import json

# Records 1193 to 1406
data = [
[1193,"Asela","A/Engineering","AMFP","On-Farm Evaluation and Demonstration of the Modified Animal-Drawn Spike-Tooth Harrow","Degefa Woyessa","Accepted",""],
[1194,"Asela","A/Engineering","AMFP","Modification and On-Farm Evaluation of an Engine-Operated Animal Feed Mixer into a Biochar-Based Fertilizer Mixing Machine","Degefa Woyessa & Ashebir Tsegaye","Rejected",""],
[1195,"Asela","A/Engineering","AMFP","Modification and Performance evaluation of a Walking-behind Row Planter for Inter-Row Cultivation","Wabi Tafa","Rejected",""],
[1196,"Asela","A/Engineering","AMFP","On-Farm Evaluation and Demonstration of Walking-Behind Harvester","Gosa Bekele and Ashebir Tsegaye","Accepted",""],
[1197,"Asela","A/Engineering","AMFP","Adaptation and Performance Evaluation of Mini Combiner","Ashebir Ts, Abulasan K, Degefa W","Accepted",""],
[1198,"Asela","A/Engineering","AMFP","On-Farm Evaluation and Verification of a Mini-tractor Drawn Onion Harvester","Wabi Tafa & Girum Merga","Rejected",""],
[1199,"Asela","A/Engineering","AMFP","On-Farm Evaluation and Demonstration of Engine-Driven Sunflower Thresher","Abulasan Keberedin","Conditionally Accepted",""],
[1200,"Asela","A/Engineering","AMFP","Adaptation and Performance Evaluation of 'MAQTRON' Multi-Crop Thresher","Ashebir Tsegaye","Rejected",""],
[1201,"BEARC","A/Engineering","AMFP","Adaptation and Performance Evaluation of an Engine-Driven Compost Turner for Organic Farming in West Shewa","Seyfeddin.A","Rejected",""],
[1202,"BEARC","A/Engineering","AMFP","On-farm evaluation and demonstration of a potato Grading machine","Seyfeddin.A","Accepted",""],
[1203,"BEARC","A/Engineering","AMFP","Adaptation and performance evaluation of a tractor-drawn combined tillage implement","Abdurehman.S","Rejected",""],
[1204,"BEARC","A/Engineering","AMFP","Adaptation and performance evaluation of an engine-operated grain picker modified to 'Development and performance evaluation of an engine-operated grain Cleaner and Conveyor'","Abdurehman.S","Accepted",""],
[1205,"BEARC","A/Engineering","AMFP","Development and Performance Evaluation of PTO Driven Three Rows Maize Planter modified to Modification and Performance Evaluation of PTO Driven Three Rows Maize Planter","Teresa.D","Accepted",""],
[1206,"BEARC","A/Engineering","AMFP","Adaptation and Performance Evaluation of Tractor-Drawn Faba Bean Planter modified to 'On-farm evaluation and demonstration of Tractor-Drawn Faba Bean Planter'","Desta A","Conditionally Accepted",""],
[1207,"BEARC","A/Engineering","AMFP","On-Farm Evaluation and Verification of Animal-Drawn Teff Seedbed Dumper","Makbib.A","Accepted",""],
[1208,"BEARC","A/Engineering","AMFP","Development and Performance Evaluation of an Engine-Operated Urea Applicator and Cultivator for Row Crops","Merga W.","Conditionally Accepted",""],
[1209,"Fedis","A/Engineering","AMFP","Development and evaluation of engine-operated potato hiller for small-scale farmers. Modified 'On-farm evaluation and demonstration of tractor-drawn potato hiller'","Bedasa W.and Milkesa A.","Accepted",""],
[1210,"Fedis","A/Engineering","AMFP","Improvement and Evaluation of an Engine-Operated Multi-Grain Cleaning and Grading Machine","Bedasa W.and Teshome U.","Rejected",""],
[1211,"Fedis","A/Engineering","AMFP","On-farm evaluation and demonstration of a tractor-mounted potato planter for potato-growing farmers","Bedasa W.and Milkesa A.","Accepted",""],
[1212,"Fedis","A/Engineering","AMFP","Improvement and evaluation of manual-operated fruit harvester","Bedasa W.and Milkesa A.","Rejected",""],
[1213,"Fedis","A/Engineering","AMFP","On-farm evaluation of engine-operated maize harvester for small-scale farmers in Hararghe","Milkesa A.","Rejected",""],
[1214,"Fedis","A/Engineering","AMFP","Development and performance evaluation of manually operated multi-crop planter for small-scale farmers","Milkesa A.","Conditionally Accepted",""],
[1215,"Fedis","A/Engineering","AMFP","Improvement and evaluation of engine-driven groundnut stripper","Milkesa A.and Bedasa w.","Accepted",""],
[1216,"Fedis","A/Engineering","AMFP","Improvement and evaluation of engine-operated motorized plough","Milkesa A.","Rejected",""],
[1217,"Fedis","A/Engineering","AMFP","Improvement and evaluation of IITA Multi-crop thresher to PTO driven multi-crop thresher","Teshome U.Bedasa","Conditionally Accepted",""],
[1218,"Fedis","A/Engineering","AMFP","Improvement and evaluation of animal-drawn groundnut digger to tractor-driven groundnut digger","Teshome U.Bedasa","Rejected",""],
[1219,"Fedis","A/Engineering","AMFP","Development and Evaluation of an Engine-Driven Multi-Row Hot Pepper Planter for Smallholder Farmers in West Hararghe Zone","Teshome U.","Rejected",""],
[1220,"Jima","A/Engineering","AMFP","On-farm evaluation of Spike Tooth-type Rice Thresher Machine","Rebira Wirtu","Rejected",""],
[1221,"Jima","A/Engineering","AMFP","Modification and performance evaluation for tractor-drawn teff threshing machine","Rebira Wirtu","Rejected",""],
[1222,"Jima","A/Engineering","AMFP","Modification and performance evaluation of the JAERC model animal-drawn manure applicator to a tractor-drawn. The title was modified to 'Development and Performance evaluation of PTO operated manure applicator'","Rebira Wirtu","Accepted",""],
[1223,"Jima","A/Engineering","AMFP","Adaptation and PE of potato tractor-drawn hiller for maize inter-row cultivator","Rebira Wirtu","Rejected",""],
[1224,"Jima","A/Engineering","AMFP","Adaptation and performance evaluation of an engine-operated backpack chemical sprayer","Rebira Wirtu","Rejected",""],
[1225,"Jima","A/Engineering","AMFP","Adaptation and performance evaluation of engine-operated coffee Stumping Machine","Rebira Wirtu","Conditionally Accepted",""],
[1226,"Jima","A/Engineering","AMFP","On-farm evaluation of tractor-drawn multi-crop planter modified to 'On-farm evaluation and demonstration of multi-crop planter'","Rebira Wirtu","Conditionally Accepted",""],
[1227,"Jima","A/Engineering","AMFP","Development and evaluation of soybean planter for small-scale farmers","Wasihun Mitiku","Conditionally Accepted",""],
[1228,"Jima","A/Engineering","AMFP","Adaptation and performance evaluation of non-grounding teff seed drills","Wasihun Mitiku","Rejected",""],
[1229,"Jima","A/Engineering","AMFP","On-Farm Evaluation and Demonstration of an Animal-Drawn Groundnut Digger","Wasihun Mitiku","Rejected",""],
[1230,"Jima","A/Engineering","AMFP","Development and Evaluation of a Cassava Peeling and Chipping Machine for Rural Processors","Wasihun Mitiku","Accepted",""],
[1231,"Jima","A/Engineering","AMFP","On-Farm Evaluation of Improved Engine-Operated Sorghum Thresher","Anane Gemeda","Rejected",""],
[1232,"Jima","A/Engineering","AMFP","Development and Performance Evaluation of Tractor-Drawn Inter-Row Maize Weeder","Anane Gemeda","Rejected",""],
[1233,"Jima","A/Engineering","AMFP","Development and Performance Evaluation of Tractor Groundnut Planter","Anane Gemeda","Rejected",""],
[1234,"Jima","A/Engineering","AMFP","Design, Development and Performance Evaluation of a Semi-Mechanical Coffee Harvesting Machine","Anane Gemeda","Conditionally Accepted",""],
[1235,"Asela","A/Engineering","PHAPP","Development and Performance Evaluation of engine Cactus Pad Shredder for livestock feed purpose","Abayineh A","Rejected",""],
[1236,"Asela","A/Engineering","PHAPP","Development and performance evaluation of forced ventilation evaporative cooling system for the preservation of fresh vegetables and fruits","Abayineh A","Rejected",""],
[1237,"Asela","A/Engineering","PHAPP","Adaptation and Demonstration of Integrated Coffee Pulper and Demucilager Machine","Abbe T","Accepted",""],
[1238,"Asela","A/Engineering","PHAPP","On farm Evaluation and verification of Groundnut Stripper","Rabirra N","Accepted",""],
[1239,"Asela","A/Engineering","PHAPP","Adaptation and Performance Evaluation of Engine Driven Seed Grading and Cleaning Machine","Rabirra N","Rejected",""],
[1240,"Asela","A/Engineering","PHAPP","Development and Evaluation of wheat and Barley dehulling and milling machine","Girum M","Rejected",""],
[1241,"Asela","A/Engineering","PHAPP","On farm evaluationand demonstration of integrated pto driven chopper and miller","Ashebir Thegahe, Rabirra N","Accepted",""],
[1242,"BEARC","A/Engineering","PHAPP","On Farm Evaluation and Modification of Engine Operated Groundnut Shelling Machine","Abdo.H","Conditionally Accepted",""],
[1243,"BEARC","A/Engineering","PHAPP","Adaptation and Evaluation of Engine operated Multi-Crop Cleaning Machine","Abdo.H and Abdurehman S","Rejected",""],
[1244,"BEARC","A/Engineering","PHAPP","Improvement and performance evaluation of integrated Warqe processing machine","Merga W.","Conditionally Accepted",""],
[1245,"BEARC","A/Engineering","PHAPP","Adaptation and Performance Evaluation of a Motorized Horizontal Animal Feed Chopper for Multi-Crop Residue Processing","Merga W.","Rejected",""],
[1246,"BEARC","A/Engineering","PHAPP","Adaptation and performance evaluation of PTO operated straw baller","Desta A","Accepted",""],
[1247,"Jima","A/Engineering","PHAPP","Adaptation and On-Farm Evaluation of Imported Beeswax Foundation Sheet Casting Mold","Tashome Wakeyo","Rejected",""],
[1248,"Jima","A/Engineering","PHAPP","Adaptation and Performance Evaluation of Milking Machine","Tashome Wakeyo","Rejected",""],
[1249,"Jima","A/Engineering","PHAPP","Adaptation and Demonstration of PTO Driven Straw Baler","Husen Bona","Accepted",""],
[1250,"Jima","A/Engineering","PHAPP","Modification and Evaluation of an Engine-Operated Lentil Splitting Machine","Husen Bona","Accepted",""],
[1251,"Jima","A/Engineering","PHAPP","Adaptation and Verification of Pea Milling Machine","Husen Bona","Rejected",""],
[1252,"Jima","A/Engineering","PHAPP","On-farm Evaluation and Verification of Pollen Trap","Husen Bona","Rejected",""],
[1253,"Jima","A/Engineering","PHAPP","On-farm Evaluation and Demonstration of an Integrated PTO Operated Animal feed Chopper and Miller","Husen Bona, Tashome Wakeyo, Tolasa Berhanu","Accepted",""],
[1254,"Jima","A/Engineering","PHAPP","On-farm Performance Evaluation of RF-450 Multi-crop Thresher","Husen Bona and Tolasa Berhanu","Accepted",""],
[1255,"Jima","A/Engineering","PHAPP","Development of PTO-operated Horizontal Ribbon-Type Feed Mixer","Husen Bona","Accepted",""],
[1256,"Jima","A/Engineering","PHAPP","Modification and Performance Evaluation of a Manually Operated Milk Churner to an Electrically Operated Churner","Tolasa Berhanu","Rejected",""],
[1257,"Jima","A/Engineering","PHAPP","Adaptation and Performance Evaluation of a Milk Product Packaging machine","Tolasa Berhanu","Rejected",""],
[1258,"Jima","A/Engineering","PHAPP","Development and Performance Evaluation of a Yogurt Incubator","Tolasa Berhanu","Rejected",""],
[1259,"Jima","A/Engineering","PHAPP","Modification of Manually Operated Coffee Demucilager to Vertical Type Electrically Operated","Tolasa Berhanu","Rejected",""],
[1260,"Jima","A/Engineering","PHAPP","Modification of Engine-Operated Top Hammer Miller to PTO Operated for Poultry Feed Grinding","Tolasa Berhanu","Rejected",""],
[1261,"Jima","A/Engineering","PHAPP","Comparative Performance Evaluation and Selection of Animal Feed Chopper","Tolasa Berhanu","Accepted",""],
[1262,"Jima","A/Engineering","PHAPP","Evaluation of Solar Dryer for Parboiled Rice Drying","Tolasa Berhanu","Rejected",""],
[1263,"Jima","A/Engineering","PHAPP","Modification and Performance Evaluation of Wheat and Barley Threshing Machine","Tolasa Berhanu","Rejected",""],
[1264,"Jima","A/Engineering","PHAPP","Adaptation and Evaluation of Grinding and Sieving Equipment for Biochar Production","Teka Tesfaye (PhD)","Rejected",""],
[1265,"HBRC","A/Engineering","PHAPP","Modification and performance evaluation of Steam beeswax extractor","Gadisa Beyena","Conditionally Accepted",""],
[1266,"HBRC","A/Engineering","PHAPP","Development and evaluation of rectangular clay hive for Stingless Bee","Gadisa Beyena","Accepted",""],
[1267,"HBRC","A/Engineering","PHAPP","Development and Evaluation of a Honey Uncapping Machine","Gadisa Beyena","Rejected",""],
[1268,"HBRC","A/Engineering","PHAPP","Evaluating the Effect of Hive Insulation on Honey Bee Performance in Cold Climate area of Ethiopia","Gadisa Beyena","Rejected",""],
[1269,"HBRC","A/Engineering","PHAPP","Development, and Performance Evaluation of a Suction-Based Honey Harvesting","Gelana Fufi","Rejected",""],
[1270,"HBRC","A/Engineering","PHAPP","Development, and performance evaluation of crude honey extractor","Gelana Fufi","Conditionally Accepted",""],
[1271,"HBRC","A/Engineering","PHAPP","Design, Fabrication, and Evaluation of a Stingless Bee Hive","Gelana Fufi","Rejected",""],
[1272,"Fedis","A/Engineering","PHAPP","Adaptation and Evaluation of Rice polisher Design","Birhanu Atomsa","Rejected",""],
[1273,"Fedis","A/Engineering","PHAPP","Adaptation and Participatory Evaluation of Poultry Feed pelleting machine","Birhanu Atomsa","Rejected",""],
[1274,"Fedis","A/Engineering","PHAPP","Adaptation and Performance Evaluation of a Cassava Peeling Machine","Bayissa Tarecha","Accepted",""],
[1275,"Fedis","A/Engineering","PHAPP","Modification and Performance Evaluation of an Animal Feed Chopper for Cactus Feed Processing","Bayissa Tarecha","Rejected",""],
[1276,"Fedis","A/Engineering","PHAPP","Adaptation and Performance Evaluation of a Soybean Dehulling Machine","Bayissa Tarecha","Conditionally Accepted",""],
[1277,"Fedis","A/Engineering","PHAPP","Adaptation and Performance Evaluation of Poultry Feed Miller and Mixer","Bayissa T. & Birhanu Atomsa","Rejected",""],
[1278,"Fedis","A/Engineering","PHAPP","Development and evaluation of an Engine-Operated Root Crop Washing Machine","Keneni Kebede & Jemal Nur","Accepted",""],
[1279,"Fedis","A/Engineering","PHAPP","Adaptation and Performance Evaluation of dough kneading machine","Keneni Kebede","Rejected",""],
[1280,"Fedis","A/Engineering","PHAPP","On farm evaluation and verification engine driven groundnut decorticator","Tashome Urge & Bayissa Tarecha","Accepted",""],
[1281,"ATARC","A/Engineering","IDWH","Effects Irrigation Levels and Biochar rates on Yield and Water Productivity of Onion in Negele Arsi district, West Arsi Zone of Oromia, Ethiopia","Dulo Husen","Accepted",""],
[1282,"ATARC","A/Engineering","IDWH","GIS-based Surface Irrigation Suitability Assessment in Huluka sub watershed, Rift Valley Lake Basin, Ethiopia","Dulo Husen","Accepted",""],
[1283,"ATARC","A/Engineering","IDWH","Identification and Prioritization of Suitable Rain Water Harvesting Sites Using GIS-Based Spatial Analysis in Adami Tulu Jido Kombolcha district, East Shewa Zone of Oromia, Ethiopia","Dulo Husen","Accepted",""],
[1284,"ATARC","A/Engineering","IDWH","Effect of Regulated Deficit Irrigation Management on Head cabbage at Adami Tulu Agricultural Research Center","Anbese Ambomsa","Rejected",""],
[1285,"ATARC","A/Engineering","IDWH","Evaluation of Smart Irrigation Scheduling Using Soil Moisture Sensor for Enhancing Tomato Water Productivity in Dugda District, Oromia, Ethiopia","Anbese Ambomsa","Conditionally Accepted",""],
[1286,"ATARC","A/Engineering","IDWH","Effect of Optimal Irrigation Scheduling and Nitrogen Fertilizer Rates on Yield and water productivity of Potato (Solanum tuberosum L.) Production in Shashemene Town, Oromia, Ethiopia","Anbese Ambomsa","Accepted",""],
[1287,"ATARC","A/Engineering","IDWH","Determination of Optimal Irrigation Scheduling for Carrot in Shashamanne District, West Arsi Zone, Oromia","Anbese Ambomsa","Conditionally Accepted",""],
[1288,"ATARC","A/Engineering","IDWH","Determination of Crop Water Requirement and Spatial Mapping for Major crops in selected district of East Shewa and West Arsi zones","Zelalem Shalemaw","Accepted",""],
[1289,"ATARC","A/Engineering","IDWH","Evaluation of Crop water requirement and irrigation scheduling on growth and yield of papaya at Adami Tulu Agricultural Research Center","Zelalem Shalemaw","Accepted",""],
[1290,"ATARC","A/Engineering","IDWH","Determination of Optimal Irrigation Scheduling for Avocado production at Adami Tulu Agricultural Research Center","Zelalem Shalemaw","Rejected",""],
[1291,"ATARC","A/Engineering","IDWH","On Farm Evaluation of Irrigation level and nitrogen fertilizer levels for head cabbage Yield and Water Productivity in Negele Arsi district","Zelalem Shalemaw","Accepted",""],
[1292,"ATARC","A/Engineering","IDWH","On farm Evaluation and Verification of the Effects of Irrigation and Nitrogen Fertilizers Management on Yield and Water Productivity of Tomato at ATJK district","Zelalem Shalemaw","Accepted",""],
[1293,"ATARC","A/Engineering","IDWH","Determination of supplementary irrigation of water requirement and irrigation scheduling for maize at on station","Zelalem Shalemaw","Accepted",""],
[1294,"ATARC","A/Engineering","IDWH","Determination of supplementary irrigation water requirement and irrigation scheduling for Wheat at ATJK district","Zelalem Shalemaw","Rejected",""],
[1295,"YPDARC","A/Engineering","IDWH","Determination of optimal irrigation scheduling for Green cob Maize production at Moyale District, Borana zone, Southern Ethiopia.","Demisachew Tadele","Accepted",""],
[1296,"YPDARC","A/Engineering","IDWH","Evaluation of Suitable Furrow Methods on water productivity and Yield of Potato (Solanum Tuberosum L.) Yield at Burquqe Scheme in Moyale District, Borana Zone","Demisachew Tadele","Rejected",""],
[1297,"YPDARC","A/Engineering","IDWH","Determination of Optimum Irrigation Scheduling for Potato Yield and Water Use Efficiency under Furrow Irrigation System at Moyale Districts of Borana zone","Demisachew Tadele","Accepted",""],
[1298,"YPDARC","A/Engineering","IDWH","Determination of Optimal Irrigation Scheduling for Sesame (Sesamum indicum L.) and water use efficiency at Dubuluk District, Borana Zone.","Demisachew Tadele","Rejected",""],
[1299,"SARC","A/Engineering","IDWH","Evaluation of Soil Moisture Meter-Based Irrigation Scheduling for Growth, Yield, and Water Use Efficiency of Watermelon in Bale Lowlands","Chala Chimdessa","Accepted",""],
[1300,"SARC","A/Engineering","IDWH","Groundwater Potential and Recharge Zone Mapping for Sustainable Water Resource Management Using GIS and Remote Sensing Techniques: The Shaya Watershed, Bale Zone, Southeastern Ethiopia","Chala Chimdessa","Accepted",""],
[1301,"SARC","A/Engineering","IDWH","Evaluation of Wheat (Triticum aestivum L.) Sowing Depth on Seedling Emergence, Soil Moisture Use Efficiency, and Yield at Bale Highland Ethiopia","Chala Chimdessa","Rejected",""],
[1302,"SARC","A/Engineering","IDWH","Spatiotemporal Assessment of Soil Moisture and Evapotranspiration Using Satellite Data and GIS Techniques","Chala Chimdessa","Accepted",""],
[1303,"Harosabu","A/Engineering","IDWH","Effect of deficit irrigation levels at different growth stages on yield and water productivity of furrow irrigation on Onion (Allium cepa L.) in Kellem Wollega Zone, Western Oromia","Daksisa Namomsa","Accepted",""],
[1304,"Harosabu","A/Engineering","IDWH","Determination of irrigation scheduling on groundnut yield at Kellem Wollega Zone, Western Oromia","Daksisa Namomsa","Accepted",""],
[1305,"Harosabu","A/Engineering","IDWH","Evaluation of Deficit Irrigation on Tomato Yield and Water Use Efficiency in Kellem Wollega Zone of Selected Districts,Western Oromia","Daksisa Namomsa","Rejected",""],
[1306,"BARC","A/Engineering","IDWH","On farm evaluation and Demonstration of Irrigation scheduling methods for wheat and potato crops at Wayu Tuka and Jima Ganati districts","Adisu Tadesse","Conditionally Accepted",""],
[1307,"BARC","A/Engineering","IDWH","On-farm evaluation and demonstration of Irrigation Methods with different irrigation frequencies and nitrogen rates on yield and Water use Efficiency of Wheat at Chelia and Wayu Tuka","Adisu Tadesse","Conditionally Accepted",""],
[1308,"BARC","A/Engineering","IDWH","Evaluation of mini sprinkler irrigation system for head cabbage Water Use efficiency and pest control at Bako Agricultural Research Center","Adisu Tadesse","Rejected",""],
[1309,"BARC","A/Engineering","IDWH","Determination of Optimum Irrigation Schedule for Coffee under Supplementary Irrigation at Bako Agricultural Research Center","Adisu Tadesse","Rejected",""],
[1310,"BARC","A/Engineering","IDWH","Comparative Effects of Compost, Farmyard Manure, and Biochar Amendments on Soil Water Retention, Crop Performance","Desalegn Dibaba","Accepted",""],
[1311,"BARC","A/Engineering","IDWH","Development and Evaluation of a Low-Cost Greywater for Irrigation in Sustainable Urban Crop Production in Nekemte City, East Wollega Zone, Ethiopia","Desalegn Dibaba","Rejected",""],
[1312,"BARC","A/Engineering","IDWH","Evaluation of Basin Irrigation System Performance for Lowland Rice (Oryza sativa L.) Production at Jimma Geneti District, Oromia, Ethiopia","Desalegn Dibaba","Rejected",""],
[1313,"BARC","A/Engineering","IDWH","Development and Performance Evaluation of a Cloud-Based Smart Irrigation Monitoring and Control System for Real-Time Irrigation Scheduling of Wheat (Triticum aestivum L.) Production at Chelia District, Ethiopia","Desalegn Dibaba","Conditionally Accepted",""],
[1314,"BARC","A/Engineering","IDWH","Optimization of Irrigation Scheduling for Improving Watermelon (Citrullus lanatus) production and Water Use Efficiency","Adisu Tadesse","Rejected",""],
[1315,"Mechara","A/Engineering","IDWH","Effects of Irrigation Levels and Fertilizer Rates on Yield, Yield Components, and Water Productivity of Onion (Allium cepa L.) at Daro Lebu and Oda Bultum District","Ayana Bulti","Accepted",""],
[1316,"Mechara","A/Engineering","IDWH","Integrated Effects of Biochar, Irrigation, and Fertilizer on Tomato (Solanum lycopersicum L.) Yield and Water Productivity in Oda Bultum and Daro Lebu Districts","Ayana Bulti","Accepted",""],
[1317,"Mechara","A/Engineering","IDWH","Effects of Irrigation and Fertilizer rate on Cabbage Head Formation and Water Productivity at Oda Bultum and Daro Lebu Districts","Ayana Bulti","Accepted",""],
[1318,"Mechara","A/Engineering","IDWH","Determination of Crop Water Requirement for Watermelon (Citrullus lanatus) at Machara On station","Ayana Bulti","Accepted",""],
[1319,"Mechara","A/Engineering","IDWH","Determination of optimum irrigation scheduling and water productivity of sorghum at Mechara on Station, Ethiopia","Bayisa Muleta","Accepted",""],
[1320,"Fitche","A/Engineering","IDWH","Evaluation of Bed Width and Irrigation Levels under Broadcasted Raised Bed System on Growth, Yield, Root Quality, and Water Productivity of Carrot (Daucus carota L.) at Wachale District, Oromia","Tsehay Muluneh","Rejected",""],
[1321,"Fitche","A/Engineering","IDWH","Evaluation of Planting Density and Irrigation Levels under Conventional Furrow Irrigation on Growth, Yield and Water Productivity of Cabbage (Brassica oleracea var. capitata) at Wachale District, North Shewa zone Oromia","Tsehay Muluneh","Rejected",""],
[1322,"Fitche","A/Engineering","IDWH","Determination of Irrigation Schedule and Furrow Irrigation Methods of Potato at Debra Libanos District of North Shewa Zone, Oromia","Gutata Xilahun","Accepted",""],
[1323,"Fitche","A/Engineering","IDWH","Evaluating Effect of Furrow Irrigation Methods and Fertilizer Rate on Yield of Tomato and Water Use Efficiency at Wachale District, North Shewa Zone of Oromia","Gutata Xilahun","Accepted",""],
[1324,"Fitche","A/Engineering","IDWH","Effects of different bed width and furrow irrigation methods on yield of Onion and water use efficiency at Debra Libanos district, North Shewa of Oromia","Gutata Xilahun","Rejected",""],
[1325,"Fitche","A/Engineering","IDWH","Groundwater Potential Zone Mapping With the Integration Of Geospatial Techniques and Multi Criteria Decision Analysis Method in North Shewa Zone, Oromia, Ethiopia","Woubalem Abera","Conditionally Accepted",""],
[1326,"Bore","A/Engineering","IDWH","Effect of deficit irrigation and straw mulch levels on Green cob maize yield and water productivity in Abaya District, West Guji zone, Ethiopia","Tesfaye Gragn","Accepted",""],
[1327,"Bore","A/Engineering","IDWH","Effects of deficit irrigation and biochar addition on tomato growth, yield, and soil physicochemical properties at Adola district of Guji Zone, Southern Ethiopia","Tesfaye Gragn","Accepted",""],
[1328,"Bore","A/Engineering","IDWH","Spatial estimation and Validations of Crop Water Requirements for Major Vegetable Crops Using CROPWAT Model at Adola District, Guji zone Southern Ethiopia","Tesfaye Gragn & Alemayehu Mamo","Rejected",""],
[1329,"Bore","A/Engineering","IDWH","Effects of irrigation regime and frequency on yield and water use efficiency of mung bean (Vigna radiata L.) at Guji Zone, Adola rede district, Oromia Region Ethiopia","Obsa Wolde","Accepted",""],
[1330,"Bore","A/Engineering","IDWH","Determination of Optimum Irrigation Interval and Water Demand of Groundnut at West Guji Zone, Abaya District, Oromia Region, Ethiopia","Obsa Wolde","Accepted",""],
[1331,"Bore","A/Engineering","IDWH","Determination of Optimal Irrigation Scheduling for Sesame (Sesamum indicum L.) at Abaya District, Oromia region Ethiopia","Obsa Wolde","Accepted",""],
[1332,"Bore","A/Engineering","IDWH","Effects of Irrigation Scheduling Based on Soil Moisture Depletion on Yield and Water Productivity of Alfalfa at the mid land of Guji Zone, Southern, Ethiopia.","Alemayehu Mamo","Accepted",""],
[1333,"Asela","A/Engineering","IDWH","On-farm Evaluation and Demonstration of Flexible Gated Pipe on yield and water productivity of Maize","Asnake Tilaye","Accepted",""],
[1334,"Asela","A/Engineering","IDWH","On farm Evaluation of Impact Sprinkler on Yield and Water Productivity of Wheat","Asnake Tilaye","Accepted",""],
[1335,"Asela","A/Engineering","IDWH","Integrative effect of mulch and deficit irrigation on yield and water productivity of Tomato at Doddota Irrigation Scheme","Fikadu Gemeda","Rejected",""],
[1336,"Asela","A/Engineering","IDWH","Technical Assessment of the Existing Runoff Water Harvesting Status in Doddota District of Arsi Zone","Fikadu Gemeda","Accepted",""],
[1337,"Asela","A/Engineering","IDWH","Determining of proper irrigation schedule for hot pepper (Capsicum annuum L.) at the Doddota Irrigation Scheme (Arsi Zone, Oromia, Ethiopia)","Bayan Ahmed","Accepted",""],
[1338,"Asela","A/Engineering","IDWH","Technical Performance Evaluation of Small-Scale Irrigation Schemes in Arsi Zone","Bayan Ahmed","Accepted",""],
[1339,"Asela","A/Engineering","IDWH","Development and Evaluation of Pertian wheel as a Water Lifter for Irrigation","Negash Bedaso","Rejected",""],
[1340,"Asela","A/Engineering","IDWH","Development and Performance Evaluation of Low-Cost Solar Water pump for small scale Irrigation","Fikadu Gemeda","Conditionally Accepted",""],
[1341,"Jima","A/Engineering","IDWH","On-farm Evaluation and Demonstration of the Alternative Furrow Irrigation (AFI) Method on Garlic Production in Nada, Jimma Zone, Ethiopia","Abu Dedo","Rejected",""],
[1342,"Jima","A/Engineering","IDWH","On-Farm Evaluation and Optimization of Perforated-Pipe Subsurface Drainage Systems for Waterlogging Control and Crop Productivity Improvement in Shabe Woreda, Jimma Zone, Southwestern Ethiopia","Abu Dedo","Conditionally Accepted",""],
[1343,"Jima","A/Engineering","IDWH","Future Projections of Crop Water Requirements and Irrigation Water Demand under Climate Change Using Bias-Corrected Regional Climate Model Outputs","Abu Dedo","Accepted",""],
[1344,"Jima","A/Engineering","IDWH","Optimization of Crop Area Allocation and Irrigation Water Distribution under Limited Water Availability Using the WEAP Model: A Case Study of the Kawa Irrigation Scheme, Dedo Woreda, Jimma Zone, Ethiopia","Abu Dedo and Roba Adugna","Rejected",""],
[1345,"Jima","A/Engineering","IDWH","Adaptation and On-Farm Evaluation of Drip-Based Supplementary Irrigation and Fertigation Technologies for Increasing Coffee Production and Productivity in the Jimma Area, Southwest Ethiopia","Roba Adigna","Rejected",""],
[1346,"Jima","A/Engineering","IDWH","Evaluating the Effect of Biochar Particle Sizes Added on Different Types of Soil in the South Western Part of Oromia","Teka Tesfaye (PhD) and Roba Adugna","Accepted",""],
[1347,"Jima","A/Engineering","IDWH","Evaluating the Effect of One-Time and Continuous Application of Biochar on Water-Holding Capacity and Crop Yield during Three Consecutive Periods of Crop Cultivation in the Southwestern Part of Oromia","Teka Tesfaye (PhD) and Roba Adugna","Accepted",""],
[1348,"Jima","A/Engineering","IDWH","Evaluation of furrow irrigation method at different irrigation levels on yield and water productivity of watermelon at Omo Nadda, Jimma Zone SWO","Abu Dedo and Roba Adugna","Rejected",""],
[1349,"Fedis","A/Engineering","IDWH","Evaluation of current salinity status of cluster irrigated initiative crops in East Hararghe","Jamal Nur","Accepted",""],
[1350,"Fedis","A/Engineering","IDWH","Assessment of impact climate change on ground water table and economical challenges","Jamal Nur","Rejected",""],
[1351,"Fedis","A/Engineering","IDWH","Effect of planting techniques on furrow ridge system using poor quality ground water source on yield and yield responses","Jamal Nur","Accepted",""],
[1352,"Fedis","A/Engineering","IDWH","Evaluation of different types of in-situ rain water harvesting structures for maize production to improve moisture stress in low land area of Babile district","Lalisa Ofga","Accepted",""],
[1353,"Fedis","A/Engineering","IDWH","Evaluation of Irrigation Methods and Irrigation Interval for papaya production and water productivity at babile district","Lalisa Ofga","Accepted",""],
[1354,"Fedis","A/Engineering","IDWH","Evaluation of different types of in-situ rain water harvesting structures for sorghum production to improve moisture stress in low land area of Babile district","Lalisa Ofga","Accepted",""],
[1355,"Fedis","A/Engineering","IDWH","Optimizing Rooftop Rainwater Harvesting for Supplemental Irrigation in Semi-Arid East Hararghe","Ayela Tade","Rejected",""],
[1356,"Fedis","A/Engineering","IDWH","Biochar and Deficit Irrigation Effects on Soil-Water-Crop Dynamics","Ayela Tade","Accepted",""],
[1357,"Fedis","A/Engineering","IDWH","Alternate vs Every Furrow Irrigation for Onion Water Savings and Yield","Ayela Tade","Accepted",""],
[1358,"Fedis","A/Engineering","IDWH","Spatial-temporal Rainfall Trend and Variability Assessment in the South Eastern Oromia","Ayela Tade","Accepted",""],
[1359,"BEARC","A/Engineering","IDWH","Effect of Optimal Soil Moisture Depletion Levels for Improving Yield and Water Productivity of Malt Barley (Hordeum vulgare L.) in Ambo District, West Shewa","Gudeta G.","Rejected",""],
[1360,"BEARC","A/Engineering","IDWH","Evaluation of Drip Irrigation and Fertigation Practices for Improving Coffee Yield and Water Productivity in Western Oromia, Ethiopia","Gudeta G.","Accepted",""],
[1361,"BEARC","A/Engineering","IDWH","Spatial Assessment of Irrigation Performance and Crop Water Productivity using Remote Sensing and GIS: A Case study of Toke Kutaye Woreda, West shewa zone","Gudeta G.","Conditionally Accepted",""],
[1362,"BEARC","A/Engineering","IDWH","On-Farm Evaluation and Demonstration of Furrow Irrigation Technology for Sustainable Rice Production in Western Oromia, Ethiopia","Habtamu B.","Accepted",""],
[1363,"BEARC","A/Engineering","IDWH","Effect of Different Levels of Water Stress on Growth, Yield, and Water-use Efficiency of Lentil (lens culinaris medik) in Ambo District","Habtamu B.","Accepted",""],
[1364,"BEARC","A/Engineering","IDWH","Adaptation and performance evaluation of engine driven water well-drilling machine","Eshetu M.","Rejected",""],
[1365,"BEARC","A/Engineering","IDWH","Adaptation and Performance Evaluation of Engine-Powered 5-inch Water Pump","Eshetu M.","Conditionally Accepted",""],
[1366,"BEARC","A/Engineering","IDWH","Determining the Optimum Irrigation Regime for Beetroot (Beta vulgaris L.) Production in West Shoa, Oromia.","Eshetu M.","Accepted",""],
[1367,"BeARC","A/Engineering","IDWH","Determining the irrigation regime of watermelon at Bako Tibe in Western Oromia, Ethiopia","Eshetu M.","Accepted",""],
[1368,"Asela","A/Engineering","Renergy","Adaptation and Performance Evaluation of BAERC Updraft Biomass Gasifier Stove","Getachew Hailu","Rejected",""],
[1369,"Asela","A/Engineering","Renergy","Selection and characterization binding material of pelletized biochar based fertilizer","Getachew Hailu","Rejected",""],
[1370,"Asela","A/Engineering","Renergy","Participatory evaluation and dissemination of JAERC biomass cook stove at house hold level","Getachew Hailu","Conditionally Accepted",""],
[1371,"Asela","A/Engineering","Renergy","Development and Evaluation of a Solar-Powered Rural Mini-Grid Electrification Technology","Girum Merga","Accepted",""],
[1372,"BEARC","A/Engineering","Renergy","Adaptation, Design, and Performance Evaluation of a Manual Stick Briquetting Machine for Biomass Fuel Production","Gemechis M.","Rejected",""],
[1373,"BEARC","A/Engineering","Renergy","Participatory Performance Evaluation of a Top-Lit Updraft Gasifier Cookstove","Gemechis M.","Accepted",""],
[1374,"BEARC","A/Engineering","Renergy","Adaptation and Performance Evaluation of a Rotating Drum Composter under Different Turning Frequencies","Gemechis M.","Rejected",""],
[1375,"BEARC","A/Engineering","Renergy","On-Farm Performance Evaluation of a Charcoal Evaporative Cooler for Short-Term Storage of Fresh Fruits and Vegetables","Gemechis M.","Rejected",""],
[1376,"BEARC","A/Engineering","Renergy","Adaptation and Participatory Evaluation of MICHU Cook Stove for Rural Communities of West Oromia, Ethiopia","Duresa T.","Rejected",""],
[1377,"BEARC","A/Engineering","Renergy","Fabrication and Experimental Evaluation of Mechanized Biochar-Compost Mixer Powered by a Direct Solar-PV Drive for Soil Acid Mitigation","Duresa T.","Rejected",""],
[1378,"BEARC","A/Engineering","Renergy","Development and Evaluation of a Modular Small-Scale Biomass Pelletizer with Adjustable Die Geometry for Rural Energy Applications","Duresa T.","Conditionally Accepted",""],
[1379,"BEARC","A/Engineering","Renergy","Development of Waste-Heat-Recovery biomass Cook stove for Cooking and Domestic Water Heating in Rural Areas","Duresa T.","Accepted",""],
[1380,"BEARC","A/Engineering","Renergy","Fabrication and Thermal Performance Evaluation of Insulating Refractory Composites from Local Clay and Teff Straw for Improved Biomass Cook stoves","Duresa T.","Accepted",""],
[1381,"BEARC","A/Engineering","Renergy","Comparative Evaluation of Metal Kon-Tiki and Earth/pit Kiln Biochar Production from Coffee Husk, Maize Cobs, and Urban Organic mixed solid Waste","Duresa T.","Rejected",""],
[1382,"BEARC","A/Engineering","Renergy","Development, Construction, and Experimental Testing of a Low-Cost Evaporative Cooling Chamber Powered by Direct-Drive DC Fans for Fruit Preservation in Hot-Arid Areas of West Oromia","Duresa T.","Accepted",""],
[1383,"BEARC","A/Engineering","Renergy","Design, Development and Performance Evaluation of a Small-Scale Waste-Plastic Pyrolyzing Machine for Producing Useful Fuel and Recyclable By-Products","Usman K.","Rejected",""],
[1384,"BEARC","A/Engineering","Renergy","Adaptation and Performance Evaluation of Hammer Mill Limestone Crusher for Black Charcoal Stone and Biomass Charcoal Conversion to Generate Biochar for Acidic Soil Amendments in Western Oromia","Usman K.","Rejected",""],
[1385,"BEARC","A/Engineering","Renergy","Technical Assessment of Mini Wind Power Potential for Rural Electrification in West Shewa and Horo Guduru Wellega","Usman K.","Rejected",""],
[1386,"BEARC","A/Engineering","Renergy","Adaptation and Performance Evaluation of Castor Bean Oil Extractor Machine to Engine-Operated Groundnut Oil Extractor for Small-Scale Enterprise in Western Oromia","Usman K.","Rejected",""],
[1387,"BEARC","A/Engineering","Renergy","Modification and Performance Evaluation of an Engine-Operated Waste Biomass Briquetting Machine to a Piston/Ram-Type Pressing Mechanism","Usman K.","Accepted",""],
[1388,"Fedis","A/Engineering","Renergy","Development and Performance Evaluation of Manually Operated Charcoal Briquette Making Machine","Abdi Ediris","Rejected",""],
[1389,"Fedis","A/Engineering","Renergy","Adaptation and Performance Evaluation of Mirt Stove for Metal Kibaba","Abdi Ediris","Accepted",""],
[1390,"Fedis","A/Engineering","Renergy","Development and Evaluation of Cabinet Type Solar Dryer for Groundnut, Hot Pepper and Coffee Bean Drying","Abdi Ediris","Rejected",""],
[1391,"Fedis","A/Engineering","Renergy","Development and Evaluation of Rocket Stove for Cleaner Cooking","Abdi Ediris","Rejected",""],
[1392,"Fedis","A/Engineering","Renergy","Adaptation and Evaluation of Household Biomass Gasifier Injera Baking Stove","Abdi Ediris","Accepted",""],
[1393,"Jima","A/Engineering","Renergy","Improvement and on farm evaluation of solar powered beeswax extractor","Adem Tibesso","Accepted",""],
[1394,"Jima","A/Engineering","Renergy","On-Farm Evaluation and Demonstration of Husk Biomass Briquette Machine","Teka Tesfaye (PhD)","Accepted",""],
[1395,"Jima","A/Engineering","Renergy","Adaptation and Evaluation of Home-made Electric and Kerosene lump Egg Incubator","Adem Tibesso","Rejected",""],
[1396,"Jima","A/Engineering","Renergy","Participatory evaluation and demonstration of Black Tea processing machine","Adem Tibesso","Conditionally Accepted",""],
[1397,"Jima","A/Engineering","Renergy","Adaptation and performance evaluation of a tea dryer for soybean roasting","Abduselam Aliyi","Rejected",""],
[1398,"Jima","A/Engineering","Renergy","Adaptation and Performance Evaluation of a Rocket-Type Bread Baking Oven","Abduselam Aliyi","Rejected",""],
[1399,"Jima","A/Engineering","Renergy","Adaptation of an Orthodox tea processing machine to evaluate the effects of feeding rate and rolling pressure on tea quality","Teka Tesfaye (PhD)","Rejected",""],
[1400,"Jima","A/Engineering","Renergy","Participatory evaluation and demonstration of institutional husk biomass cook stove","Adem Tibesso","Accepted",""],
[1401,"Jima","A/Engineering","Renergy","Adaptation and Evaluation of Hot rotary drum composter","Adem Tibesso & Abduselam Aliyi","Rejected",""],
[1402,"Jima","A/Engineering","Renergy","Evaluation of bio char addition effect on biogas production on existing anaerobic digesters in South Western Part of Oromia","Teka Tesfaye (PhD)","Accepted",""],
[1403,"Jima","A/Engineering","Renergy","Comparative performance evaluation of mirt and metal pan for injera baking","Adem Tibesso","Rejected",""],
[1404,"Jima","A/Engineering","Renergy","Adaptation and participatory evaluation of coffee roasting machine","Adem Tibesso","Rejected",""],
[1405,"Jima","A/Engineering","Renergy","Comparative performance evaluation of existing improved cook stoves using different agricultural biomass feed stocks","Adem Tibesso","Rejected",""],
[1406,"Jima","A/Engineering","Renergy","Adaptation and Performance Evaluation of Biolexis Gasifier Stove","Abduselam Aliyi","Rejected",""]
]

with open("/tmp/part3_b.json", "w") as f:
    json.dump(data, f)
print("Part 3B written:", len(data))
