import json

# Records 711 to 975
data = [
[711,"Harosabu","Livestock","Feeds","Biomass Yield Performance and Chemical Composition of Sainfoin (Onobrychis viciifolia) Accessions in West and Kellam Wollega Zones of Oromia","Yerosan Wekgari","Rejected",""],
[712,"Mechara","Livestock","Api","Effect of harvesting interval on honey yield and quality at Mechara Agriculture Research Center On station","Segni Giza","Accepted with modification",""],
[713,"Mechara","Livestock","Api","Adaptation and performance evaluation of Okra (Abelmoschus esculentus L) Varieties for honeybee forage development in West Haerghe zone","Sudi Dawud","Accepted",""],
[714,"Mechara","Livestock","Api","Assessment of Honeybee Colony Loss Rates in West Hararghe zone, Oromia Regional state, Ethiopia","Dema Dugda","Accepted",""],
[715,"Mechara","Livestock","Api","Diagnostic survey of seasonal status of varroa mite prevalence in selected districts of West Hararghe Zone","Segni Giza","Accepted",""],
[716,"Mechara","Livestock","Api","Performance Evaluation of improved Vetch varieties for bee forage development in West Hararghe Zones of Oromia","Sudi Dawud","Rejected",""],
[717,"Mechara","Livestock","Api","The Effect of Honey Bee pollination on seed production of alfalfa (Medicago sativa) plant in west Hararghe zone","Sudi Dawud","Rejected",""],
[718,"Mechara","Livestock","Api","Flight intensity of honeybees and its relationship with temperature, sunshine hours, cloudiness and relative humidity at Mechara Agriculture Research Center On station","Segni Giza","Rejected",""],
[719,"Mechara","Livestock","Api","Assessment of beekeeper's colony selection practices in selected districts of West Hararghe Zone","Segni Giza","Rejected",""],
[720,"Mechara","Livestock","Api","Assessment of major honey adulterant materials in selected districts of West Hararghe Zone","Segni Giza","Rejected",""],
[721,"Mechara","Livestock","Api","Evaluation of modern beehive efficiency in selected districts of West Hararghe Zone","Segni Giza","Rejected",""],
[722,"Mechara","Livestock","Feeds","Napier Grass (Pennisetum purpureum ) RVT","Tamirat Dinkale and Lensa Urgesa","Accepted",""],
[723,"Mechara","Livestock","Feeds","Vetch (Vissia villosa) PYT","Tamrat Dinkale","Accepted",""],
[724,"Mechara","Livestock","Feeds","Buffer Grass (Cenchrus ciliaris) PYT","Tamrat Dinkale","Accepted",""],
[725,"Mechara","Livestock","Feeds","Cocksfoot (Dactylis glomerata L.) Observation Nursery","Tamrat Dinkale","Accepted",""],
[726,"Mechara","Livestock","Feeds","Determination of Proper DAP application and Row space of Cowpea (Hundaol variety) for Growth Performance, Yield Components and Nutritive Values grown under Low and mid land of West Hararghe Zone, Oromia, Ethiopia","Tamrat Dinkale","Accepted",""],
[727,"Mechara","Livestock","Feeds","Observation Nursery trial of Forage Soya bean (Glycine Max.L) genotypes","Jibrail Hassen","Accepted",""],
[728,"Mechara","Livestock","Feeds","Observation Nursery Trial of Cow Pea Genotypes in West Hararghe Zone Oromia, Ethiopia","Jibrail Hassen","Accepted",""],
[729,"Mechara","Livestock","Feeds","Setaria (Setaria sphacelata) grass Observation Nursery at Mechara ARC","Tamrat Dinkale","Rejected",""],
[730,"Mechara","Livestock","Feeds","Collection & evaluation of native forage grasses for improved Animal feed production for West Hararghe Zone, Oromia, Ethiopia","Tamrat Dinkale","Rejected",""],
[731,"Mechara","Livestock","Feeds","Introduction and Evaluation of indigenous spineless cactus (Opuntia ficus-indica L.) for maintaining drought period feed shortage in low and mid land of West Hararghe, Oromia, Ethiopia","Tamrat Dinkale","Rejected",""],
[732,"SARC","Livestock","Feeds","Susbania sesban Varieties Adaptation Trial in Highlands of Bale, and East Bale Zone","Wubshet Tesfaye.","Accepted",""],
[733,"SARC","Livestock","Feeds","Performance Evaluation of Luicienia spps for Biomass yield in highlands of Bale Zone","Wubshet Tesfaye.","Accepted",""],
[734,"SARC","Livestock","Feeds","Evaluation of Inter Row spacing of Cowpea intercropping an existing Coffee production farms for Forage yield and yield components in low lands of Bale and East Bale zone","Wubshet Tesfaye.","Accepted",""],
[735,"SARC","Livestock","Feeds","Performance Evaluation of different perennial Grass species on Bund in High and Midlands of Bale and East Bale Zone","Wubshet Tesfaye.","Accepted",""],
[736,"SARC","Livestock","Feeds","Determination of Optimum Level of fertilizer Application on common Vetch variety on forage yield and Yield Components in highlands of Bale zone","Wubshet Tesfaye.","Accepted",""],
[737,"SARC","Livestock","Feeds","Observation Nursery of Common Vetch (Vicia sativa) for the Highlands of Bale Zone","Gemechis L. and Wubshet T","Accepted",""],
[738,"SARC","Livestock","Feeds","Cowpea (Vigna unguiculata L.) l Variety Verification Trial (VVT)","Gemechis L.","Accepted",""],
[739,"SARC","Livestock","Feeds","Adaptation Trials of Improved Cassava (Manihot esculenta Crantz) Varieties with Special Emphasis on Leaf Biomass Quality for Livestock Feed","Gemechis L.","Accepted",""],
[740,"SARC","Livestock","Feeds","Observation Nursery of Fodder Oat (Avena sativa) for Highlands of Bale Zone","Gemechis L. and Wubshet T","Accepted",""],
[741,"SARC","Livestock","Api","Determination of the Optimum Sowing Date and Season of establishment for Yield, and Yield Components of Leonurus coardiata under Highland Conditions of Bale, Ethiopia","Temaro Gelgelu","Accepted",""],
[742,"SARC","Livestock","Api","Performance Evaluation of Ethiopian Mustard (Brassica carinata A. Braun) Varieties for Honeybee Forage development in the Highlands of Bale","Temaro Gelgelu","Accepted",""],
[743,"SARC","Livestock","Api","Ethno botanical study of Traditional Medicinal Plants Used to treat Honey Bee Diseases, Pests and Predators in Bale","Temaro Gelgelu","Accepted",""],
[744,"SARC","Livestock","Api","Assessment of Trigona stinglessbee production practices, distribution and indigenous knowledge in Bale zone, southeaster Oromia, Ethiopia","Wondimu Lelisa","Accepted",""],
[745,"SARC","Livestock","Feeds","Lablab intercropping with Maize on forage yield and Yield Components in low lands of Bale and East Bale zone","Wubshet Tesfaye.","Rejected",""],
[746,"SARC","Livestock","Feeds","Cowpea intercropping and time of planting with Maize on forage yield and Yield Components in mid land and low lands of Bale and East Bale zone","Wubshet Tesfaye.","Rejected",""],
[747,"SARC","Livestock","Feeds","Evaluation of Pulse crops by-products potential and Nutritional Value in Highlands of Bale Zone","Wubshet Tesfaye.","Rejected",""],
[748,"SARC","Livestock","Feeds","Evaluation of Different Crown Rust fungicides for grain yield and yield components fodder Oat Varieties","Wubshet Tesfaye.","Rejected",""],
[749,"SARC","Livestock","Feeds","Common Vetch (Vicia sativa) Varieties Adaptation Trial in Midlands of Bale and East Bale Zone","Wubshet Tesfaye.","Rejected",""],
[750,"SARC","Livestock","Feeds","Evaluation of Biomass Yield and Growth Performance of Intercropping Oats (Avena sativa L.) with Alfalfa (Medicago sativa) in the Bale Highlands, Ethiopia","Gemechis L. and Wubshet. T","Rejected",""],
[751,"SARC","Livestock","Api","Determination of the Optimum seeding rate and row spacing for Yield, and Yield Components of Leonurus coardiata under Highland Conditions of Bale, Ethiopia","Temaro Gelgelu","Rejected",""],
[752,"SARC","Livestock","Api","Integration of Improved beekeeping technologies to Area Closure through Beekeepers organizing in Goro Districts","Wondimu Lelisa","Rejected",""],
[753,"SARC","Livestock","Api","Evaluation of Oregano(Origanum Vulgare L) cultivars for honeybee forage development in Bale Zone, southeastern Oromia, Ethiopia","Wondimu Lelisa","Rejected",""],
[754,"SARC","Livestock","Api","Evaluation of physico-chemical quality of Royal jelly produced in different Agro-ecology of Bale Zone, Southwestern Oromia.","Wondimu Lelisa","Rejected",""],
[755,"SARC","Livestock","Api","Assessment of the Existence and Distribution of the Apis mellifera scutellata Honey Bee Race in the Lowland Areas of Bale, Ethiopia.","Habtamu D","Rejected",""],
[756,"SARC","Livestock","Api","Effect of Seasonal Honey Harvesting on the Honeybee Colony Performance and honey production in Bale Zone.","Habtamu D","Rejected",""],
[757,"YPDARC","Livestock","Meat","On-Station Performance Evaluation of Different Blood Levels of Boer-Borana Crossbred Goats at Yabello Pastoral and Dryland Agriculture Research Center (YPDARC), Southern Ethiopia","Anaf O. and Feyisa L","Accepted with modification",""],
[758,"YPDARC","Livestock","Feeds","Adaption of Early-Released Lablab Variety in Borana Zone, Southern Ethiopia","Asfaw Ejo","Accepted",""],
[759,"YPDARC","Livestock","Feeds","Effect of Controlling Techniques on Invasive Shrub Species (Lantana Camara) in Borana Rangeland, Southern Ethiopia","Asfaw Ejo","Accepted",""],
[760,"YPDARC","Livestock","Feeds","Distribution, Impact and Controlling Methods of Parthenium hysterophorus in Borana Rangeland, Southern Ethiopia","Asfaw Ejo","Accepted",""],
[761,"YPDARC","Livestock","Feeds","Improving Soil Quality and Restoring Degraded Rangeland Areas through Using Encroached Bush Biochar in Borana Zone","Jaldesa Doyo","Accepted",""],
[762,"YPDARC","Livestock","Meat","Prevalence and controlling method of camel trypanosomosis and its vectors in Borana pastoral areas, southern Ethiopia","Bantayehu Muluneh","Accepted",""],
[763,"YPDARC","Livestock","Meat","Participatory Epidemiological Study of Contagious Ecthyma (orf) of Small Ruminants, In Borana Zone, Southern Ethiopia","Bantayehu Muluneh","Accepted",""],
[764,"YPDARC","Livestock","Meat","Effect of improved forage and Concentrate Supplementation on Growth Performance, Carcass quality and Feed Utilization of yearling male goats feed brachiaria grass as basal diet","Sisay Kumsa","Accepted",""],
[765,"YPDARC","Livestock","Meat","Effect Of Cross-Border Livestock Migration On Disease Prevalence In Kenya And Ethiopia Border","Dr. Dereje Teshome","Accepted",""],
[766,"YPDARC","Livestock","Meat","Study On Major Reproductive Problems Of Cattle And Shoats In Pastoral And Agro-Pastoral Communities Of Borana Zone, Southern Oromia, Ethiopia","Dereje Teshome, Adem Kumbi, Bantayehu Muluney","Accepted",""],
[767,"YPDARC","Livestock","Feeds","Nursery Observation of Cenchrus ciliaris L. in Borana Zone","Asfaw Ejo","Accepted",""],
[768,"YPDARC","Livestock","Meat","Evaluation of Creep Feeding on Pre-Weaning Survival, Growth, and Early Puberty age in Borana Kids, Southern Oromia","Feyisa Lemessa","Conditionally Accepted",""],
[769,"YPDARC","Livestock","Feeds","Nursery Observation of Cajana cajanus in Borana Zone","Asfaw Ejo","Rejected",""],
[770,"YPDARC","Livestock","Feeds","Assessment of Rangeland improvement Interventions and Management in Borena Lowlands: Case Studies on Sustainable Practices for Societal and Ecosystem Betterment","Jaldesa Doyo","Rejected",""],
[771,"YPDARC","Livestock","Feeds","Asssment of dairy cattle feed resource, feeding practices and copping strategies to feed shortage under changing climate in Borena Zone, southern Ethiopia (Transferred from yabello Dairy team CNs)","Birhanu Bekele","Rejected",""],
[772,"YPDARC","Livestock","Meat","A study on prevalence of Bovine Pasteurellosis: Isolation and Identification of Pasteurellae in Borana zone, southern Ethiopia","Bantayehu Muluneh","Rejected",""],
[773,"YPDARC","Livestock","Meat","Women's Empowerment through Women-Centered Goat Fattening under Pastoral Management in Selected Districts of Borana Zone, Southern Ethiopia","Anaf O","Rejected",""],
[774,"YPDARC","Livestock","Meat","Assessment Of Major Reproductive Problems Of Camel (Camelus Dromedarius) In Pastoral And Agro-Pastoral Community Of Borana Zone, Southern Oromia, Ethiopia","Dereje Teshome","Rejected",""],
[775,"YPDARC","Livestock","Meat","Disease Resistance And Survival Evaluation Of Boer Goats At On-Station, Borana, Southern Oromia, Ethiopia","Dereje Teshome","Rejected",""],
[776,"YPDARC","Livestock","Meat","Survey On Neglected Equine Health In Pastoral Areas Of Borana, Southern Oromia Ethiopia","Dereje Teshome","Rejected",""],
[777,"YPDARC","Livestock","Feeds","Evaluation the Performance of Spineless Cactus Varieties with Local in Borana Zone, Southern Ethiopia","Asfaw Ejo","Rejected",""],
[778,"YPDARC","Livestock","Meat","Optimization of Short-Term Agro-Industrial By-Product Supplementation for Rapid Off-Take Fattening of Young Borana Bulls under on-station Management condition, Borana Zone","Feyisa Lemessa","Rejected",""],
[779,"YPDARC","Livestock","Meat","Efficacy/t of Strategic Deworming and Local Mineral Block Supplementation on Milk Yield and Calf Growth in Pastoral Herds of the Borana Zone","Feyisa Lemessa","Rejected",""],
[780,"YPDARC","Livestock","Api","Performance Evaluation of Sunflower, Faba bean and Lucerne in Borana zone, southern Oromia","Gayo Ginbe","Accepted with modification",""],
[781,"YPDARC","Livestock","Api","Comparative Performance Evaluation, Behavioural Characterization, and Scientific Validation of Indigenous Honeybee Ecotypes (Apis mellifera) in Borana Zone, Southern Ethiopia","Olyad Daniel","Accepted with modification",""],
[782,"YPDARC","Livestock","Api","Optimum sugar syrup feeding intervals for Honeybees (Apis mellifera) during the dearth period in Borana zone, southern Ethiopia","Gayo Ginbe","Accepted with modification",""],
[783,"YPDARC","Livestock","Api","Assessment of Beeswax Production, Utilization, Processing and Marketing Practices among Beekeepers in Borana and West Guji Zone","Olyad Daniel","Accepted",""],
[784,"YPDARC","Livestock","Api","Evaluating the Agronomic Performance, Drought-Escape Potential, and Dual-Purpose Value of Buckwheat (Fagopyrum esculentum and Fagopyrum tataricum) as Honeybee Forage and Human Food Crops during the Short Rainy Season in Borana and West Guji Zones","Olyad Daniel","Rejected",""],
[785,"YPDARC","Livestock","Api","Current conditions of honeybee colony population and production status in Borana zone southern Oromia, Ethiopia","Gayo Ginbe","Rejected",""],
[786,"YPDARC","Livestock","Dairy","Conservation and Genetic Improvement of the Qorti Subtype of Borana Cattle through a Community Based Breeding Program in Borana Zone","Birhanu B., Anaf O. and Dr. Adem K","Accepted with modification",""],
[787,"YPDARC","Livestock","Dairy","Assessment of Major Pathogens, Their Antimicrobial Resistance, and Community Safety Perceptions in raw and fermented Camel Milk","Birhanu Bekele","Accepted with modification",""],
[788,"YPDARC","Livestock","Dairy","Effects of Graded Replacement of Wheat Bran with Maize Grain on Feed Intake, Milk Yield, Milk Composition and Economic Efficiency of Lactating Borana Cows at YPDARC, Southern Ethiopia","Birhanu Bekele","Accepted",""],
[789,"YPDARC","Livestock","Dairy","Adaptation and Evaluation of F1 Holstein-Friesian x Borana Crosses for Urban and Per-urban Milk Production in Borana Zone, Southern Ethiopia","Birhanu B","Rejected",""],
[790,"YPDARC","Livestock","Dairy","Prevalence of Mastitis in lactating Goats and Camel under pastoral management of Borana southern, Ethiopia","Dr. Adem Kumbe","Rejected",""],
[791,"YPDARC","Livestock","Dairy","The prevalence of camel gastro-intestinal parasites in the Borana zone, Oromia region","Dr. Adem Kumbe","Rejected",""],
[792,"YPDARC","Livestock","Dairy","Improving the Productivity of Indigenous Borana Cattle through Elite Bull Sharing Groups in Selected Districts of Borana Zone, Southern Ethiopia","Anaf O","Rejected",""],
[793,"Asela","SEAE","AE","Pre-Extension Demonstration and Evaluation of Updraft cook stove in selected districts of Arsi Zone","Getu R.","Accepted",""],
[794,"Asela","SEAE","AE","Pre-Extension Demonstration and Evaluation of Manually operated coffee bean Demucilager in selected districts of Guji and Bale zones","Getu R.","Accepted",""],
[795,"Asela","SEAE","AE","Pre-extension demonstration and evaluation of Conventional Furrow Irrigation and Selected Water Level on Onion at Dodota Irrigation Scheme of Arsi zone","Getu R.","Accepted",""],
[796,"Asela","SEAE","AE","Pre-extension demonstration and evaluation of selected deficit irrigation and nitrogen fertilizer rate on yield and water productivity of potato under conventional furrow irrigation in selected districts of Arsi zone","Aman N.","Accepted",""],
[797,"Asela","SEAE","AE","Pre-extension demonstration and evaluation of dual purpose Michu cooking stove in selected districts of Arsi zone","Aman N.","Accepted",""],
[798,"Asela","SEAE","SE","Adoption of Improved Biomass Stoves among Rural Households in Arsi and West Arsi Zones, Oromia, Ethiopia","Ibsa Dawid.","Accepted",""],
[799,"Asela","SEAE","SE","Determinants of Smallholder Farmers' Perceptions of Biochar-Based Fertilizer in Arsi, West Arsi, and East Shewa Zones, Oromia, Ethiopia","Ibsa Dawid.","Rejected",""],
[800,"Asela","SEAE","SE","Assessment of Smallholder Farmers' Perceptions and Willingness to Adopt Solar-Powered Irrigation Pumps in Arsi and West Arsi, and East Shewa Zones, Oromia, Ethiopia","Ibsa Dawid.","Accepted",""],
[801,"Asela","SEAE","SE","Effectiveness of Agricultural Extension Services delivery and challenges in Oromia Region","Ibsa Dawid.","Accepted",""],
[802,"Asela","SEAE","SE","Assessment of Beekeeping and Green Legacy Initiative integration in Oromia Region","Ibsa Dawid.","Accepted",""],
[803,"ATARC","SEAE","AE","Pre-Extension Demonstration and Evaluation of recommended Irrigation Level for Groundnut production in Dugda district, East Shewa Zone","Hikma Sultan and Tesfaye Gemechu","Accepted",""],
[804,"ATARC","SEAE","AE","Pre-Extension demonstration of Soil-Test-Based phosphorus critical Level and phosphorus Requirement Factor for Maize production in Negele Arsi District, West Arsi Zone, Oromia Region, Ethiopia","BultuKusa","Accepted",""],
[805,"ATARC","SEAE","AE","Pre-Extension Demonstration and Evaluation of Adapted Faba Bean (Vicia faba L.) Varieties in West Arsi Zone, Oromia, Ethiopia","Firalem Regassa","Accepted",""],
[806,"ATARC","SEAE","AE","Pre-extension demonstration and evaluation of combined application of vermi cmpost and in organic fertilizer for maize production at Adami Tulu Jiddo Kombolcha district East Shewa zone, Oromia, Ethiopia","Tesfaye Gemechu","Accepted",""],
[807,"ATARC","SEAE","AE","Pre-extension demonstration and evaluation of integrated application of vermi compost and in-organic fertilizer for bread wheat Production in Adami Tulu Jido Kombolcha District","Tesfaye Gemechu and Firalem Regasa","Accepted",""],
[808,"ATARC","SEAE","AE","Pre-scale up of Maize-Pigeon Pea (Cajanus cajan) Improved Fallow Agroforestry Practice in the Adami Tullu District","Firalem Regasa and Bonsa Fantale","Conditionally Accepted",""],
[809,"ATARC","SEAE","SE","Impact of modern bee hives income of Bee keeping households in East Shewa and West Arsi Zones, Oromia Region Ethiopia","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[810,"ATARC","SEAE","SE","Adoption of King Bird Wheat variety in East Shewa Zone, Oromia Region Ethiopia","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[811,"ATARC","SEAE","SE","Agricultural credit system for Urban SME in East Shewa Zone Oromia Region Ethiopia","Asfaw. N. and Beriso. B. and Yassin.E","Conditionally accepted",""],
[812,"ATARC","SEAE","SE","Analysis of economics efficiency of Beef fattening in urban Agriculture of East Shewa Zone Oromia Region Ethiopia","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[813,"ATARC","SEAE","SE","Assessment of Soil Fertility Management Practices in West Arsi and East Shewa zones, Oromia national regional state, Ethiopia.","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[814,"ATARC","SEAE","SE","Impact of Potato Technologies on smallholder farmers Income in West Arsi Zone, Oromia National Regional State.","Asfaw. N. and Beriso. B. and Yassin.E","Rejected",""],
[815,"ATARC","SEAE","SE","Assessment of Post-harvest Management Practices and Causes of Post-harvest loss of Major Grain Crops in East Shewa and West Arsi Zones, Oromia Region, Ethiopia","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[816,"ATARC","SEAE","SE","Adoption and Impact of Plastic Milk Churner on Smallholder Dairy Farmers Income in West Arsi zone, Oromia national regional state, Ethiopia.","Asfaw. N. and Beriso. B. and Yassin.E","Rejected",""],
[817,"ATARC","SEAE","SE","Assessment of on-farm tree planting demand and species preference in West Arsi and East Shewa zones of Oromia.","Asfaw. N. and Beriso. B. and Yassin.E","Rejected",""],
[818,"ATARC","SEAE","SE","Adoption and Impacts of Improved Tef technologies on smallholder farmers Income and Food security in East Shewa and West Arsi zones, Oromia.","Asfaw. N. and Beriso. B. and Yassin.E","Rejected",""],
[819,"ATARC","SEAE","SE","Assessment of Agro-chemicals Empty Containers Disposal effect on Ecosystem and Environment in East Shewa zone of zones, Oromia.","Asfaw. N. and Beriso. B. and Yassin.E","Rejected",""],
[820,"ATARC","SEAE","SE","Economic evaluation and demand analysis of Banana production in East Shewa and West Arsi zones, Oromia Region.","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[821,"ATARC","SEAE","SE","Impact of Haricot bean technologies on smallholder farmers income in East Shewa zone, Oromia national regional state, Ethiopia.","Asfaw. N. and Beriso. B. and Yassin.E","Rejected",""],
[822,"ATARC","SEAE","SE","Analyzing the contribution of Crop Diversification in Improving Income and Food Security of smallholder farmers in East Shewa zone, Oromia.","Asfaw. N. and Beriso. B. and Yassin.E","Rejected",""],
[823,"ATARC","SEAE","SE","Adoption and Impacts of Durum Wheat technologies on smallholder farmers Income and Food security in East Shewa zone, Oromia region.","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[824,"ATARC","SEAE","SE","Effectiveness of Agricultural Extension Services delivery and challenges in Oromia Region","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[825,"ATARC","SEAE","SE","Economic Efficiency of wheat Production Oromia Region, Ethiopia","Asfaw. N. and Beriso. B. and Yassin.E","Accepted",""],
[826,"ATO","SEAE","SE","Effect of Agricultural Input Utilization on Crop Productivity: Evidence from Zone-Level Data, Ethiopia, 2018-2026","Addisu Hailu","Accepted",""],
[827,"BEARC","SEAE","AE","Pre-extension Demonstration and Evaluation of PTO Operated BAERC Soybean Thresher in Selected Districts of East Wollega Zone, Ethiopia","Girma Ajama","Accepted",""],
[828,"BEARC","SEAE","AE","Pre-extension Demonstration and Evaluation of PTO Driven Faba Bean Thresher in West Shewa Zone of Oromia National Regional State, Ethiopia","Girma Ajama","Accepted",""],
[829,"BEARC","SEAE","AE","Pre-scaling up of Tractor operated teff thresher in Selected Districts of West Shewa Zone of Oromia Region, Ethiopia","Chala Emiru","Accepted",""],
[830,"BEARC","SEAE","AE","Pre-Extension Demonstration and Evaluation of Optimized Irrigation Water Application Levels and Nitrogen Fertilizer Rates at Taltale Irrigation Scheme in west Shewa zone","Chala Emiru","Accepted",""],
[831,"BEARC","SEAE","SE","Factors Influencing Farmers' Choice of Mechanization for Major Activities of Teff Production in West Showa Zone","Gemechisa Yadeta.","Rejected",""],
[832,"BEARC","SEAE","SE","Farmers' Willingness to Pay for Agricultural Extension Services in East Wollaga zone","Gemechisa Yadeta.","Accepted",""],
[833,"BEARC","SEAE","SE","Adoption and impacts of motor pump for irrigation in western Oromia, Ethiopia","Gemechisa Yadeta.","Rejected",""],
[834,"BEARC","SEAE","SE","Factors Affecting Smallholder Farmers' Tractor Hiring Decisions in Western Oromia, Ethiopia","Gemechisa Yadeta.","Conditionally accepted",""],
[835,"BEARC","SEAE","SE","Willingness to pay of small holder farmers for metal silo cereal storage technology in west Shewa zone, Oromia, Ethiopia","Dereje Tibebu","Rejected",""],
[836,"BEARC","SEAE","SE","Adoption of Poultry Technologies among Smallholder Farmers in West Shewa Zone, Oromia, Ethiopia","Dereje Tibebu","Accepted",""],
[837,"BEARC","SEAE","SE","Assessment of Agricultural mechanization Utilization on major crops in Oromia Region","Gemechisa Yadeta.","Accepted",""],
[838,"BARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Teff Technologies in Selected Districts of East Wollega and West Shewa Zones of western Oromia.","Dubiso Gacheno","Accepted",""],
[839,"BARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Sunflower Technologies in Selected Districts of East Wollega and West Shewa Zones of western Oromia.","Dubiso Gacheno","Accepted",""],
[840,"BARC","SEAE","AE","Participatory Variety Evaluation and Selection of improved coffee varieties in Wayu Tuqa district of Western Oromia","Effa Wolteji","Conditionally Accepted",""],
[841,"BARC","SEAE","AE","Pre-extension demonstration of improved potato technologies in selected districts of West Shewa, Horro Guduru and East Wollega Zones of Western Oromia","Effa Wolteji","Accepted",""],
[842,"BARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Improved Sorghum Technologies in Potential Production Areas of East Wallaga zone, Western Oromia","Berhanu Soboka, Dubiso Gacheno and Effa Wolteji","Accepted",""],
[843,"BARC","SEAE","AE","Pre-Extension Demonstration of Brachiaria Grass in Selected Districts of East Wollega Zone","Wakgari Keba and Berhanu Soboka","Accepted",""],
[844,"BARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Sesame Technologies in Selected Districts of East Wollega and Bunno Bedelle Zones.","Matiwos Kasahun","Conditionally Accepted",""],
[845,"BARC","SEAE","AE","Pre-extension demonstration and evaluation of improved small pod hot pepper technology in selected districts of East Wollega and West Shewa zones","Matiwos Kasahun","Rejected",""],
[846,"BARC","SEAE","AE","Pre-scaling-up of Finger millet technology in East Wollega and Bunno Bedelle Zones of Western Oromia.","Dubiso Gacheno","Conditionally Accepted",""],
[847,"BARC","SEAE","AE","Cluster-based pre-scaling up of improved Linseed Technologies in selected Districts of West Shewa and East Wollega Zones, Western Oromia","Berhanu Soboka","Conditionally Accepted",""],
[848,"BARC","SEAE","SE","Impact Evaluation of Adopted Improved Rice Variety: The Case of Chewaka District","Galmesa Abebe","Accepted",""],
[849,"BARC","SEAE","SE","Econometric Analysis of Factors Affecting Market Outlet Choice of Mango Fruit Producers in Western Oromia, Ethiopia","Tamiru. I","Accepted",""],
[850,"BARC","SEAE","SE","Analysis of Factors Affecting The Technical Efficiency of Coffee Producers In Western Oromia, Ethiopia","Tamiru. I","Accepted",""],
[851,"BARC","SEAE","SE","Evaluation of Public-Private Partnerships (PPPs) in Regional Seed Multiplication and Distribution in Western Oromia, Ethiopia.","Tamiru. I","Rejected",""],
[852,"BARC","SEAE","SE","Impact Assessment of Improved Sesame Varieties on Productivity, Profitability, and Livelihoods in Selected Districts of Western Oromia","Tamiru. I","Accepted",""],
[853,"BARC","SEAE","SE","Adoption and impact integrated Soil Fertility Management Practices on major crop productivity in Oromia Region, Ethiopia","Tamiru Ijara","Accepted",""],
[854,"BARC","SEAE","SE","Economic Efficiency of wheat Production Oromia Region, Ethiopia","Kifle Degafa","Accepted",""],
[855,"BARC","SEAE","SE","Assessment of Beekeeping and Green Legacy Initiative integration in Oromia Region","Galmesa Abebe","Accepted",""],
[856,"Fishery","SEAE","AE","Pre Extension Demonstration of Selected Fishery Technologies in fishery Potential district of East Bale Zone","Alemayehu K.","Accepted",""],
[857,"Fishery","SEAE","SE","Analysis of household fish Consumption patterns and consumer preferences in selected fishery potential districts of East Shoa Zone","Abdulhakim H","Accepted",""],
[858,"Bedele","SEAE","AE","Pre-Extension Demonstration and Evaluation of Improved Bread Wheat in Chora and Gechi Districts of Buno Bedele Zone","Suleiman Aman, Nuru Temam, Diriba Hordofa and Emebet Alemayehu","Accepted",""],
[859,"Bedele","SEAE","AE","Pre-Scaling up of Improved White-flashed Sweet Potato (Ipomoea batatas Lam) varieties in Dabo Hana, Bedele and Gechi Districts of Buno Bedele Zone.","Diriba Hordofa","Conditionally Accepted",""],
[860,"Bedele","SEAE","AE","Pre-scaling up of improved upland Rice technologies in lowland areas of Buno Bedele zone","Emebet Alemayehu","Conditionally Accepted",""],
[861,"Bedele","SEAE","AE","Pre-scaling up of improved lowland sorghum technologies in Buno Bedele and Ilu Ababor Zones","Emebet Alemayehu","Conditionally Accepted",""],
[862,"Bedele","SEAE","AE","Pre-scaling up of Soil Test Crop Response Based Calibrated N and P Fertilizer rate for Tef in Gechi District of Buno Bedele Zone, South western Ethiopia","Nuru Temam, Suleiman Aman, Diriba Hordofa and Emebet Alemeyehu","Conditionally Accepted",""],
[863,"Bedele","SEAE","SE","Adoption and impact integrated Soil Fertility Management Practices on major crop productivity in Oromia Region, Ethiopia","Nuru Temam","Accepted",""],
[864,"Bedele","SEAE","SE","Assessment of Beekeeping and Green Legacy Initiative integration in Oromia Region","Nuru Temam","Accepted",""],
[865,"Bore","SEAE","AE","Pre-extension demonstration and evaluation of sweet lupin technologies in Guji zone, Oromia Region, Ethiopia","Basha Kebede","Accepted",""],
[866,"Bore","SEAE","AE","Pre-extension demonstration and evaluation of brown type tef technologies in midlands of Guji zone, Oromia Region, Ethiopia","Basha Kebede","Accepted",""],
[867,"Bore","SEAE","AE","Pre Extension Demonstration and Evaluation of Improved Cowpea Varieties at Midland Districts of Guji Zone, Southern Oromia, Ethiopia","Dembi Korji","Accepted",""],
[868,"Bore","SEAE","AE","Pre Extension Demonstration and Evaluation of Improved Desi Type chick pea Varieties at Midland Districts of Guji Zone, Southern Oromia, Ethiopia","Dembi Korji","Accepted",""],
[869,"Bore","SEAE","AE","Pre Extension Demonstration and Evaluation of Improved Faba bean Variety at Highland Districts of Guji Zone, Southern Oromia, Ethiopia","Dembi Korji","Accepted",""],
[870,"Bore","SEAE","AE","Pre-extension demonstration and evaluation of Irish Potato technologies in the Highlands of Guji Zone, Oromia Region, Ethiopia","Girma Amare","Accepted",""],
[871,"Bore","SEAE","AE","Pre-scaling up of bread wheat technologies in highlands of Guji zone, Oromia Region, Ethiopia","Basha Kebede","Conditionally Accepted",""],
[872,"Bore","SEAE","AE","Pre-Scaling up of improved bread wheat (Triticum aestivum. L) technologies at Adola Rede District of Guji Zone, Southern Oromia, Ethiopia","Girma Amare","Accepted",""],
[873,"Bore","SEAE","AE","Pre-Scaling up of improved Common bean (Phaseolus vulgaris L.) technologies at Midland Districts of Guji Zone, Southern Oromia, Ethiopia","Girma Amare","Conditionally Accepted",""],
[874,"Bore","SEAE","AE","Pre Scaling Up of Improved Haricot Bean Variety at Midland Districts of Guji Zone, Southern Oromia, Ethiopia","Dembi Korji","Conditionally Accepted",""],
[875,"Bore","SEAE","SE","Analysis of Teff Value Chain in Guji Zone, Southern Oromia, Ethiopia","Tesfu Nega","Rejected",""],
[876,"Bore","SEAE","SE","Adoption of Modern Beehive Technology in Guji Zone, Southern Oromia Ethiopia","Tesfu Nega","Accepted",""],
[877,"Bore","SEAE","SE","Analysis of Sheep Value Chain in Guji Zone, Southern Oromia, Ethiopia","Tesfu Nega","Rejected",""],
[878,"Bore","SEAE","SE","Assessment of Smallholder Farmers' Soil Fertility Management Practices in Guji Zone, Southern Oromia, Ethiopia","Tesfu Nega","Accepted",""],
[879,"Bore","SEAE","SE","Adoption of livestock genetic improvement through artificial insemination on the income and livelihood of smallholder farmers in Guji and west Guji Zones, southern Oromia, Ethiopia","Tekle Bobo","Accepted",""],
[880,"Bore","SEAE","SE","Analysis of wheat production Efficiency in highland Parts of Guji Zone, Southern Oromia, Ethiopia","Tekle Bobo","Rejected",""],
[881,"Bore","SEAE","SE","Adoption and impact of honey production initiatives on the Livelihood of Smallholder Farmers in Guji, West Guji and East Borana Zones, Southern Oromia, Ethiopia","Tekle Bobo","Rejected",""],
[882,"Bore","SEAE","SE","Enset Value Chain Analysis in Guji and West Guji zones, southern Oromia, Ethiopia","Tekle Bobo","Accepted",""],
[883,"Bore","SEAE","SE","Assessment of Beekeeping and Green Legacy Initiative integration in Oromia Region","Tekle B and Tesfu N","Accepted",""],
[884,"Fedis","SEAE","AE","Pre-extension Demonstration and evaluation of improved Triticale technology in the selected District of East Hararghe zone, Oromia Ethiopia","Abdulaziz Teha.","Accepted",""],
[885,"Fedis","SEAE","AE","Pre-extension Demonstration and evaluation of Engine Operated Portable Hole Digger for Tree planting technology in the selected District of East Hararghe zone, Oromia Ethiopia","Abdulaziz Teha.","Accepted",""],
[886,"Fedis","SEAE","AE","Pre-extension demonstration and evaluation of improved pigeon pea technologies in Fadis district of East Hararghe zone, Oromia, Ethiopia","Oromia Megersa","Accepted",""],
[887,"Fedis","SEAE","AE","Pre-extension demonstration and evaluation of improved Panicum grass technologies in Kersa and Meta districts of East Hararghe zone, Oromia, Ethiopia","Oromia Megersa","Accepted",""],
[888,"Fedis","SEAE","AE","Pre- extension Demonstration and evaluation of Emmer wheat Technology in the selected District of Highland area of East Hararghe zone , Oromia , Ethiopia.","Mersha Belete","Accepted",""],
[889,"Fedis","SEAE","AE","Pre-Extension Demonstration and Evaluation of Red common bean technology in the selected Districts of East Hararghe zone, Oromiya, Ethiopia","Mersha Belete","Accepted",""],
[890,"Fedis","SEAE","AE","Pre-extension Demonstration and Evaluation of Improved Bread wheat Technologies in selected Highland Districts of East Hararghe Zone.","Bedasso Urgessa","Accepted",""],
[891,"Fedis","SEAE","SE","Impact of Income Diversification on the Smallholder farmers' household Food Security Status: The case of East Hararghe Zone, Oromia Region, Ethiopia","Solomon Ayele","Accepted",""],
[892,"Fedis","SEAE","SE","Impact Integrated Soil Fertility Management Technologies on the household welfare: The East Hararghe Zone, Oromia Region, Ethiopia","Solomon Ayele","Accepted",""],
[893,"Fedis","SEAE","SE","Assessment of fenugreek production and marketing system System in East Hararghe Zone, Oromia Regional State, Ethiopia.","Kena Boja","Rejected",""],
[894,"Fedis","SEAE","SE","Economic benefits and Conservation of medicinal plants in East Hararghe Zone, Oromia Regional State, Ethiopia","Kena Boja","Rejected",""],
[895,"Fedis","SEAE","SE","Assessment hot pepper Production and Marketing System in East Hararghe Zone, Oromia Regional State, Ethiopia.","Kena Boja","Rejected",""],
[896,"Fedis","SEAE","SE","Determinants of Major Spice Crops Production and Commercialization among smallholder farmers in East Hararghe Zone, Oromia Regional State, Ethiopia.","Kena Boja","Accepted",""],
[897,"Fedis","SEAE","SE","Assessment of Small-Scale Post-Harvest Machineries Utilization Status, Challenges and Future Prospects in East and West Hararghe Zone","Bayissa Tarecha and kena Boja","Accepted",""],
[898,"Fedis","SEAE","SE","Mitigation Pathway and Impacts of Recurrent Drought on Households' Multi-dimensional poverty in East and South East Oromia, Ethiopia","Jafer Mume Ahmed (PhD)","Rejected",""],
[899,"Fedis","SEAE","SE","Adaptation pathways, Distress Sale Intensity and Impacts of Drought on Livestock Producers' Welfare in Pastoral and Agro-pastoral area of East and south East Ethiopia","Jafer Mume Ahmed (PhD)","Rejected",""],
[900,"Fedis","SEAE","SE","Economic Efficiency of Wheat Production: A Comparative Analysis in Eastern Cluster of Oromia Region, Ethiopia","Kibret Ketema and Solomon Ayele","Accepted",""],
[901,"Fedis","SEAE","SE","Effectiveness of Agricultural Extension Services delivery and challenges in Oromia Region","Solomon Ayele","Accepted",""],
[902,"Fedis","SEAE","SE","Assessment of Beekeeping and Green Legacy Initiative integration in Oromia Region","Jafer Mume Ahmed (PhD)","Accepted",""],
[903,"Fitche","SEAE","AE","Pre-extension Demonstration and Evaluation of Adapted Tomato technologies Under Irrigation in North shewa zone of Oromia","Adanu Ebisa","Accepted",""],
[904,"Fitche","SEAE","AE","Pre-scaling up of improved Faba bean technologies on the highland of North Shewa Zone, Oromia","Adanu Ebisa","Conditionally Accepted",""],
[905,"Fitche","SEAE","AE","Pre-scaling up of improved Triticale (X-Triticosecale) technologies in North Shewa Zone Oromia, Ethiopia","Adanu Ebisa","Conditionally Accepted",""],
[906,"Fitche","SEAE","AE","Pre-scaling up of improved Field Pea Technologies on the Highland of North Shewa zone, Oromia","Adanu Ebisa","Conditionally Accepted",""],
[907,"Fitche","SEAE","SE","Assessments of food self-sufficiency among small holder farmers in north shewa zone Oromia region","Bedo Hora Kefeni","Rejected",""],
[908,"Fitche","SEAE","SE","Impact Analysis of Agricultural Extension Service Delivery on technology adoption, productivity, and livelihoods of small holder farmers in North Shewa Zone; oromia region","Bedo Hora Kefeni","Accepted",""],
[909,"Fitche","SEAE","SE","Determinants of Milk Commercialization among Smallholder Dairy Farmers in North Shewa Zone, Oromia","Bedo Hora Kefeni","Rejected",""],
[910,"Fitche","SEAE","SE","Adoption and impact integrated Soil Fertility Management Practices on major crop productivity in Oromia Region, Ethiopia","Bedo Hora Kefeni","Accepted",""],
[911,"Fitche","SEAE","SE","Economic Efficiency of wheat Production Oromia Region, Ethiopia","Bedo Hora Kefeni","Accepted",""],
[912,"HBRC","SEAE","AE","Pre-Scaling Up of Beekeeping Technology in urban areas of Ambo town, Oromia","Lalisa W","Accepted",""],
[913,"HBRC","SEAE","AE","Pre-extension demonstration of sweet basil ( Ocimum basilicum L.) and Lavandula angustifolia Mill. (Lavender) bee forage development in welmera district,Oromiya.","Bizunesh Dandena","Accepted",""],
[914,"HBRC","SEAE","SE","Assessment of Integrated Beekeeping and Green Legacy Initiative in Selected Zones of Oromia Region: Constraints and SWOT analysis","Shelema R .","Accepted",""],
[915,"HBRC","SEAE","SE","Contributions of Honey Initiative Production Approach to Utilization of Beekeeping Technologies: The Case selected zones of Oromia Region, Ethiopia","Shelema R .","Accepted",""],
[916,"Harosabu","SEAE","AE","Pre-Extension Demonstration and Evaluation of Improved Small Red Lima Bean (Phaseolus Lunatus L) Technology in Selected Districts of West And Kellem Wollega Zones, Oromia, Ethiopia","Hika Tasfa","Accepted",""],
[917,"Harosabu","SEAE","AE","Pre-Extension Demonstration and Evaluation of Vermicompost Technology for Finger Millet Production in West and Kellem Wollega Zones, Oromia, Ethiopia","Hika Tasfa","Rejected",""],
[918,"Harosabu","SEAE","AE","Pre-Extension Demonstration and Evaluation of Improved Inter- and Intra-Row Spacing Practices for Enhancing Yield and Yield Components of Field Pea (Pisum sativum L.) in Selected Districts of West and Kellem Wollega Zones, Oromia, Ethiopia","Hika Tasfa","Accepted",""],
[919,"Harosabu","SEAE","AE","Pre-Extension Demonstration and Evaluation of Verified Fungicides for the Management of Fusarium Head Blight Disease of Bread Wheat (Triticum aestivum L.) in West and Kellem Wollega Zones, Oromia, Ethiopia","Hika Tasfa","Accepted",""],
[920,"Harosabu","SEAE","AE","Pre-Extension Demonstration and Evaluation of Improved Medium Red Lima Bean (Phaseolus lunatus L) Technology in Selected Districts of West and Kellem Wollega Zones, Oromia, Ethiopia","Hika Tasfa","Accepted",""],
[921,"Harosabu","SEAE","AE","Pre Extension Demonstration and Evaluation of Improved Inter and Intra Row Spacing Practices for Enhancing Yield of Head Cabbage (Brassica oleracea var. capitata L.) in Selected Districts of West and Kellam Wollega zones","Dammeksa Umer","Accepted",""],
[922,"Harosabu","SEAE","AE","Pre-Extension Demonstration and Evaluation of Integrated Coffee Husk Biochar with Inorganic Fertilizers for Improved Chomo Grass (Brachiaria Humidicola) Production in West and Kellem Wollega Zones, Western Oromia","Dammeksa Umer and Yerosan Wekgari","Accepted",""],
[923,"Harosabu","SEAE","AE","Pre-Scaling up of Groundnut (Arachis Hypogaea L.) Technologies in Selected Districts of West and Kellem Wollega Zones Western Oromia, Ethiopia","Dammeksa Umer","Accepted",""],
[924,"Harosabu","SEAE","AE","Pre-Scaling up of Large Red Mottled Lima Bean (Phaseolus Lunatus L) Technologies in Selected Districts of West Wollega and Kellem Wollega Zones Western Oromia, Ethiopia","Dammeksa Umer","Accepted",""],
[925,"Harosabu","SEAE","AE","Pre scaling up of improved commercial head cabbage (Brassica oleraceae var. capitata)Technology in West Wollega and Kellem Wollega Zones.","BayisaTamiru","Accepted",""],
[926,"Harosabu","SEAE","SE","Adoption of improved finger millet varieties in Kellem Wollega and West Wollega Zones","DanoAlemu","Accepted",""],
[927,"Harosabu","SEAE","SE","Economic Analysis of Sorghum Production and Marketing for Rural Development: A Case Study from Kellem Wollega and West Wollega Zones, Oromia Region","DanoAlemu","Accepted",""],
[928,"Harosabu","SEAE","SE","Impact of Improved Common Bean Technology Adoption on Smallholder Farmers' Income and Productivity in West and Kellem Wollega Zones, Oromia Region","DanoAlemu","Accepted",""],
[929,"Harosabu","SEAE","SE","Determinants of Sesame Production and its marketing system in Kellem Wollega and West Wollega Zones, Oromia Region","DanoAlemu","Accepted",""],
[930,"Harosabu","SEAE","SE","Effectiveness of Agricultural Extension Services delivery and challenges in Oromia Region","DanoAlemu","Accepted",""],
[931,"Jima","SEAE","AE","Pre scaling up of engine operated Inset processing machine in Jimma and Buno Bedele zones of Oromia region, Ethiopia","Kumale Sadeso","Accepted",""],
[932,"Jima","SEAE","AE","Pre scaling up of engine operated animal feed chopper machine in Jimma and Buno Bedele zones of Oromia region, Ethiopia","Kumale Sadeso","Accepted",""],
[933,"Jima","SEAE","AE","Pre scaling up of BAERC hand operated fertilizer applicator in Jimma zone, Oromia region","Kumale Sadeso","Accepted",""],
[934,"Jima","SEAE","AE","Pre-extension Demonstration and Evaluation of Metal Pan for Injera Baking in Selected Districts of Jimma Zone","Kumale Sadeso","Rejected",""],
[935,"Jima","SEAE","AE","Pre-extension Demonstration and Evaluation of Integrated Coffee Pulping and Washing Machine Selected Districts of Jimma ,Bunno bedele and Ilubabor Zone","Kumale Sadeso","Accepted",""],
[936,"Jima","SEAE","AE","Pre-Extension Demonstration and Evaluation of engine-operated Engine Groundnut stripper South Western Oromia","Kumale Sadeso","Conditionally Accepted",""],
[937,"Jima","SEAE","SE","Assessment on Soybean Harvest and Post-harvest Handling Practices in Southwestern Oromia","Husen A/Gissa","Accepted",""],
[938,"Jima","SEAE","SE","Adoption of Improved Biomass Stove Technology in Southwest Oromia","Husen A/Gissa","Rejected",""],
[939,"Jima","SEAE","SE","Adoption of Modern Beehive in Southwestern Oromia","Husen A/Gissa","Accepted",""],
[940,"Jima","SEAE","SE","Effectiveness of Agricultural Extension Services delivery and challenges in Oromia Region","Husen A/Gissa","Accepted",""],
[941,"Jima","SEAE","SE","Economic Efficiency of wheat Production Oromia Region, Ethiopia","Husen A/Gissa","Accepted",""],
[942,"Mechara","SEAE","AE","Pre-extension Demonstration and Evaluation of Moringa Stenopetala Provenance in West Hararghe Zone","Gemechu Terefe","Accepted",""],
[943,"Mechara","SEAE","AE","Pre-extension demonstration and evaluation of Head cabbage Technologies in West Hararghe zone, Oromia, Ethiopia (accepted last year and absented to develop its proposal due to priority)","Adem Hirpo","Accepted",""],
[944,"Mechara","SEAE","AE","Pre-extension Demonstration and Evaluation of Soil Test Crop Response Based Recommended Phosphorus Fertilizer for Maize in Daro Lebu District of West Hararghe, Ethiopia","Gemechu Terefe","Accepted",""],
[945,"Mechara","SEAE","AE","Pre scaling up of Bread wheat technology in West Hararghe Zone, Oromia, Ethiopia","Gemechu Terefe","Conditionally Accepted",""],
[946,"Mechara","SEAE","AE","Pre-scaling up of Cow pea Technologies in West Hararghe Zone, Oromia, Ethiopia","Adem Hirpo","Accepted",""],
[947,"Mechara","SEAE","AE","Pre-Extension Demonstration and Evaluation of Cassava Production and Utilization Technologies in west Hararghe Zone, Ethiopia","Gemechu Terefe, Dereje Deresa, Megersa Daba","Rejected",""],
[948,"Mechara","SEAE","SE","Assessments of sweet potato production and marketing systems in West Hararghe Zone, Oromia Region","Birhanu Angasu","Accepted",""],
[949,"Mechara","SEAE","SE","Economic efficiency analysis of sorghum production in West Hararghe zone, Oromia Ethiopia","Birhanu Angasu","Rejected",""],
[950,"Mechara","SEAE","SE","Economic efficiency analysis of wheat production in West Hararghe Zone, Oromia Ethiopia","Birhanu Angasu","Accepted",""],
[951,"Mechara","SEAE","SE","Effectiveness of Agricultural Extension Services delivery and challenges in Oromia Region","Birhanu Angasu","Accepted",""],
[952,"Nekemte","SEAE","AE","Pre scaling up of soil test crop response based phosphorus recommendation for bread wheat (Triticum AestivumL.) production at Leka Dulecha district, western Oromia, Ethiopia.","Naferom Negesa.","Conditionally Accepted",""],
[953,"Nekemte","SEAE","AE","Pre Extension Demonstration of Phosphorous Requirement Map for Bread Wheat (Triticum aestivum L.) at Jima Arjo District, East Wollega Zone, Oromia, Ethiopia.","Naferom Negesa.","Rejected",""],
[954,"Nekemte","SEAE","AE","Pre Extension Demonstration of Soil Test Crop Response Based Phosphorous Recommendation for Maize (Zea mays L.) at Guto Gida District, East Wollega Zone, western Oromia","Naferom Negesa.","Rejected",""],
[955,"SARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Mung bean Technologies in Selected Districts of Bale Zone","Ayalew Sida","Accepted",""],
[956,"SARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Semi-hulled Barley in Selected Highland Districts of Bale Zone","Ayalew Sida","Accepted",""],
[957,"SARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Improved Field Pea Technologies in Potential Districts of Bale zone","Bayeta Gadissa","Accepted",""],
[958,"SARC","SEAE","AE","Pre-Extension Demonstration and Evaluation of Faba Been Technology in Selected Districts of Bale Zone","Ibrahim Abite.","Accepted",""],
[959,"SARC","SEAE","AE","Pre-Extension Demonstration and Evaluation of Improved Lentil Technologies in Bale and East Bale Zones","Toluma Dereje","Accepted",""],
[960,"SARC","SEAE","AE","Pre-extension Demonstration of Soil Test Crop Response Based Recommended Phosphorus Fertilizer for Bread Wheat production in Agarfa District of Bale zone","Bayeta Gadissa","Accepted",""],
[961,"SARC","SEAE","AE","Pre-extension Demonstration of Soil Test Crop Response Based Recommended Phosphorus Fertilizer for Food Barley production in Agarfa District of Bale Highland, Oromia, Southeastern Ethiopia","Toluma Dereje and Bayeta Gadissa","Accepted",""],
[962,"SARC","SEAE","AE","Pre-scaling up of Improved Fenugreek Technologies in Bale and East Bale Zones","Ayalew Sida","Conditionally Accepted",""],
[963,"SARC","SEAE","AE","Pre-scaling Up of Improved Chickpea variety in Potential district of Bale and East Bale Zone.","Ibrahim Abite","Conditionally Accepted",""],
[964,"SARC","SEAE","AE","Pre-Scaling Up of Improved Vetch Varieties in Highland Areas of Bale Zone","Toluma Dereje","Conditionally Accepted",""],
[965,"SARC","SEAE","SE","Adoption and impact integrated Soil Fertility Management Practices on major crop productivity in Oromia Region, Ethiopia","Boki Abebe","Accepted",""],
[966,"SARC","SEAE","SE","Economic Efficiency of wheat Production Oromia Region, Ethiopia","Boki Abebe","Accepted",""],
[967,"YPDARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Small Red Common Bean (Phaseolus vulgaris L.) Technology in Borana Zone, Southern Oromia, Ethiopia","Teshome Kassa","Accepted",""],
[968,"YPDARC","SEAE","AE","Pre-extension Demonstration and Evaluation of improved Potato (Solanum tuberosum L.) Technologies in West Guji zones, Ethiopia","Feyisa Urgesa","Rejected",""],
[969,"YPDARC","SEAE","AE","Pre-extension Demonstration improved Maize (Zea mays L.) Varieties in Mid-land Areas of West Guji Zone","Feyissa Desiso and Feyissa Urgessa","Accepted",""],
[970,"YPDARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Newly Released Small White Common Bean (Phaseolus vulgaris L.) Technologies in Borana and West Guji Zones, Southern Oromia, Ethiopia","Feyissa Desiso","Accepted",""],
[971,"YPDARC","SEAE","AE","Pre-extension Demonstration and Evaluation of Pre -emergence Herbicide on Yield and Yield Components of Maize (Zea mays L.) in Borana and West Guji Zone, Southern Oromia, Ethiopia","Feyissa Desiso and Teshome Kassa","Accepted",""],
[972,"YPDARC","SEAE","SE","Adoption Study of Melkassa-1 miaze variety among agro pastoral of Borana Zone, Ethiopia.","Belay Biru","Accepted",""],
[973,"YPDARC","SEAE","SE","Assessment of Sweet Potato Production, Marketing and Farmers' Crop Choice in West Guji Zone, Southern Ethiopia","Belay Biru","Accepted",""],
[974,"YPDARC","SEAE","SE","Assessment of Management, Utilization and Sustainability of Protected Watershed Areas in Borana Zone, Southern Ethiopia","Belay Biru","Rejected",""],
[975,"YPDARC","SEAE","SE","Effectiveness of Agricultural Extension Services delivery and challenges in Oromia Region","Belay Biru","Accepted",""]
]

with open("/tmp/part2_b.json", "w") as f:
    json.dump(data, f)
print("Part 2B written:", len(data))
