import json

# Records 1 to 230
data = [
[1,"ATARC","Crop","Cereals","Influence of Different Seeding Rate on the Yield and Yield Component of Food Barley in East Shewa Zone, Oromia","Selam H. & Temesgen D.","Accepted","add N as additional factor; design be factorial RCBD; locations be three"],
[2,"ATARC","Crop","Cereals","Bread Wheat Regional Variety Trial for Low Moisture Stress Areas (BWRVT-2027)","Temesgen D. & Selam H.","Accepted",""],
[3,"ATARC","Crop","Cereals","Bread Wheat Preliminary Yield Trial for Low Moisture Areas (BWPYT-2027)","Temesgen D. & Selam H.","Accepted",""],
[4,"ATARC","Crop","Cereals","Bread Wheat Observation Nursery for Low Moisture Stressed Areas (BWON-2027)","Temesgen D. & Selam H.","Accepted",""],
[5,"ATARC","Crop","Cereals","Durum Wheat Regional Variety Trial for Low Moisture Areas (DWRVT-2027)","Selam H. & Temesgen D.","Accepted",""],
[6,"ATARC","Crop","Cereals","Durum Wheat Preliminary Yield Trial for Low Moisture Areas (DWPYT-2027)","Selam H. & Temesgen D.","Accepted",""],
[7,"ATARC","Crop","Cereals","Durum Wheat Observation Nursery for Low Moisture Areas (DWON-2027)","Selam H. & Temesgen D.","Accepted",""],
[8,"ATARC","Crop","Cereals","Food Barley Regional Variety Trial for Low Moisture Areas (2027)","Temesgen D. & Selam H.","Accepted","Include proper standard check/s"],
[9,"ATARC","Crop","Cereals","Food Barley Preliminary Yield Trial for Low Moisture Areas (FBPYT-2027)","Selam H. & Temesgen D.","Accepted","Include proper standard check/s"],
[10,"ATARC","Crop","Cereals","Food Barley Observation Nursery for Low Moisture Areas (FBON-2027)","Selam H. & Temesgen D.","Accepted",""],
[11,"ATARC","Crop","Cereals","Tef Variety Verification for Low Moisture Areas (2027)","Temesgen D. & Selam H.","Accepted","Mention recent standard check; specify color"],
[12,"ATARC","Crop","Cereals","White seeded Tef Regional Variety Trial for Low Moisture Areas (2027)","Temesgen D. & Selam H.","Accepted","Mention recent standard check; specify color"],
[13,"ATARC","Crop","Cereals","White seeded Tef Preliminary Yield Trial (TPYT-2027)","Temesgen D. & Selam H.","Accepted",""],
[14,"ATARC","Crop","Cereals","White seeded Tef Preliminary Observation Nursery Trial (TPON-2027)","Selam H. & Temesgen D.","Accepted",""],
[15,"ATARC","Crop","Cereals","Brown seeded Tef Preliminary Observation Nursery Trial (TPON-2027)","Selam H. & Temesgen D.","Accepted",""],
[16,"ATARC","Crop","Pulses","Lentil (Lens culinaris Medik.) Preliminary Yield Trial","Ashenafi T. and Beshir H.","Accepted","Mention recent standard check"],
[17,"ATARC","Crop","Pulses","Lentil (Lens culinaris Medik.) Regional variety Trial","Ashenafi T. and Beshir H.","Accepted","Mention one best & erecent standard check"],
[18,"ATARC","Crop","Pulses","Dessi-type Chickpea (Cicer arietinum L.) Observation Nursery","Ashenafi T. and Beshir H.","Accepted","Mention the standard checks"],
[19,"ATARC","Crop","Pulses","Dessi-type Chickpea (Cicer arietinum L.) Preliminary Yield Trial","Beshir H. & Ashenafi T.","Accepted","Identify proper standard checks"],
[20,"ATARC","Crop","Pulses","Dessi-type Chickpea (Cicer arietinum L.) RVT","Ashenafi T. and Beshir H.","Accepted","Identify one proper standard check"],
[21,"ATARC","Crop","Pulses","Kabuli type Chickpea (Cicer arietinum L.) Observation Nursery","Ashenafi T. and Beshir H.","Accepted","Identify proper standard checks"],
[22,"ATARC","Crop","Pulses","Kabuli type Chickpea (Cicer arietinum L.) Preliminary Yield Trial","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[23,"ATARC","Crop","Pulses","Kabuli type Chickpea (Cicer arietinum L.) RVT","Ashenafi T. and Beshir H.","Accepted","Identify proper standard check"],
[24,"ATARC","Crop","Pulses","Soybean Observation Nursery","Ashenafi T. and Beshir H.","Accepted","Focus on early maturing genotypes"],
[25,"ATARC","Crop","Pulses","Early Set Soybean (Glycine Max L.) Preliminary Yield Trial","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[26,"ATARC","Crop","Pulses","Medium Set Soybean (Glycine max L.) Preliminary Yield Trial","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[27,"ATARC","Crop","Pulses","Early set Soybean (Glycine max L.) Regional variety Trial","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[28,"ATARC","Crop","Pulses","Medium Set Soybean (Glycine max L.) Regional variety Trial","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[29,"ATARC","Crop","Pulses","Speckled Common Bean (Phaseolus Vulgaris) Observation Nursery","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[30,"ATARC","Crop","Pulses","Mottled Common Bean (Phaseolus Vulgaris) Observation Nursery","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[31,"ATARC","Crop","Pulses","Large White Common Bean (Phaseolus Vulgaris) Observation Nursery","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[32,"ATARC","Crop","Pulses","Small white Common Bean (Phaseolus Vulgaris) Observation Nursery","Ashenafi T.","Accepted","Identify proper checks"],
[33,"ATARC","Crop","Pulses","Large Red Common Bean (Phaseolus Vulgaris) Observation Nursery","Ashenafi T.","Accepted","Identify proper checks"],
[34,"ATARC","Crop","Pulses","Small Red Common Bean (Phaseolus Vulgaris) Observation Nursery","Ashenafi T. and Beshir H.","Accepted","Identify proper checks"],
[35,"ATARC","Crop","Pulses","Mottled Common Bean (Phaseolus Vulgaris) Preliminary Yield Trial","Ashenafi T.","Accepted","Identify proper checks"],
[36,"ATARC","Crop","Pulses","Large White Common Bean (Phaseolus Vulgaris) Preliminary Yield Trial","Ashenafi T.","Accepted","Identify proper checks"],
[37,"ATARC","Crop","Pulses","Small White Common Bean (Phaseolus Vulgaris) Preliminary Yield Trial","Ashenafi T.","Accepted","Identify proper checks"],
[38,"ATARC","Crop","Pulses","Large Red Common Bean (Phaseolus Vulgaris) Preliminary Yield Trial","Ashenafi T.","Accepted","Identify proper checks"],
[39,"ATARC","Crop","Pulses","Small Red Common Bean (Phaseolus Vulgaris) Preliminary Yield Trial","Ashenafi T.","Accepted","Identify proper checks"],
[40,"ATARC","Crop","Pulses","Speckled Common Bean (Phaseolus Vulgaris) RVT","Ashenafi T.","Accepted","Identify proper checks; use only on standard check"],
[41,"ATARC","Crop","Pulses","Small White Common Bean (Phaseolus Vulgaris) RVT","Ashenafi T.","Accepted","Identify proper checks; use only on standard check, accross all RVTs; locations be three for RVTs"],
[42,"ATARC","Crop","Pulses","Mottled Common Bean (Phaseolus Vulgaris) RVT","Ashenafi T.","Accepted","Identify proper checks; use only on standard check, accross all RVTs; locations be three for RVTs"],
[43,"ATARC","Crop","Pulses","Adaptation Trial of Mung bean (Vigna radiata L.)","Ashenafi T.","Accepted","Changed to Observation Nursery (PON); include Sinana varieties as check"],
[44,"ATARC","Crop","Pulses","Adaptation Trial of Faba Bean in Ada'a and Lume District of East Shewa Oromia","Ashenafi T.","Accepted","Describe the varieites by names and source; include proper check."],
[45,"ATARC","Crop","Pulses","Adaptation Trial of Shiro - type Field Pea (Pisum sativum L.) varieites in Ada'aa and Lume districts, East Shewa Zone, Oromia, Ethiopia","Ashanfi T. and Beshir H.","Accepted","Describe the varieites by names and source; include proper check."],
[46,"ATARC","Crop","Pulses","Adaptation Trial of kik-type Field Pea (Pisum sativum L.) at Ada'a and Lume district East Shewa Zone, Oromia, Ethiopia","Ashanfi T. and Beshir H.","Accepted","Describe the varieites by names and source; include proper check."],
[47,"ATARC","Crop","Pulses","Adaptation Trial of Groundnut (Arachis hypogaea L.) Varieties East Shewa Zone, Oromia, Ethiopia","Ashenafi T. and Beshir H.","Rejected","Not a priority given that ther researchers are already overloaded."],
[48,"ATARC","Crop","Pulses","Performance Evaluation of Early Set Soybean (Glycine max L.) Using Irrigation at East Shewa Zone, Oromia Regional State, Ethiopia","Beshir H. & Ashenafi T.","Rejected","Not a priority given that ther researchers are already overloaded."],
[49,"ATARC","Crop","Pulses","Performance Evaluation of Sesame (Sesamum indicum L.) Using Irrigation at East Shewa Zone, Oromia Regional State, Ethiopia","Beshir H. & Ashenafi T.","Accepted","Describe varieites"],
[50,"BARC","Crop","Cereals","Influence of Integrated Organic and Inorganic fertilizer application rates on Grain Yield and yield-related traits of Bread wheat in the highland areas of Western Oromia","Hailu F.","Accepted",""],
[51,"BARC","Crop","Cereals","Effects of Green Manure and fertilizer rates on Soil Fertility and Productivity of Finger Millet (Eleusine coracana L. Gaertn.) in Western Ethiopia","Fufa A.","Rejected","One season is not enough for the activity - grwoing green manure and then the fingermillet; result may not be actuall applicable at farmers level"],
[52,"BARC","Crop","Cereals","Effects of Sowing Time on Yield and Yield Components of Upland Rice in Western Ethiopia","Fufa A.","Accepted","specify the sowing date; check the intervals (number of days between two swoings)"],
[53,"BARC","Crop","Cereals","Effects of Sowing Time on Yield and Yield Components of Upland Rice in Western Ethiopia","Fufa A. et al","Accepted","Check for suitablitity of sorghum varieties; and matuirty class of soybean (medium is better); check the ratios, sorghum be fixed and soybean varry; make clear the temporal and spiatial arrangments."],
[54,"BARC","Crop","Cereals","Response of improved food barley to NP fertilizer rates in western parts of Ethiopia","Fufa A.","Accepted","Delete the general objective; rewrite the specific objectives, condensing to single objective"],
[55,"BARC","Crop","Cereals","Sorghum Preliminary Yield Trial (Medium Set)","Meseret T.","Accepted",""],
[56,"BARC","Crop","Cereals","Sorghum Preliminary Yield Trial (Medium Set)","Meseret T.","Accepted",""],
[57,"BARC","Crop","Cereals","Evaluation of F3 Sorghum Segreagant generations","Chemeda B.","Accepted",""],
[58,"BARC","Crop","Cereals","Sorghum Preliminary Yield Trial (SPYT - 2027)","Chemeda B.","Accepted",""],
[59,"BARC","Crop","Cereals","White Seeded Finger millet Regional Variety Trial","Chemeda B.","Accepted",""],
[60,"BARC","Crop","Cereals","Brown Seeded Finger millet Regional Variety Trial","Chemeda B.","Accepted",""],
[61,"BARC","Crop","Cereals","Black Seeded Finger millet Regional Variety Trial","Chemeda B.","Accepted",""],
[62,"BARC","Crop","Cereals","Bread Wheat Observation Nurseryunder Irrigation condition","Geleta G.","Accepted",""],
[63,"BARC","Crop","Cereals","Bread Wheat Observation of Nursery under rain-fed","Geleta G.","Accepted",""],
[64,"BARC","Crop","Cereals","Durum Wheat Observation Nursery","Geleta G.","Accepted",""],
[65,"BARC","Crop","Cereals","Evaluation of Bread wheat F1 Segregating generation","Geleta G.","Accepted",""],
[66,"BARC","Crop","Cereals","Evaluation of Bread wheat F2 Segregating generation","Geleta G.","Accepted",""],
[67,"BARC","Crop","Cereals","Bread wheat Regional variety Trail -Irrigated (IBWRVT-2027)","Geleta G.","Accepted",""],
[68,"BARC","Crop","Cereals","Bread wheat regional Variety Trail (BWRVT-2027)","Geleta G.","Accepted",""],
[69,"BARC","Crop","Cereals","Durum Wheat Regional Variety Trial","Geleta G.","Accepted",""],
[70,"BARC","Crop","Cereals","Bread wheat National Performance Test- 2027","Geleta G.","Accepted",""],
[71,"BARC","Crop","Cereals","Malt Barley Regional Variety Trial","Meseret T.","Accepted",""],
[72,"BARC","Crop","Cereals","Food Barley Regional Variety Trial","Meseret T.","Accepted",""],
[73,"BARC","Crop","Cereals","Semi- hulled Barley Observation Nursery","Meseret T.","Accepted",""],
[74,"BARC","Crop","Cereals","Food Barley Observation Nursery","Meseret T.","Accepted",""],
[75,"BARC","Crop","Cereals","Rice Regional Variety Trial","Gudeta B.","Accepted",""],
[76,"BARC","Crop","Cereals","Evaluation of F3 Rice Segregating Generations","Gudeta B.","Accepted",""],
[77,"BARC","Crop","Cereals","Upland Rice Nursery Observation Trial.","Gudeta B.","Accepted",""],
[78,"BARC","Crop","Cereals","Tef Observation Nursery (Brown-seeded)","Gudeta B.","Accepted",""],
[79,"BARC","Crop","Cereals","Tef Observation Nursery (White-seeded)","Gudeta B.","Accepted",""],
[80,"BARC","Crop","Cereals","Tef Preliminary Yield Trial (white-seeded)","Gudeta B.","Accepted",""],
[81,"BARC","Crop","Cereals","Tef Preliminary Yield Trial (Brown-seeded)","Gudeta B.","Accepted",""],
[82,"BARC","Crop","Cereals","Tef Regional Variety Trial (White-seeded)","Gudeta B.","Accepted",""],
[83,"BARC","Crop","Cereals","Tef Regional Variety Trial (Brown-seeded)","Gudeta B.","Accepted",""],
[84,"BARC","Crop","Pulses","Agronomic and Economic Evaluation of Low-Cost Input Bundling System for Sustainable Soybean Production in Western Oromia","Alemayehu D","Accepted",""],
[85,"BARC","Crop","Pulses","Machine Learning-Based Prediction of Soybean Yield under Different Phosphorus and Bradyrhizobium Management Systems","Alemayehu D","Accepted",""],
[86,"BARC","Crop","Pulses","Evaluation of Staking Methods for High-Yield Climbing Bean (Phaseolus vulgaris L.) Production in Western Oromia, Ethiopia","Alemayehu D","Accepted","Merge the two objectives into one"],
[87,"BARC","Crop","Pulses","The Influence of Inter- and Intra-Row Spacing on Growth, Yield Components, and Grain Yield of Climbing Bean (Phaseolus vulgaris L.) in Western Oromia","Alemayehu D","Accepted","Merge the two objectives into one"],
[88,"BARC","Crop","Pulses","Synergizing Tillage and Legume Service Crops as Regenerative Practices to Enhance Maize Yield and System Resilience to Biotic and Abiotic Stresses","Alemayehu D","Accepted",""],
[89,"BARC","Crop","Pulses","Adaptability and Yield Performance Evaluation of Biofortified Common Bean (Phaseolus vulgaris L.) Varieties in Oromia, Ethiopia","Alemayehu D & Megersa D.","Accepted","check varieties; complete the list of locations (Bako, Bedlle, Fadis, Machara, Adami Tulu)"],
[90,"BARC","Crop","Pulses","Effect of planting date on Growth, Yield and Yield Components of Sunflower (Helianthus annus) at mid land area of Western Oromia","Teshome G, Alemayehu D & Feyera T.","Accepted","Focus on singe factor i.e planting date study"],
[91,"BARC","Crop","Pulses","Effects of Planting Date on Growth, Yield and Yield Components of Sunflower (Helianthus annuus L.) in the Highland Areas of Western Oromia, Ethiopia","Teshome G, Alemayehu D & Feyera T.","Accepted",""],
[92,"BARC","Crop","Pulses","Effect of P2O5 Fertilizer application rates on Yield and Yield Component of Pigeon pea (Cajanus cajan) Varieties In Western Oromia","Teshome G.","Accepted",""],
[93,"BARC","Crop","Pulses","Sesame Variety Verification Trial","Feyera T.","Accepted","Moved to FRSP"],
[94,"BARC","Crop","Pulses","Sesame Regional Variety Trial (RVT-I)","Feyera T.","Accepted",""],
[95,"BARC","Crop","Pulses","Sesame Observation Nursery","Feyera T.","Accepted","Be secure the germplasm"],
[96,"BARC","Crop","Pulses","Sunflower Variety Verification Trial","Feyera T.","Accepted","Moved to FRSP"],
[97,"BARC","Crop","Pulses","Fababean Variety Verification Tria","Feyera T.","Accepted","Include proper/recent standard check/s"],
[98,"BARC","Crop","Pulses","Fababean Regional Variety Trial","Feyera T.","Accepted","Use th recommended seeding rate"],
[99,"BARC","Crop","Pulses","Faba bean Preliminary Yield Trial","Feyera T.","Accepted","Use th recommended seeding rate"],
[100,"BARC","Crop","Pulses","Faba bean Observation Nursery","Feyera T.","Accepted","Use th recommended seeding rate and also be secure the germplasm"],
[101,"BARC","Crop","Pulses","Field Pea Variety Verification Trial (Shiro type)","Feyera T.","Accepted","Include proper/recent standard check/s"],
[102,"BARC","Crop","Pulses","Field pea observation nursery trial (Kiki Type)","Feyera T.","Accepted","Be secure the germplasm"],
[103,"BARC","Crop","Pulses","Field pea observation nursery trial (Shiro Type)","Feyera T.","Accepted","Be secure the germplasm"],
[104,"BARC","Crop","Pulses","Groundnut Observation Nursery","Feyera T.","Accepted","Be secure the germplasm"],
[105,"BARC","Crop","Pulses","Chickpea Observation Nursery","Feyera T.","Accepted","Be secure the germplasm and also specify the set type or go for two types"],
[106,"BARC","Crop","Pulses","Medium Set Soybean Variety Verification","Adane A.","Accepted","Moved to FRSP"],
[107,"BARC","Crop","Pulses","Late Set Soybean Variety Verification","Adane A.","Accepted","Moved to FRSP"],
[108,"BARC","Crop","Pulses","Medium Set Soybean Preliminary Yield Trial","Adane A.","Accepted",""],
[109,"BARC","Crop","Pulses","Early-to-medium-maturing Soybean Observation Nursery","Adane A.","Accepted","Be secure the germplasm"],
[110,"BARC","Crop","Pulses","Medium to Late-Maturing Soybean Observation Nursery","Adane A.","Accepted","Be secure the germplasm"],
[111,"BARC","Crop","Pulses","Small Red Common Bean Regional Variety Trial","Adane A.","Accepted",""],
[112,"BARC","Crop","Pulses","Large Red Common Bean Regional Variety Trial","Adane A.","Accepted",""],
[113,"BARC","Crop","Pulses","Small Red Common Bean Preliminary Yield Trial","Adane A.","Accepted",""],
[114,"BARC","Crop","Pulses","Small White Common bean Preliminary Yield Trial","Adane A.","Accepted",""],
[115,"BARC","Crop","Pulses","Small Red Common Bean Observation Nursery","Adane A.","Accepted","Be secure the germplasm"],
[116,"BARC","Crop","Pulses","Medium Red Common Bean Observation Nursery","Adane A.","Accepted","Be secure the germplasm"],
[117,"BARC","Crop","Pulses","Speckled Bean Observation Nursery","Adane A.","Accepted","Be secure the germplasm (large Speckled common bean)"],
[118,"BARC","Crop","Pulses","Red Mottled Bean Observation Nursery","Adane A.","Accepted","Be secure the germplasm"],
[119,"BARC","Crop","Pulses","Mung Bean Variety Verification Trial","Adane A.","Accepted",""],
[120,"BARC","Crop","Pulses","Mung Bean Observation Nursery","Adane A.","Accepted","Be secure the germplasm"],
[121,"BARC","Crop","Pulses","Linseed Observation Nursery","Adane A.","Accepted","Be secure the germplasm"],
[122,"BARC","Crop","Pulses","Lentil Adaptation Trial","Adane A.","Accepted","Be secure the materials (Varities)"],
[123,"BARC","Crop","Horticulture","Evaluation of planting techniques and varieties for increasing root yield of sweet potato (Ipomoea batatas (L.) Lam.) production in Western Oromia, Ethiopia","Mamo M.","Accepted","Strong justification is required. Also Specify the differences b/n the varieties (Growth habit/characteristics), Include farmer practice as one treatment and also add one more location (Chewaka)"],
[124,"BARC","Crop","Horticulture","Effects of vermi compost and inorganic fertilizers on Growth, Yield Components and Yield of Hot Pepper at Western Oromia","Chala G.","Accepted","Strong justification is required, Specify the base of vermi-compost rates and check the rates for the inorganic fertilizers"],
[125,"BARC","Crop","Horticulture","Evaluation of F5 Progenies of Large Pod Hot Pepper for Yield and Related Traits","Tilahun W","Accepted",""],
[126,"BARC","Crop","Horticulture","Evaluation of F3 Progenies of Small Pod Hot Pepper for Yield and Related Traits","Tilahun W","Accepted",""],
[127,"BARC","Crop","Horticulture","Chilli pepper observation nursery 2027","Eshetu M.","Accepted","Be secure the germplasm"],
[128,"BARC","Crop","Horticulture","Potato Variety Verification Trial 2027","Eshetu M.","Accepted",""],
[129,"BARC","Crop","Horticulture","Potato Preliminary Yield Trial 2027","Eshetu M.","Accepted",""],
[130,"BARC","Crop","Horticulture","Fenugreek Preliminary Yield Trial 2027","Eshetu M.","Accepted",""],
[131,"BARC","Crop","Horticulture","Okra (Abelmoschus esculentus) Observation Nursery","Sisay G.","Rejected","Not a priority crop"],
[132,"BARC","Crop","Horticulture","Adaptation and Performance Evaluation of Improved Shallot (Allium cepa var. aggregatum) Varieties in the Mid-Altitude Agroecology of Bako, Western Oromia.","Sisay G.","Accepted","Use bulb propagated materials. Also add one more location"],
[133,"Bedele","Crop","Cereals","Effect of Nitrogen and Phosphorus Fertilizer Rates on Yield and Yield Components of Triticale in Buno Bedele, South West Oromia, Ethiopia","Adisu Y.","Accepted","use the recommended variety in the study area (if no variety adapted in the area first go for adatation traial)"],
[134,"Bedele","Crop","Cereals","Effect of Nitrogen and Phosphorus Fertilizer Rates on Yield and Yield Components of Durum wheat in Buno Bedele, South West Oromia, Ethiopia","Adisu Y.","Accepted","use the adapted/recommended variety for the study area. Include Quality parameter data"],
[135,"Bedele","Crop","Cereals","Effect of Seed Rate and Row Spacing on Yield and Yield Components Upland Rice (Oryza sativa L.) in Buno Bedele Zone Bedele, South West Oromia, Ethiopia","Adisu Y.","Accepted","Modified to Effect of seeding rates and N fertilizer application rates on yield and Yield Components Upland Ric. Revise the treatments based on the above given suggestions"],
[136,"Bedele","Crop","Pulses","Effects of nitrogen and phosphorus on Yield and yield components on Sesame (Sesamum indicum L.) at Buno Bedele","Garoma F.","Accepted","Specify the variety used and also include quality parameter data"],
[137,"Bedele","Crop","Horticulture","Effects of NP Fertilizer and Seeding Rates on Yield and Yield Components of Fenugreek (Trigonella foenum-graecum L.) in Buno Bedele Zone, Southwestern Ethiopia","Alemayehu A.","Accepted","Revise the treatments per given suggestions"],
[138,"Bedele","Crop","Horticulture","Integrated Effects of NP and Vermicompost Rates on Hot Pepper (Capsicum annuum L.) in Buno Bedele Zone, Southwestern Ethiopia","Alemayehu A.","Accepted","Calculate the rate of Vermi-compost based on the nutrient content of the Vermi-compost. Include soil sample and economic analysis"],
[139,"Bedele","Crop","Horticulture","Integrated Effects of NP and Vermicompost Rates on Tuber Yield and Tuber Yield Components of Potato (Solanum tuberosum L.) in Buno Bedele Zone, Southwestern Ethiopia","Alemayehu A.","Accepted","Calculate the rate of Vermi-compost based on the nutrient content of the Vermi-compost. Include soil sample and economic analysis"],
[140,"Bedele","Crop","Horticulture","Effects of Planting Time and NP Fertilizer Rates on Yield and Yield Components of Garlic (Allium sativum L.) Varieties in Buno Bedele Zone, Southwestern Ethiopia","Alemayehu A.","Rejected","Not justifiable; better to manage the disease using other methods; planting time not priority"],
[141,"Bedele","Crop","Cereals","White Seeded Tef (Eragrostis tef) Regional Variety Trial","Gebeyehu Ch.","Accepted",""],
[142,"Bedele","Crop","Cereals","Finger Millet (Eleusine coracana (L.) Gaertn) Preliminary Yield Trial (FMPYT-2027) in Buno Bedele Zone","Gebeyehu Ch.","Accepted",""],
[143,"Bedele","Crop","Cereals","Upland Rice (Oryza sativa L.) Preliminary Yield Trial (URPYT-2027) in Buno Bedele Zone","Gebeyehu Ch. & Gemechu D","Accepted",""],
[144,"Bedele","Crop","Cereals","Bread Wheat (Triticum aestivum L.) Preliminary Yield Trial (BWPYT-2027) in Buno Bedele Zone","Gebeyehu Ch. & Gemechu D","Accepted",""],
[145,"Bedele","Crop","Cereals","Brown Seeded Tef Observation Nursery","Gebeyehu Ch. & Gemechu D","Accepted","Genotype source should be Bishoftu Agricultural Research Center"],
[146,"Bedele","Crop","Cereals","White Seeded Finger Millet (Eleusine coracana) Observation Nursery","Gebeyehu Ch. & Gemechu D","Accepted","Try to access germplasm from Melkasa Agricultural Research Center; try to get germplasm for all seed colors or secure together and separate late at PYT stage"],
[147,"Bedele","Crop","Pulses","Small White Common Bean (Phaseolus Vulgaris L.) Regional Variety Trial (RVT)","Garoma F.","Accepted",""],
[148,"Bedele","Crop","Pulses","Sesame (Sesamum Indicum L.) Regional Variety Trial (RVT)","Garoma F.","Accepted","Use recent varieties for standard check from Bako Agri Research Center"],
[149,"Bedele","Crop","Pulses","Small Red Common bean (Phaseolus vulgaris L.) Observation Nursery","Garoma F.","Accepted","Include standard checks"],
[150,"Bedele","Crop","Pulses","Adaptation Trial of Newly Released Faba Bean (Vicia faba L.) Varieties on Buno Bedele zone","Garoma F.","Rejected","Not priority; not the right ecology for faba bean"],
[151,"Bedele","Crop","Horticulture","Performance Evaluation of Improved Hybrid Tomato Varieties under Supplemental Irrigation in Buno Bedele Zone","Alemayehu A.","Rejected","the check suggested is OPV; on top of that seed may not be available"],
[152,"Bedele","Crop","Horticulture","Adaptation Trial of Improved Hybrid Onion (Allium cepa L.) Varieties under the Agro-Ecological Conditions of Buno Bedele Zone, Southwestern Ethiopia","Alemayehu A.","Accepted",""],
[153,"Bedele","Crop","Horticulture","Adaptation Trial of Improved Cacao (Theobroma cacao L.) Varieties in Buno Bedele and Ilu Aba Bor Zones, Southwestern Ethiopia","Alemayehu A.","Accepted",""],
[154,"Bedele","Crop","Horticulture","Adaptation Trial of Improved Ethiopia Cardamom (Aframomum corrorima) Varieties in Ilu Ababor and Buno Bedele Zones, Southwestern Ethiopia","Alemayehu A.","Accepted",""],
[155,"Bore","Crop","Cereals","Bread Wheat (Triticum aestivum L.) Regional Variety Trial (BWRVT-HL-27) at High Land Areas","Aliyi K.","Accepted",""],
[156,"Bore","Crop","Cereals","Bread Wheat (Triticum aestivum L.) Regional Variety Trial (BWPYT-ML-27) at Mid Land Areas","Aliyi K.","Accepted",""],
[157,"Bore","Crop","Cereals","Bread Wheat National Performance Trial at High Land of Ethiopia (BW-NPT-HL-27)","Aliyi K.","Accepted",""],
[158,"Bore","Crop","Cereals","Nursery Observation of Bread Wheat (Triticum aestivum L.) genotypes at High Land (NO-BW-HL-27) of Guji, Southern Oromia","Aliyi K.","Accepted",""],
[159,"Bore","Crop","Cereals","Nursery Observation of Bread Wheat (Triticum aestivum L.) genotypes at Mid Land (NO-BW-ML-27) of Guji, Southern Oromia","Aliyi K.","Accepted",""],
[160,"Bore","Crop","Cereals","Food Barley (Hordeum vulgare L.) Preliminary Variety Trial (FBPYT-27) for mid land Areas of Guji Zone, Southern Oromia","Aliyi K.","Accepted",""],
[161,"Bore","Crop","Cereals","Food Barley (Hordeum vulgare L.) National Performance Trial at High Land of Ethiopia (FB-NPT-HPA-27)","Aliyi K.","Accepted",""],
[162,"Bore","Crop","Cereals","Nursery Observation of Food Barley (Hordeum vulgare L.) genotypes at high Land (NO-FB-HL-27) of Guji, Southern Oromia","Aliyi K.","Accepted",""],
[163,"Bore","Crop","Cereals","Malt Barley (Hordeum Distichon L.) Regional Variety Trial (MB-RVT-HL-27) at High Land of Guji Zone Southern Oromia","Aliyi K.","Accepted",""],
[164,"Bore","Crop","Cereals","Malt Barley (Hordeum Distichon L.) National Performance Trial at High Land of Ethiopia (MB-NPT-HPA-27)","Aliyi K.","Accepted",""],
[165,"Bore","Crop","Cereals","Nursery Observation of Malt Barley (Hordeum Distichon L.) genotypes at high Land (NO-MB-HL-27) of Guji, Southern Oromia","Aliyi K.","Accepted",""],
[166,"Bore","Crop","Cereals","Tef (brown seeded) [Eragrostis tef (Zucc.) Trotter] Regional Variety Trial at Mid land of Guji zone (TB-RVT-27)","Aliyi K.","Accepted",""],
[167,"Bore","Crop","Cereals","Observation Nursery of Tef [Eragrostis tef (Zucc.)Trotter] genotypes at mid land at Guji, Southern Oromia ((TON-ML-27)","Aliyi K.","Accepted",""],
[168,"Bore","Crop","Cereals","Evaluation of Farmyard Manure Integrated with Chemical Fertilizer on Yield, Yield Components and Quality of Bread Wheat (Triticum aestivum L) in Highlands of Guji zone, Southern Oromia","Seyoum A.","Accepted","Reduce the levels of FYM, for example to 1,3,5 t/ha; instead of Zero level, use (0,0) plot as check"],
[169,"Bore","Crop","Cereals","Effect of Integrated Organic and Inorganic fertilizers on Yield, yield components and Quality of Bread wheat (Triticum aestivum L) in Bore District, Guji Zone, Southern Ethiopia","Seyoum A.","Accepted","Apply lime uniformly to all plots, not as treatment"],
[170,"Bore","Crop","Cereals","Effect of Farmyard Manure and Inorganic Fertilizer on Yield and Yield Components of Food Barley (Hordeum vulgre L) in Highlands of Guji zone, Southern Oromia","Seyoum A.","Accepted","Reduce the levels of FYM, for example to 1,3,5 t/ha; instead of Zero level, use (0,0) plot as check"],
[171,"Bore","Crop","Cereals","Evaluation of Vermicompost Integrated with Inorganic Fertilizer on Yield, Yield Components and Quality of Malt Barley (Hordeum disticho.) in the Highlands of Guji Zone, Southern Ethiopia","Seyoum A.","Accepted","Use (0,0) control plot, include quality parameters in data collection"],
[172,"Bore","Crop","Cereals","Integration of Vermi compost and NP Fertilizer on Yield Component and Yield of Tef at Mid-land of Guji zone, Southern Ethiopia","Seyoum A.","Accepted","Use the previous comments as to the levels and control plot"],
[173,"Bore","Crop","Pulses","Faba Bean Variety Verification Trial (FB-VVT-2027)","Tekalign A.","Accepted",""],
[174,"Bore","Crop","Pulses","Faba Bean Preliminary Yield Trial (FB-PYT-2027)","Tekalign A.","Accepted",""],
[175,"Bore","Crop","Pulses","Faba Bean Preliminary Observation Trial (FB-PON-2027)","Tekalign A.","Accepted",""],
[176,"Bore","Crop","Pulses","Evaluation of Superior MAGIC-Derived Faba Bean (Vicia faba L.) Genotypes","Tekalign A.","Accepted","Change to RVT"],
[177,"Bore","Crop","Pulses","Shiro-type Field Pea (Pisum sativum L.) Variety Verification Trial (FP-VVT-2027)","Tekalign A. & Deressa Sh.","Accepted",""],
[178,"Bore","Crop","Pulses","Kik-type Field Pea (Pisum sativum L.) Variety Verification Trial (FP-VVT-2027)","Tekalign A. & Deressa Sh.","Accepted",""],
[179,"Bore","Crop","Pulses","Field Pea Preliminary Observation Trial (FP-PON-2027)","Tekalign A.","Accepted",""],
[180,"Bore","Crop","Pulses","Small Red Common Bean Variety Verification Trial (SRCB-VVT-2027)","Tekalign A. & Deressa Sh.","Accepted",""],
[181,"Bore","Crop","Pulses","Small White Common Bean Variety Verification Trial (SWCB-VVT-2027)","Tekalign A. & Deressa Sh.","Accepted",""],
[182,"Bore","Crop","Pulses","Large Red Common Bean Preliminary Yield Trial (LRCB-PYT-2027)","Tekalign A.","Accepted",""],
[183,"Bore","Crop","Pulses","Large Speckled Common Bean Preliminary Yield Trial (LSCB-PYT-2027)","Tekalign A.","Accepted",""],
[184,"Bore","Crop","Pulses","Evaluation of Rapeseed (Brassica napus L.) Varieties","Tekalign A.","Accepted",""],
[185,"Bore","Crop","Pulses","Preliminary Observation Nursery of Groundnut (Arachis hypogaea L.) Genotypes","Roboth N.","Accepted",""],
[186,"Bore","Crop","Pulses","Effect of Planting Proportion of Component Crops in Faba bean -Field Pea Inter cropping System in Highlands of Guji Zone, Southern Oromia","Deresa Sh.","Accepted","Replace intercropping by mixed cropping system"],
[187,"Bore","Crop","Pulses","Effect of plant spacing and NP Rates on the yield and yield component of field pea (pisum sativum L.) at Bore, Southern Oromia, Ethiopia","Deresa Sh.","Accepted","improve per suggestions in the main document5"],
[188,"Bore","Crop","Pulses","1. Effect of vermi-compost on growth, Yield and yield components of Common Bean Varieties Under Lime Treatment (Phaseolus vulgaris) at Midland of Guji Zone, Southern oromia","Deresa Sh.","Accepted","Modified to: Effect of vermi-compost and Phosphorus rates on growth, Yield and yield components of Common Bean Varieties. Use one best variety"],
[189,"Bore","Crop","Pulses","Effect of Different Bio-fertilizer Inoculation on nodulation, yield and yield components of Chickpea Varieties at Midland of Guji Zone, Southern oromia","Deresa Sh.","Rejected","under moisture stress the bio-fertilizer is not effective"],
[190,"Bore","Crop","Horticulture","Irish Potato (Solanum tuberosum L.) Regional Variety Trial (IP RVT-2027)","Arega A.","Accepted",""],
[191,"Bore","Crop","Horticulture","Irish Potato (Solanum tuberosum L.)Preliminary yield Trial (IP PYT-2027) in the highland areas of Guji zone","Arega A.","Accepted",""],
[192,"Bore","Crop","Horticulture","Irish Potato (Solanum tuberosum L.)Preliminary yield Trial (IP PYT-2027) in the midland areas of Guji zone","Arega A.","Accepted",""],
[193,"Bore","Crop","Horticulture","Irish Potato (Solanum tuberosum L.)Observation Nursery (IP PON-2027) in the highland areas of Guji Zone","Arega A.","Accepted","be secure the germplasm"],
[194,"Bore","Crop","Horticulture","Black cumin (Nigella sativa L.) Variety Verification Trial (BCVVT, 2027","Arega A.","Accepted",""],
[195,"Bore","Crop","Horticulture","Fenugreek (Trigonellafoenum-graecum L.) Variety Verification Trial (FGVVT-","Arega A.","Accepted",""],
[196,"Bore","Crop","Horticulture","Evaluation of Different Improved Carrot (Daucus carota L.) Varieties under the Highland Agro-Ecology of Guji Zone, Oromia, Ethiopia","Solomon T","Accepted","be secure the varieties"],
[197,"Bore","Crop","Horticulture","Effects of Potato-Based Multi-Season Cropping Sequences and Preceding Crops on the Yield Performance of Wheat and Faba Bean","Solomon T","Rejected",""],
[198,"Bore","Crop","Horticulture","Determination of Vermi-compost and Biochar Rates for Potato (Solanum tuberosum L.) Production of in the Highland Areas of Guji Zone, Southern Ethiopia","Arega A.","Accepted",""],
[199,"Bore","Crop","Horticulture","Double-cropping of Potato (Solanum tuberosum L.) with Faba bean (Vicia faba L.) Response to Inorganic Fertilizer in the highland areas of Guji, Southern Ethiopia","Arega A.","Accepted",""],
[200,"Bore","Crop","Horticulture","Effect of Intercropping Irish Potato with Common Bean in the midland areas of Guji Zone, southern Ethiopia","Arega A.","Rejected","not combatable"],
[201,"Fedis","Crop","Cereals","Early Maturing Sorghum Variety Verification Trial (VVT)","Zeleke L.","Accepted","check the objectives, use recent checks"],
[202,"Fedis","Crop","Cereals","Dual Purpose sorghum Variety Verification Trial (DPSVVT)","Zeleke L.","Accepted","No materials and methods, locations, initiators etc....."],
[203,"Fedis","Crop","Cereals","Long Maturing Sorghum Regional Variety Trial for Mid-land areas of East Hararghe","Zeleke L.","Accepted",""],
[204,"Fedis","Crop","Cereals","Early Maturing Sorghum Preliminary Yield Trial (SPYT)","Zeleke L.","Accepted",""],
[205,"Fedis","Crop","Cereals","Screening of Early maturing sorghum genotypes for low moisture stress areas of East Hararghe, Ethiopia","Zeleke L.","Accepted","Correct the title to the breeding type (PON)("],
[206,"Fedis","Crop","Cereals","Development of Drought-tolerant Sorghum Breeding Materials through Crossing of Elite High-Yielding and Early-Maturing Parents","Zeleke L.","Accepted","No materials and methods, locations, initiators etc....., Clearly indicate the parental lines with their merits"],
[207,"Fedis","Crop","Cereals","Bread wheat Regional Variety Trial for high land areas of East Hararghe zone","Zeleke L.","Accepted",""],
[208,"Fedis","Crop","Cereals","Bread wheat Regional Variety Trial for low moisture areas of East Hararghe zone","Zeleke L.","Accepted",""],
[209,"Fedis","Crop","Cereals","Bread wheat Observation Nursery Trial for high land areas of East Hararghe zone","Zeleke L.","Accepted",""],
[210,"Fedis","Crop","Cereals","Food Barley Regional Variety Trial (FBRVT) for High land areas of East Hararghe","Zeleke L.","Accepted","Merge the two objectives into one"],
[211,"Fedis","Crop","Cereals","Food Barley Preliminary Yield Trial (FBPYT) for High land areas of East Hararghe","Zeleke L.","Accepted",""],
[212,"Fedis","Crop","Cereals","Food Barley Preliminary Yield Trial (FBPYT) for low moisture Areas of East Hararghe","Zeleke L.","Accepted",""],
[213,"Fedis","Crop","Cereals","Food Barley (Hordeum vulgare L.) Observation Trial for High-land areas of East Hararghe, Ethiopia","Zeleke L.","Accepted",""],
[214,"Fedis","Crop","Cereals","Brown seeded Finger millet (Eleusine coracana) Regional Variety Trial for lowland areas","Zeleke L.","Accepted",""],
[215,"Fedis","Crop","Cereals","Finger Millet Variety Verification Trial (FMVVT)","Zeleke L.","Accepted","Please revise this section (use recent released checks)"],
[216,"Fedis","Crop","Cereals","Pearl Millet Adaptation Trial in East Hararghe, Ethiopia","Zeleke L.","Accepted","Be secure the varieties used, List the materials used (Varieties) and also increase the number of varieties. Also Please, revise the objectives"],
[217,"Fedis","Crop","Cereals","White-Seeded Tef (Eragrostis tef [Zucc.] Trotter) Adaptation Trial for East Hararghe Zone, Eastern Oromia, Ethiopia","Zeleke L.","Accepted","Be secure the varieties used, List the materials used (Varieties) and also increase the number of varieties. Also Please, revise the objectives"],
[218,"Fedis","Crop","Pulses","Sesame (Sesamum indicum L.) Observation Nursery yield trial","Awwal M.","Accepted","if possible include Umera ARC materials"],
[219,"Fedis","Crop","Pulses","Sesame (Sesamum indicum L.) Regional Variety trial","Awwal M.","Accepted","add more location"],
[220,"Fedis","Crop","Pulses","Mung bean Observation Nursery trial","Awwal M. and Habte B","Accepted",""],
[221,"Fedis","Crop","Pulses","Mung bean preliminary yield trial","Awwal M. and Habte B","Accepted","List the number of genotypes"],
[222,"Fedis","Crop","Pulses","Nursery observation of Chick pea (Kabuli types) genotypes for moisture stress of eastern lowlands of Hararghe, Oromia","Awwal M. and Habte B","Accepted","Revise the title (Kabuli type chick pea Observation nursery ....), merge the objectives to one"],
[223,"Fedis","Crop","Pulses","Nursery observation of Chick pea (Cicer arietinum L.) desi type genotypes for lowlands of east Hararghe, Oromia","Awwal M. and Habte B","Accepted","Revise the title (Kabuli type chick pea Observation nursery ....), merge the objectives to one"],
[224,"Fedis","Crop","Pulses","preliminary yield trial of Chick pea (Kabuli types) genotypes","Awwal M. and Habte B","Accepted","merge the objectives to one"],
[225,"Fedis","Crop","Pulses","preliminary yield trial of Chick pea (Cicer arietinum L.) desi type genotypes","Awwal M. and Habte B","Accepted","merge the objectives to one"],
[226,"Fedis","Crop","Pulses","Regional Variety trial of Chick pea (Kabuli types) genotypes","Awwal M.","Accepted","Revise the duration based on number of locations"],
[227,"Fedis","Crop","Pulses","Regional Variety trial trial of Chick pea (Cicer arietinum L.) desi type genotypes","Awwal M.","Accepted","Revise the duration based on number of locations"],
[228,"Fedis","Crop","Pulses","Chick pea (Cicer arietinum L.) desi Verification Variety trial","Habte B","Accepted","Use recently released varieties"],
[229,"Fedis","Crop","Pulses","Observation Nursery of Lupines albus L.","Abdi M","Rejected","Not a priority crops"],
[230,"Fedis","Crop","Pulses","Groundnut Observation Nursery Trial","Habte B","Accepted","be secure the germplasm, Revise the location to one"]
]

with open("/tmp/part1_a.json", "w") as f:
    json.dump(data, f)
print("Part 1A written:", len(data))
