import json

# Records 231 to 452
data = [
[231,"Fedis","Crop","Pulses","Groundnut Preliminary yield trial","Habte B","Accepted",""],
[232,"Fedis","Crop","Pulses","Groundnut Regional variety trial","Habte B","Accepted","Please revise this section (number of genotypes, st. checks,"],
[233,"Fedis","Crop","Pulses","Soybean Observation Nursery trial in East Hararghe Zone, Oromia, Ethiopia","Habte B","Accepted",""],
[234,"Fedis","Crop","Pulses","Early Set Soybean Preliminary yield trial","Habte B","Accepted",""],
[235,"Fedis","Crop","Pulses","Medium set Soybean Preliminary yield trial","Habte B","Accepted",""],
[236,"Fedis","Crop","Pulses","Early Set Soybean Regional variety trial","Habte B","Accepted",""],
[237,"Fedis","Crop","Pulses","Medium Set Soybean Regional variety trial","Habte B","Accepted",""],
[238,"Fedis","Crop","Pulses","Small White Common bean (Phaseolus vulgaris L.) Preliminary Yield Trial","Habte B","Accepted",""],
[239,"Fedis","Crop","Pulses","Small Red Common bean (Phaseolus vulgaris L.) Preliminary Yield Trial","Almaz A. and Awwal M","Accepted",""],
[240,"Fedis","Crop","Pulses","Large White common Bean Regional Variety trial","Almaz A. and Habte B","Accepted","Specify the materials (genotypes), st. checks"],
[241,"Fedis","Crop","Pulses","Regional Variety Trial of Linseed (Linum usitatissimum L.) for Yield, and yield related traits","Almaz A. and Habte B","Accepted","Modify the title(Linseed RVT), specify the locations, durations,"],
[242,"Fedis","Crop","Pulses","Linseed Preliminary yield trial","Almaz A. and Habte B","Accepted","Include the comments given above"],
[243,"Fedis","Crop","Pulses","Regional Variety Trial of Lentil (Lens culinaris Medik.) Yield","Almaz A. and Habte B","Accepted",""],
[244,"Fedis","Crop","Pulses","Faba Bean (Vicia faba L.) Preliminary Yield Trial","Habte B","Accepted",""],
[245,"Fedis","Crop","Horticulture","Fenugreek (Trigonella foenum-graecum L.) Variety Verification Trial","Mohammed J.","Accepted","check for recent checks"],
[246,"Fedis","Crop","Horticulture","Fenugreek (Trigonella foenum-graecum L.) Preliminary Trial","Mohammed J.","Accepted",""],
[247,"Fedis","Crop","Horticulture","Sweet Potato Regional Variety Trial in East Hararghe zone, Ethiopia","Mohammed J.","Accepted",""],
[248,"Fedis","Crop","Horticulture","Orange Fleshed Sweet Regional Variety Trial in East Hararghe Zone, Ethiopia","Mohammed J.","Accepted",""],
[249,"Fedis","Crop","Horticulture","Hot pepper (Capsicum annuum L.) PYT Trial in East Hararghe Zone","Mohammed J., Girma W. & Gezu D","Accepted",""],
[250,"Fedis","Crop","Horticulture","Black Cumin Regional Variety Yield Trial in East Hararghe","Mohammed J., Girma W. & Gezu D","Accepted",""],
[251,"Fedis","Crop","Horticulture","Black Cumin Observation Nursery Trial","Mohammed J., Girma W. & Gezu D","Accepted",""],
[252,"Fedis","Crop","Horticulture","Coriander RVT in East Hararghe zone, Ethiopia","Mohammed J.","Accepted",""],
[253,"Fedis","Crop","Horticulture","Coriander Observation Nursery in East Hararghe zone, Ethiopia","Mohammed J.","Accepted",""],
[254,"Fedis","Crop","Horticulture","Chili Pepper (Capsicum annuum L.) Observation Nursery Trial","Mohammed J.","Accepted",""],
[255,"Fedis","Crop","Horticulture","Tomato (Solanum lycopersicum L.) Observation Nursery trial","Mohammed J., Girma W. & Gezu D","Accepted","Try alternative germplasm source, Melkasa Agricultural Research Center, use one location"],
[256,"Fedis","Crop","Horticulture","Mango Varieties adaptation trial","Mohammed J., Girma W. & Gezu D","Accepted",""],
[257,"Fedis","Crop","Horticulture","Potato Varieties Adaptation Trial","Mohammed J., Girma W. & Gezu D","Accepted",""],
[258,"Fedis","Crop","Horticulture","Shallot (Allium cepa var. aggregatum) Varieties Adaptation in East Hararghe Zone, Ethiopia","Girma W.","Accepted","Ensure planting material source"],
[259,"Fedis","Crop","Horticulture","Adaptation of Okra (Abelmoschus esculentus (L) Moench) Varieties","Girma W.","Accepted",""],
[260,"Fedis","Crop","Horticulture","Turmeric (Curcuma longa) Varieties Adaptation trial","Girma W.","Rejected","Not priority for the East Ecology"],
[261,"Fedis","Crop","Cereals","Effect of Organic and Inorganic fertilizer rates a yield and yield components of hybrid maize at East Hararghe","Berehanu D.","Accepted","Arrange the treatments - NP and Vermicompost. First conduct the equivalencey of vermicompost then add NP as treatment"],
[262,"Fedis","Crop","Cereals","Effect of Nitrogen and Phosphorus Fertilizers on Yield Components and Yield of Bread Wheat (Triticum aestivum L.) in highland areas of East Hararghe","Fikadu T.","Accepted",""],
[263,"Fedis","Crop","Cereals","Evaluating the compatibility of highland sorghum {Sorghum Bicolor (L.) Moench} varieties for relay- intercropping with chickpea [Cicer Arietinum (L.)] at highland areas of East Hararghe, Ethiopia","Fikadu T.","Accepted","Work on factorila combination of two planting times with some three chickpea varieties, at least one being Kabli type; use one early maturing sorghum variety."],
[264,"Fedis","Crop","Cereals","Effect of Durum Wheat (Triticum turgidum L. var. Durum) Varieties to Varying Nitrogen Fertilizer Rates on Agronomic and Quality in highland areas of East Hararghe","Berhanu D. & Fikadu T.","Rejected",""],
[265,"Fedis","Crop","Cereals","Long-Term Evaluation of Soybean-Sorghum Crop Rotation Effects on Productivity and Soil Fertility at Fadis, Eastern Ethiopia","Birhanu D.","Accepted",""],
[266,"Fedis","Crop","Horticulture","Effect of P and Nitrogen Fertilizer Rates on Onion Yield and Yield Components in East Hararghe","Gezu D.","Accepted","Include (0,0) as control; convert DAP to elemental P"],
[267,"Fitche","Crop","Cereals","Food barley preliminary Yield Trial (FBPYT-27)","Geleta N.","Accepted",""],
[268,"Fitche","Crop","Cereals","Food Barley National performance trial (FBNPT-27)","Geleta N.","Accepted",""],
[269,"Fitche","Crop","Cereals","Bread wheat preliminary Yield Trial (BWPYT-27)","Geleta N.","Accepted",""],
[270,"Fitche","Crop","Cereals","Bread wheat RVT (BWRVT-27)","Geleta N.","Accepted",""],
[271,"Fitche","Crop","Cereals","Durum wheat RVT (DWRVT-27)","Geleta N.","Accepted",""],
[272,"Fitche","Crop","Cereals","Bread wheat National performance trial (BWNPT-27)","Geleta N.","Accepted",""],
[273,"Fitche","Crop","Cereals","Tritiacale Variety verification trial (TVVT-27)","Geleta N.","Accepted",""],
[274,"Fitche","Crop","Cereals","Tef RVT (TRVT-27)","Geleta N.","Accepted",""],
[275,"Fitche","Crop","Pulses","Faba bean (Vicia faba L.) Regional Variety Trial (Fb RVT-2027)","Name Kinati and Abreham Feyisa","Accepted",""],
[276,"Fitche","Crop","Pulses","Field pea Preliminary Observation Nursery (Fp PON-2027)","Name Kinati and Abreham Feyisa","Accepted",""],
[277,"Fitche","Crop","Pulses","Lentil Variety Verification Trial (VVT)","Name Kinati and Abreham Feyisa","Accepted","include recent checks released by the Bishoftu Agri. Research Center"],
[278,"Fitche","Crop","Pulses","Lentil Preliminary Observation Nursery (LnPON-2027)","Abreham Feyisa & Name Kinati","Accepted",""],
[279,"Fitche","Crop","Pulses","Linseed Preliminary Observation Nursery (LsPON-2027)","Abreham Feyisa & Name Kinati","Accepted",""],
[280,"Fitche","Crop","Horticulture","Potato (Solanum tubersum L.) Preliminary Yield Trial (PYT)","Zewdu T.","Accepted",""],
[281,"Fitche","Crop","Horticulture","Potato Observation Nursery (PON)","Zewdu T.","Accepted",""],
[282,"Fitche","Crop","Horticulture","Fenugreek Observation Nursery (PON)","Zewdu T.","Accepted",""],
[283,"Fitche","Crop","Pulses","Spatial Micro-Zoning and Climate-Informed Decision Support Systems for Precision Input Optimization in Some Selected Pulse and Oil seed Cropping Systems","Abrham F.","Accepted",""],
[284,"Fitche","Crop","Horticulture","Determination of P and N fertilizers application for potato under Irrigation at the highlands of North Shewa Zone; Oromia","Zewdu T.","Accepted",""],
[285,"Fitche","Crop","Horticulture","Evaluation of Different Rates of N and P on Growth and Yield Performances of Garlic (Allium sativumL.) under irrigation in North shewa Zone, Oromia, Ethiopia","Ayantu T., Zewdu T & Samson D.","Accepted",""],
[286,"Fitche","Crop","Horticulture","Evaluation of Planting Dates on Growth, Yield and Yield Components of Potato in North Shewa Zone, Oromia, Ethiopia","Samson D.","Rejected","Not priority"],
[287,"Harosabu","Crop","Cereals","Finger Millet Variety Verification Trial (Brown Seed Color)","Wakgari Raga","Accepted","Revise the objective"],
[288,"Harosabu","Crop","Cereals","Finger Millet Variety Verification Trial (White Seed Color)","Wakgari Raga","Accepted","Revise the objective"],
[289,"Harosabu","Crop","Cereals","Finger Millet Preliminary Yield Trial","Wakgari Raga","Accepted","Revise the objective"],
[290,"Harosabu","Crop","Cereals","Bread Wheat National Performance Trial","Gamachisa D","Accepted","Revise the objective"],
[291,"Harosabu","Crop","Cereals","Bread Wheat Regional Variety Trial","Gamachisa D","Accepted",""],
[292,"Harosabu","Crop","Cereals","Tef Preliminary Yield Trial","Gamachisa D","Accepted","Revise your objectives"],
[293,"Harosabu","Crop","Cereals","Sorghum Variety Verification Trial (Medium maturity set)","Gamachisa D","Accepted","Revise your objectives"],
[294,"Harosabu","Crop","Cereals","Sorghum Preliminary Observation Nursery","Gamachisa D","Accepted","Revise your objectives"],
[295,"Harosabu","Crop","Cereals","Food Barley Preliminary Yield Trial","Wakgari Raga","Accepted",""],
[296,"Harosabu","Crop","Horticulture","Fenugreek (Trigonellafoenum-graecum) Regional variety Trail in Kelem Welega and West Welega West Zones","Kibiru K","Accepted",""],
[297,"Harosabu","Crop","Horticulture","Evaluation of improved Taro (Colocasia esculenta(L.) Schott) genotypes on growth and yield performance in Kelem Welega and West Welega Zones","Kibiru K","Accepted",""],
[298,"Harosabu","Crop","Horticulture","Collection, Characterization and Evaluation of Dinicha Oromo (Plectranthus edulis) landraces from West Wollega and Kellem Wollega Zones of Oromia Region","Kibiru K","Accepted","Collaborate with Bako ARC and collect across Oromia"],
[299,"Harosabu","Crop","Horticulture","Preliminary observation nursery of potato ((Solanum tuberosum L.) in West Welega and Kelem Welega Zones of western Oromia","Kibiru K","Accepted","Revise the objective"],
[300,"Harosabu","Crop","Pulses","Preliminary Observation Nursery of Large Red Mottled Common Bean Component: Variety development","Dereje A","Accepted",""],
[301,"Harosabu","Crop","Pulses","Preliminary Observation Nursery of Large Red Common Bean","Dereje A","Accepted",""],
[302,"Harosabu","Crop","Pulses","Preliminary Observation Nursery of Mung Bean Genotypes","Dereje A","Accepted",""],
[303,"Harosabu","Crop","Pulses","Collection and Characterization of Germplasm from West Oromia Component: Variety Development (Breeding & Genetics)","Dereje A","Rejected","Ethiopia is not center of origin and diversity of this crop"],
[304,"Harosabu","Crop","Pulses","Late Type Soybean (Glycine max (L.) Merr.) Regional Variety Trial (RVT-II)","Dereje A","Accepted",""],
[305,"Harosabu","Crop","Pulses","Early Type Soybean (Glycine max (L.) Merr.) Regional Variety Trial (RVT-II)","Dereje A","Accepted",""],
[306,"Harosabu","Crop","Pulses","Small White Common Bean Preliminary Yield Trial","Dereje A","Accepted",""],
[307,"Harosabu","Crop","Pulses","Evaluation of F1 Cross lines of Large Red Mottled Common Bean","Dereje A","Accepted",""],
[308,"Harosabu","Crop","Pulses","Evaluation of F1 Cross lines of Small Red Common Bean","Dereje A","Accepted",""],
[309,"Harosabu","Crop","Pulses","Preliminary Observation Nursery of Sesame genotypes at West Oromia Component: Variety Development","Dereje A","Accepted","BARC is not center of excellence for FM. So introdue prefereable from Pawe/EBI"],
[310,"Harosabu","Crop","Pulses","Preliminary Yield Trial of Chickpea (Desi Type)","Dereje A","Accepted",""],
[311,"Harosabu","Crop","Horticulture","Effect of Phosphorus and Nitrogen fertilizer rates on Yield and Yield components of sweet potato (Ipomoea batatas L in West Wollega and Kellem Wollega zones","Kibiru K","Accepted","Increase fertilizer levels to 23, 46,69 and 92 for both of N and P as indicated in text; soil test and paritial budget analysis be conducted"],
[312,"Harosabu","Crop","Horticulture","Effect of Phosphorus and Nitrogen fertilizer rates on Yield and Yield components of Tomato (Solanum lycopersicum L) in West Welega and Kelem Welega zones","Kibiru K. & Ashenafi","Accepted","Adjust treatments as: N (46, 69, 92 and 115kg/haof P2O5) and P as: 23, 46, 69 and 92 kg/ha levels; conduct paritial budget analysis"],
[313,"Harosabu","Crop","Pulses","Effect of Phosphorus fertilizer rates on yield and yield components of field pea in Kellem Wollega Zone, Western Oromia, Ethiopia","Hambisa F.","Accepted","Choose only one variety"],
[314,"Harosabu","Crop","Pulses","Effect of Phosphorus Fertilizer rates on yield and yield components of Soybean and Residual Nutrient effects on a subsequent Maize crop in Kellem Wollega Zone, Western Oromia, Ethiopia","Hambisa F.","Rejected","Not priority"],
[315,"Harosabu","Crop","Pulses","Effect of integrated Nutrient Management and Plant spacing on soybean (Glycine max (L.) Merrill) yield and seed quality in Acidic soil of West and Kellem Wollega Zones, Western Oromia, Ethiopia","Lemessa E","Accepted","For spacing refer to previous works from Bako; work on integration of organic and inorganic fertilizers"],
[316,"Harosabu","Crop","Pulses","Effect of Lime, Vermicompost, and Inorganic P Fertilizer on yield and yield attributes of Common bean (Phaseolus vulgaris L) in Acidic soil of West and Kellem Wollega Zones, Western Oromia, Ethiopia","Lemessa E","Accepted","Lime should not be included as a factor; work on the intergatin of organic and inorganic fertilizers"],
[317,"SARC","Crop","Cereals","Effects of NP Fertilizer Rates on Grain Yield and Yield Components of Bread Wheat in Highland of Bale","Jitu A.","Pended","Should be done after the P calibration is complete"],
[318,"SARC","Crop","Cereals","Determining the Optimal NP Fertilizer Rate to Maximize Yield and Quality of Durum Wheat in Southeastern Ethiopia's Bale Highlands","Jitu A.","Accepted","Make the treatments levels complete for both N and P"],
[319,"SARC","Crop","Cereals","Optimizing NP Application Rate for Enhanced Productivity of Emmer Wheat (Triticum dicoccum) in the Bale Highlands, Ethiopia","Jitu A.","Accepted","Work on NP rate; using the recommend split application timing"],
[320,"SARC","Crop","Cereals","Optimizing Seed and NP Fertilizer Rates for Enhanced Yield and Yield-Related Traits of Food Barley (Hordeum Vulgare L.) in the Lowlands of Bale, Ethiopia","Jitu A.","Accepted","TSP may not be available"],
[321,"SARC","Crop","Cereals","Optimizing Seed and NP Fertilizer Rates for Enhanced Yield and Yield-Related Traits of Food Barley (Hordeum Vulgare L.) in the Lowlands of Bale, Ethiopia","Jitu A.","Accepted",""],
[322,"SARC","Crop","Cereals","Determining Optimal Nitrogen Fertilizer Rates to Maximize Grain Yield and Nitrogen Use Efficiency for Elite Malt Barley Lines in Bale Highlands, Ethiopia","Jitu A.","Accepted","Specify variety or genotypes by name."],
[323,"SARC","Crop","Cereals","Effects of seed rates on bread wheat varieties in highlands of bale, Southeastern, Ethiopia","Jitu A.","Rejected","There is already a recommended rate."],
[324,"SARC","Crop","Cereals","Effects of seed Rates on Durum Wheat varieties in Highlands of Bale, Southeastern Ethiopia","Jitu A.","Rejected","There is already a recommended rate."],
[325,"SARC","Crop","Pulses","Effect of Starter Nitrogen and Phosphorus Fertilizer Rates on Growth, Yield and Yield Components of Groundnut (Arachis hypogaea L.) in Bale lowland south Eastern Ethiopia","Tameru M. & Reta D.","Accepted",""],
[326,"SARC","Crop","Pulses","Agronomic and Economic Evaluation of Field Pea-Wheat Double Cropping for Enhancing Wheat Yield and Farm Profitability in South Eastern , Ethiopia","Tameru M. & Reta D.","Accepted",""],
[327,"SARC","Crop","Pulses","Agronomic and Economic Evaluation of Lentil-Wheat Double Cropping on Wheat Yield and Productivity in South Eastern, Ethiopia","Tameru M. & Reta D.","Accepted",""],
[328,"SARC","Crop","Pulses","Effect of Fertilizer and Seed Rates on Yield and Yield Components of Soybean (Glycine max L. Merrill) in the Lowlands of Bale, Southeastern Ethiopia","Reta D. and Tameru M.","Accepted","Working on seed rate is not priority as there is recommendations; instead think of addressing starter N, P fertilizers as well Rhizobium inculation"],
[329,"SARC","Crop","Pulses","Effect of Nitrogen rates and Application time on the Yield of Lentil (Lens culinaris Medik.) in the Highlands of Bale, Southeastern Ethiopia","Rta D. and Tameru M","Rejected","NP rate investigation is in progress, as an ongoing"],
[330,"SARC","Crop","Pulses","Effect of Row spacing and NP Fertilizer Rates on Growth, Yield and Yield Components of Linseed (Linum usitatissimum L.) in the Highlands of Bale, Southeastern","Reta D. and Tameru M.","Rejected","The recommendation is already available."],
[331,"SARC","Crop","Horticulture","Effects of Different Spacing and DAP fertilizer rates on Growth and Yield of Sweet Potato at Delo-mena, Southeastern Ethioipia","Kecha D.","Accepted","Work on spacing and NP (combined)"],
[332,"SARC","Crop","Horticulture","Effects of inter and intra row spacing on Growth, Yield Components and Dry Fruit Yield of Hot Pepper at Dello-mena, Southeastern Ethiopia","Kecha D.","Accepted",""],
[333,"SARC","Crop","Horticulture","Effects of Nitrogen and Phosphorus fertilizer on Growth and yield of Onion (Allium cepa L.) at Highland of Bale","Kecha D.","Accepted","set the fertilizer levels"],
[334,"SARC","Crop","Cereals","Evaluation of Bread Wheat F2 Generation-2027 (EBWF2-27)","Meti T., Mulatu A. and Ahamad M.","Accepted",""],
[335,"SARC","Crop","Cereals","Evaluation of F6 Bread Wheat Crosses for Optimum Areas of South Eastern Oromia - 2027 (EBWF6-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[336,"SARC","Crop","Cereals","Bread wheat observation nursery for low moisture areas of Bale zone-2027 (BWON for LMA-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[337,"SARC","Crop","Cereals","Bread Wheat Preliminary Yield Trial for Low moisture Areas of Bale zone - 2027 (BWPYT for LMA-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[338,"SARC","Crop","Cereals","Bread Wheat Regional Variety Trial for Low Moisture Areas of Bale zone- 2027 (BWRVT for LMA-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[339,"SARC","Crop","Cereals","Bread Wheat Observation Nursery for High Potential Areas of Bale Zone - 2027 (BWON-HPA-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[340,"SARC","Crop","Cereals","Bread Wheat Preliminary Yield Trial for High Potential Areas of Bale Zone-2027 (BWPYT for HPA-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[341,"SARC","Crop","Cereals","Bread Wheat Regional Variety Trial for High Potential Areas - 2027 (BWRVT for HPA-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[342,"SARC","Crop","Cereals","Bread Wheat National Performance Trial for High Potential Area of Bale zone- 2027 (BWNPT for HPA-27)","Mulatu A., Ahmed M. and Meti T","Accepted",""],
[343,"SARC","Crop","Cereals","Combining of elite bread wheat materials to develop quality population for high potential areas - 2027","Mulatu A., Ahamad M. and Meti T.","Accepted",""],
[344,"SARC","Crop","Cereals","Evaluation of Durum Wheat F6 Generation -2025 (EDWF6-25)","Mulatu A., Meti T. and Ahmed M.","Accepted",""],
[345,"SARC","Crop","Cereals","Durum Wheat Observation Nursery for high to mid altitude areas of Bale Zone -2027 (DWON-27)","Meti T., Ahmed M. and Mulatu A.","Accepted",""],
[346,"SARC","Crop","Cereals","Durum Wheat Preliminary Yield Trial for high to mid altitude areas of Bale zone- 2027 (DWPYT-27)","Ahmed M., Mulatu A. and Meti T.","Accepted",""],
[347,"SARC","Crop","Cereals","Durum Wheat Regional Variety Trial for high to mid altitude areas of Bale zone- 2027 (DWRVT-27)","Ahmed M., Mulatu A. and Meti T.","Accepted",""],
[348,"SARC","Crop","Cereals","Evaluation of Emmer Wheat F1 Generation for High land Areas of Bale Zone-2027","Mulatu A., Ahamad M. and Meti T.","Accepted",""],
[349,"SARC","Crop","Cereals","Hybridization of food barley for diseases resistance and major agronomic Traits","Aschalew M & Hiwot S.","Accepted",""],
[350,"SARC","Crop","Cereals","Evaluation of food barely F1 generation","Hiwot S. & Aschalew M","Accepted",""],
[351,"SARC","Crop","Cereals","Evaluation of food barely F2 generation","Hiwot S. & Aschalew M","Accepted",""],
[352,"SARC","Crop","Cereals","Semi hulled Barley Hybridization for Agronomic and nutritional quality trait","Hiwot S. & Aschalew M","Accepted",""],
[353,"SARC","Crop","Cereals","Evaluation of Semi hulled barely F1 generation","Aschalew M & Hiwot S.","Accepted",""],
[354,"SARC","Crop","Cereals","Evaluation of Semi hulled barely F2 generation","Hiwot S. & Aschalew M","Accepted",""],
[355,"SARC","Crop","Cereals","Food Barley Preliminary Observation Nursery for High Potential Areas-27","Aschalew M & Hiwot S.","Accepted",""],
[356,"SARC","Crop","Cereals","Food Barley Preliminary Variety Trial-27","Aschalew M & Hiwot S.","Accepted",""],
[357,"SARC","Crop","Cereals","Malt Barley Hybridization for Selected Agronomic and Malt Quality Trait","Aschalew M & Hiwot S.","Accepted",""],
[358,"SARC","Crop","Cereals","Evaluation of malt barely F1 generation","Aschalew M & Hiwot S.","Accepted",""],
[359,"SARC","Crop","Cereals","Evaluation of barely F2 generation","Aschalew M & Hiwot S.","Accepted",""],
[360,"SARC","Crop","Cereals","Evaluation of malt barely F3 generation","Hiwot S. & Aschalwe M.","Accepted",""],
[361,"SARC","Crop","Cereals","Evaluation of malt barely F4 generation","Aschalew M & Hiwot S.","Accepted",""],
[362,"SARC","Crop","Cereals","Malt Barley Preliminary Observation Nursery -27","Aschalew M & Hiwot S.","Accepted",""],
[363,"SARC","Crop","Cereals","Malt Barley Preliminary Variety Trial-27","Aschalew M & Hiwot S.","Accepted",""],
[364,"SARC","Crop","Cereals","Malt Barley National Variety Trial -27","Aschalew M & Hiwot S.","Accepted",""],
[365,"SARC","Crop","Pulses","Faba bean Observation Nursery 2027/28","Tadele Tadesse and Belay Asmare","Accepted",""],
[366,"SARC","Crop","Pulses","Faba bean Preliminary Yield Trial 2027/28","Tadele Tadesse and Belay Asmare","Accepted",""],
[367,"SARC","Crop","Pulses","Faba bean Regional Variety Trial 2027/28","Tadele Tadesse and Belay Asmare","Accepted",""],
[368,"SARC","Crop","Pulses","Faba bean Variety Verification Trial 2027/28","Tadele Tadesse and Belay Asmare","Accepted",""],
[369,"SARC","Crop","Pulses","Field pea Preliminary Yield Trial 2027/28","Belay Asmare and Tadele Tadesse","Accepted",""],
[370,"SARC","Crop","Pulses","Field pea Regional Variety Trial 2027/28","Belay Asmare and Tadele Tadesse","Accepted",""],
[371,"SARC","Crop","Pulses","Field pea Variety Verification Trial 2027/28","Tadele T. & Belay A.","Accepted",""],
[372,"SARC","Crop","Pulses","Lentil Observation Nursery 2027/28","Belay Asmare and Tadele Tadesse","Accepted",""],
[373,"SARC","Crop","Pulses","Lentil Preliminary Yield Trial 2027/28","Tadele T. & Belay A.","Accepted",""],
[374,"SARC","Crop","Pulses","Lentil Variety Verification Trial 2027/28","Tadele T. & Belay A.","Accepted",""],
[375,"SARC","Crop","Pulses","Kabuli Type Chickpea Observation nursery 2027","Tadele T. & Belay A.","Accepted",""],
[376,"SARC","Crop","Pulses","Desi Type Chickpea Observation nursery 2027","Belay Asmare and Tadele Tadesse","Accepted",""],
[377,"SARC","Crop","Pulses","Kabuli Type Chickpea Preliminary Yield Trial 2027/28","Tadele T. & Belay A.","Accepted",""],
[378,"SARC","Crop","Pulses","Kabuli type Chickpea Regional Variety Trial 2027","Belay Asmare and Tadele Tadesse","Accepted",""],
[379,"SARC","Crop","Pulses","Desi type Chickpea Variety Verification Trial 2027","Belay Asmare and Tadele Tadesse","Accepted",""],
[380,"SARC","Crop","Pulses","Kabuli type Chickpea Variety Verification Trial 2027","Tadele T. & Belay A.","Accepted",""],
[381,"SARC","Crop","Pulses","Mung bean Observation Trial 2027","Belay Asmare and Tadele Tadesse","Accepted",""],
[382,"SARC","Crop","Pulses","Groundnut Observation Trial 2027","Belay Asmare and Tadele Tadesse","Accepted",""],
[383,"SARC","Crop","Pulses","Linseed Observation Nursery 2027","Belay Asmare and Tadele Tadesse","Accepted",""],
[384,"SARC","Crop","Pulses","Ethiopian Mustared/Gomenzer Observation Nursery 2027","Belay Asmare and Tadele Tadesse","Accepted",""],
[385,"SARC","Crop","Horticulture","Fenugreek Observation Nursery","Birhane I., Gemechu E. & Kecha d.","Accepted",""],
[386,"SARC","Crop","Horticulture","Fenugreek Preliminary Yield Trial","Birhane I., Gemechu E. & Kecha d.","Accepted",""],
[387,"SARC","Crop","Horticulture","Fenugreek Regional Variety Trial-2027","Gemechu E. & Birhane I","Accepted",""],
[388,"SARC","Crop","Horticulture","Fenugreek Variety Verification Trial-2027","Gemechu E. & Birhane I","Accepted",""],
[389,"SARC","Crop","Horticulture","Black cumin Observation Nursery","Birhane I., Gemechu E. & Kecha d.","Accepted",""],
[390,"SARC","Crop","Horticulture","Black Cumin Preliminary Yield Trial-27","Gemechu E. & Birhane I.","Accepted",""],
[391,"SARC","Crop","Horticulture","Black Cumin Regional Variety Trial-2027","Gemechu E. & Birhane I.","Accepted",""],
[392,"SARC","Crop","Horticulture","White Cumin Preliminary yield Trial -27","Gemechu E. & Birhane I.","Accepted",""],
[393,"SARC","Crop","Horticulture","White Cumin Variety Verification Trial-27","Gemechu E. & Birhane I.","Accepted",""],
[394,"SARC","Crop","Horticulture","Coriander Observation Nursery","Gemechu E. & Birhane I.","Accepted",""],
[395,"SARC","Crop","Horticulture","Coriander Regional Variety trial -27","Gemechu E. & Birhane I.","Accepted",""],
[396,"SARC","Crop","Horticulture","Potato Regional Variety Trial-27","Gemechu E. & Birhane I.","Accepted",""],
[397,"SARC","Crop","Horticulture","Characterization of Brassica Orientale species at Bale highlands","Gemechu E. & Birhane I.","Accepted","Make clear wheather or not the accessations are already available; if not include collection"],
[398,"Mechara","Crop","Cereals","Effects of phosphorus fertilizer and seed rates on yield and yield traits of Tef (Eragrostis tef) in West Hararghe zone","Desu A.","Accepted","Incorporate the comments givenn in the body of the proposal i.e study NP rate in factorial combination; use the proposed levels; include soil analysis and paritial budget analysis"],
[399,"Mechara","Crop","Pulses","Effects of P and Starter N Rates on Growth, Yield Components, and Yield of Small Red bean in West Hararghe, Ethiopia","Firaol A.","Accepted","Study starter N and P rates, using the specified treatments in the body of the proposa."],
[400,"Mechara","Crop","Pulses","Effects of Inter and Intra Row Spacing on Yield and Yield Components of Desi type Chick Pea (Cicer arietinum L.) In Western Hararghe Zone, Eastern Ethiopia","Firaol A.","Accepted","An intrarow spacing of 25 Is too wide; reduce it."],
[401,"Mechara","Crop","Horticulture","Effects of Phosphorus and N fertilizer rare on Yield and Yield Component of Onion (Allium cepa L.) in West Hararghe Zone","Gezahegn A., Dereje D & Dagne A.","Accepted",""],
[402,"Mechara","Crop","Horticulture","Determination of Inter and Intra row spacing on yield and yield component of Tomato (Solanum lycopersicum L.), under irrigation in West Hararghe zone, Eastern Ethiopia","Gezahegn A., Dereje D & Dagne A.","Rejected","Spacing is not a priority bottleneck; look for other gaps such as NP rates"],
[403,"Mechara","Crop","Horticulture","Effect of Phosphorus and Nitrogen Fertilizer Rate on Yield and Yield Traits of Potato (Solanum tuberosum L.) in West Hararghe Zone","Gezahegn A., Dereje D & Dagne A.","Accepted",""],
[404,"Mechara","Crop","Horticulture","Effect of Inter-Row and Intra-Row Spacing on Yield and Yield-Related Traits of Sweet Potato in West Hararghe Zone","Gezahegn A., Dereje D & Dagne A.","Accepted","Adjusted the treatment levels as indicated in the body of the proposal i.e intrarow spacing of 80, 90, 100,110"],
[405,"Mechara","Crop","Cereals","Sorghum Observation Nursery for the lowland of West Hararghe Zone","Desu A.","Accepted",""],
[406,"Mechara","Crop","Cereals","White Seeded Tef (Eragrostis tef) Observation Nursery Trial","Desu A.","Accepted",""],
[407,"Mechara","Crop","Cereals","White Seeded Finger Millet (Eleusine coracana (L) Observation Nursery Trial","Desu A.","Accepted",""],
[408,"Mechara","Crop","Pulses","Early set Desi type Chick Pea (Cicer arietinum L.) Preliminary Observation Nursery in West Hararghe, Eastern Ethiopia","Firaol A.","Accepted","Is there early set? Check and correct if not"],
[409,"Mechara","Crop","Pulses","Early set Kabuli type Chick Pea (Cicer arietinum L.) Preliminary Observation Nursery in West Hararghe, Eastern Ethiopia","Firaol A.","Accepted",""],
[410,"Mechara","Crop","Pulses","Mung bean (Vigna radiata) Preliminary Nursery Observation in West Hararghe, Eastern Ethiopia","Shanene H. & Firaol A.","Accepted","Materials may not be available at EBI; stick to Melkasa ARC for germplasm source"],
[411,"Mechara","Crop","Pulses","Lentil (Lens culinaris Medik.) Preliminary Nursery Observation trial in West Hararghe, Eastern Ethiopia","Shanene H. & Firaol A.","Accepted",""],
[412,"Mechara","Crop","Pulses","Groundnut (Arachis hypogaea L.) Variety Verification Trial in West Hararghe, Eastern Ethiopia","Shanene H. & Firaol A.","Accepted",""],
[413,"Mechara","Crop","Pulses","Small Red Common Bean Regional Variety Trial in West Hararghe, Eastern Oromia","Shanene H. & Firaol A.","Accepted",""],
[414,"Mechara","Crop","Pulses","Ground nut (Arachis hypogeae L.) Preliminary Nursery Observation in West Hararghe, Eastern Ethiopia","Firaol A.","Accepted",""],
[415,"Mechara","Crop","Pulses","Small white Common bean (Phaseolus vulgares L) Preliminary Nursery Observation in West Hararghe, Eastern Ethiopia","Firaol A. & Shanene H.","Accepted",""],
[416,"Mechara","Crop","Pulses","Large Speckled Common Bean (Phaseolus Vulgaris L) Preliminary Nursery Observation in West Hararghe, Eastern Ethiopia","Firaol A.","Accepted",""],
[417,"Mechara","Crop","Pulses","Large Red Common Bean (Phaseolus Vulgaris L) Preliminary Nursery Observation in West Hararghe, Eastern Ethiopia","Kedir A.","Accepted",""],
[418,"Mechara","Crop","Pulses","Early Set Soybean (Glycine ) Nursery Observation Trial","Kedir A.","Accepted","Note that the source of germplasm is Jimma Agricultural Research Center and correct accordinly"],
[419,"Mechara","Crop","Horticulture","Fenugreek Preliminar Observation Nursery","Dereje D., Gezahegn A., Dagne A.","Accepted",""],
[420,"Mechara","Crop","Horticulture","White fleshed Sweet Potato Genotypes (Ipomoea batatas (L.) Lam) Observation Nursery","Dereje D., Gezahegn A., Dagne A.","Accepted",""],
[421,"Mechara","Crop","Horticulture","Orange fleshed Sweet Potato Genotypes (Ipomoea batatas (L.) Lam) Observation Nursery","Dereje D., Gezahegn A., Dagne A.","Accepted",""],
[422,"Mechara","Crop","Horticulture","Irish Potato (Solanum tuberosum L.) Nursery Observation Trial","Dereje D., Gezahegn A., Dagne A.","Accepted",""],
[423,"Mechara","Crop","Horticulture","Hot pepper genotypes (Capsicum annuum L.) Observation Nursery Trial","Dereje D., Gezahegn A., Dagne A.","Accepted",""],
[424,"Mechara","Crop","Horticulture","Adaptation Trial of Recently Released Open Pollinated Onion ((Allium cepa L.) Varieties in West Hararghe Zone, Eastern Oromia, Ethiopia","Dagne A., Dereje D., Gezahegn A","Accepted","Descibe the varieties (name, source center, year of release etc)"],
[425,"YPDARC","Crop","Cereals","Effect of Nitrogen Application Rates and Sowing Time on Yield and yield components of Maize (Zea mays L.) in Borana and West Guji Zones, Southern Ethiopia","Ibsa J.","Rejected","Planting time study may not be feasible in moisture-stressed areas such as Yaballo"],
[426,"YPDARC","Crop","Cereals","Response of Maize to Nitrogen and Phosphorus Fertilizer Rates in the Mid- to Highland Areas of Bule Hora, West Guji, Southern Ethiopia","Ibsa J.","Accepted",""],
[427,"YPDARC","Crop","Cereals","Optimization of Nitrogen Rate and Application Frequency for Teff Varieties in moisture stress areas of Borana, Southern Ethiopia","Ibsa J.","Rejected","There is no need to study N application frequency. Try to address other issues such NP"],
[428,"YPDARC","Crop","Pulses","Effect of NP Fertilizer Rate and Rhizobium Inoculation on the Yield and Yield Components of Field Pea (Pisum sativum L.) In West Guji Zones, Southern Oromia, Ethiopia","Gutema I.","Accepted","Focus on P fertilizer Rhizobium inoculation; no need to study N rate for field pea; check for appropriate strain of Rhizobium"],
[429,"YPDARC","Crop","Pulses","Optimizing Row and Plant Spacing for Agronomic Performance and Economic Returns of Newly Released Common Bean Varieties in Borana and West Guji Zones, Southern Ethiopia","Gutema I. & Ibsa J.","Rejected","spacing is not a priority bottleneck; look for other gaps such as P rates & Starter N"],
[430,"YPDARC","Crop","Pulses","Effect of Row Spacing and P Fertilizer Rate on the Yield and Yield Components of Chickpea (Cicer arietinum L.) in Borana and West Guji Zones, Southern Oromia, Ethiopia","Gutema I.","Accepted",""],
[431,"YPDARC","Crop","Pulses","Optimizing Inter-row Spacing and Seeding Rate for Enhanced Sesame Productivity in the Dry Land Agro-ecology of, West Guji Zone, Southern Ethiopia","Gutema I.","Rejected","Not a priority; try to address other bottlenecks for sesame (eg. Fertilizer rates)"],
[432,"YPDARC","Crop","Cereals","Tef [Eragrostis tef (zucc.) Trotter] Regional Variety Trial (RVT) for lowland Areas of Southern Oromia, Ethiopia","Belda I.","Accepted","Use recent varieties for standard check"],
[433,"YPDARC","Crop","Cereals","Bread Wheat (Triticum aestivum L.) Preliminary Yield Trial (PYT) for grain yield and disease resistance at highland Areas of Bule-hora district","Belda I. & Kemal K.","Accepted",""],
[434,"YPDARC","Crop","Cereals","Bread Wheat (Triticum aestivum.L) Regional Variety Trial (RVT) for grain yield and drought tolerance at Lowland Areas of Southern Oromia","Belda I.","Accepted","No need of local check for bread wheat; use recently released varieties for standard chec"],
[435,"YPDARC","Crop","Cereals","Performance Evaluation of Durum wheat (Triticum turgidum ssp durum) at selected districts of west Guji zone, southern Oromia, Ethiopia","Dejene L.","Accepted","If possible, add one more locations. Two years duration is enough."],
[436,"YPDARC","Crop","Cereals","Evaluation of Newly released Food Barley (Hordeum Vulgare L) Varieties for mid land Areas of Southern Oromia","Dejene L.","Accepted","Describe the varieties (by names, source center, year of release etc)"],
[437,"YPDARC","Crop","Cereals","Malt Barley (Hordeum vulgare L.) adaption trial at highland Areas of west Guji zone, southern Oromia","Dejene L.","Accepted",""],
[438,"YPDARC","Crop","Cereals","Performance Evaluation Newly released white seed Tef (Eragrostic tef L.) Varieties for grain yield and drought tolerance at selected lowland Areas of Southern Oromia","Belda E. and Dejene L.","Accepted","Describe the varieties (by names, source center, year of release etc); write clear objective"],
[439,"YPDARC","Crop","Pulses","Large Red Common bean Observation nursery","Ejigu I.","Accepted",""],
[440,"YPDARC","Crop","Pulses","Small Red Common bean Regional Variety Trial","Ejigu I.","Accepted","Location for RVT should be three"],
[441,"YPDARC","Crop","Pulses","Large white common bean Observation nursery","Ejigu I.","Accepted",""],
[442,"YPDARC","Crop","Pulses","Small white Common Regional Variety Trial","Ejigu I.","Accepted","Location for RVT should be three"],
[443,"YPDARC","Crop","Pulses","Speckled common bean Observation nursery","Ejigu I.","Accepted",""],
[444,"YPDARC","Crop","Pulses","Speckled Common Bean Regional Variety Trial","Ejigu I.","Accepted",""],
[445,"YPDARC","Crop","Pulses","Mung bean Reginal variety trial (RVT-2027)","Ejigu I.","Accepted","Location for RVT should be three"],
[446,"YPDARC","Crop","Pulses","Shiro type Field pea Observation Nursery","Gutema I. & Ejigu I.","Accepted",""],
[447,"YPDARC","Crop","Pulses","Kik type Field pea Observation Nursery","Gutema I. & Ejigu I.","Accepted",""],
[448,"YPDARC","Crop","Horticulture","Black cumin regional variety trial (RVT)","Taera I","Accepted",""],
[449,"YPDARC","Crop","Horticulture","Fenugreek Regional Variety Trial (RVT)","Taera I","Accepted",""],
[450,"YPDARC","Crop","Horticulture","Chili preliminary Yield Trail (PYT)","Taera I","Accepted",""],
[451,"YPDARC","Crop","Horticulture","Irish Potato preliminary yield trial (PYT)","Taera I","Accepted",""],
[452,"YPDARC","Crop","Horticulture","Orange Fleshed Sweet Potato Preliminary yield trial (PYT).","Taera I","Accepted",""]
]

with open("/tmp/part1_b.json", "w") as f:
    json.dump(data, f)
print("Part 1B written:", len(data))
