import json

# Records 453 to 710
data = [
[453,"ATARC","Livestock","poultry","Genetic Evaluation and Observation Trial of Desirable Traits through direct and reciprocal crossing of Tetra H and Koekoek chicken breeds under ATARC","Dr. Gebawo Tibesso","Accepted with modification",""],
[454,"ATARC","Livestock","Api","Evaluation of Adaptation, Flowering Phenology and Honey Production Potential of Opuntia ficus-indica (L.) Mill. as a Bee Forage Plant in [Study Area], Ethiopia","Desta Abi","Accepted with modification",""],
[455,"ATARC","Livestock","Meat","Adaptation and Productive Performance of Boer Goats and Their Crosses with Arsi-Bale Indigenous Goats under Ethiopian Production Systems","Ashebir Worku","Accepted with modification",""],
[456,"ATARC","Livestock","Meat","Molecular Insights into Parasite Resistance in Goats: Galectin Gene Expression and Its Association with Parasite Burden, FAMACHA Scores and Five Point Check","Ashebir Worku & Dr. Abdella Edao","Accepted with modification",""],
[457,"ATARC","Livestock","poultry","Adaption and Feeding Trail of Black Soldier Fly (Hermetia illucens) Larvae in Layer Chicken Diets at ATARC","Beshir Husein and Usman A","Accepted with modification",""],
[458,"ATARC","Livestock","poultry","Assessment of Biosecurity Measures in Small and Medium Scale Poultry Farms in Urban and Peri-urban of Western Oromia","Tesfa G.","Accepted with modification",""],
[459,"ATARC","Livestock","Dairy","Field Efficacy, In Vitro Mortality, and Safety Profile of Locally Formulated Botanical Extracts (Calotropis procera and Croton macrostachyus) Against Hard Ticks (Rhipicephalus spp.) and Mange Mites (Sarcoptes scabiei var. bovis) in Native Calves","Dr Abdela Edao","Accepted with modification",""],
[460,"ATARC","Livestock","Meat","Field-Screening and Quantitative Risk Assessment of Mycotoxin Levels (Aflatoxin B1 and Zearalenone) in Commercial Oilseed Cakes and Storage Feeds Across Feedlot Supply Chains","Genet Dadi","Accepted with modification",""],
[461,"ATARC","Livestock","Meat","Assessment of major health constraints, disease occurrence and associated risk factors of sheep in urban and peri-urban fattening systems of East Shewa and West Arsi Zones, Oromia, Ethiopia.","Dr. Gebawo Tibesso","Accepted with modification",""],
[462,"ATARC","Livestock","Meat","Identification and economic impact assessment of major diseases affecting goats in urban and peri-urban fattening systems of East Shewa and West Arsi Zones, Oromia, Ethiopia","Dr. Gebawo Tibesso","Accepted with modification",""],
[463,"ATARC","Livestock","Meat","Assessment of Major Health Constraints, Associated Risk Factors and Their Impact on Productivity of Sheep and Goats Managed Under Traditional Smallholder Systems in East Shewa and West Arsi Zone, Oromia, Ethiopia","Dr. Gebawo Tibesso","Accepted with modification",""],
[464,"ATARC","Livestock","poultry","Effect of Improved Green Forage Leaves Inclusion On Egg Yolk Pigmentation and Egg Production Performance of Bovines Brown/Tetra H Layers Chickens at ATARC","Nebi Husein and Usman A","Accepted with modification",""],
[465,"ATARC","Livestock","poultry","The Effect of Layer Age on Egg Quality and Hatchability of Tetra H Layer Chicken at ATARC","Beshir Hussien Dr Gebawo T, Dr Abdel Edao","Accepted with modification",""],
[466,"ATARC","Livestock","Api","Collection and identification of Wild Fruit Tree and Shrub Species for Bee Forage Development in East Shewa and West Arsi Zones","Mekonen Wolditsadik","Accepted with modification",""],
[467,"ATARC","Livestock","Api","Characterization of honey quality in the central Rift Valley of Oromia, Ethiopia","Taye Beyene","Accepted",""],
[468,"ATARC","Livestock","Dairy","Efficacy of Dry Cow Antimicrobial and Teat Sealant Therapies on Intra-Mammary Infection Rates Across Consecutive Lactations","Dr Abdela Edao","Accepted",""],
[469,"ATARC","Livestock","Dairy","Efficacy and Validation of Strategic Macrocyclic Lactone Pour-On vs. Botanical Neem Oil (Azadirachta indica) for Pediculosis in Ethiopian Crossbred Dairy Cows","Dr Abdela Edao","Accepted",""],
[470,"ATARC","Livestock","Meat","Effects of Different Levels of Biochar Inclusion in the Dietary Rations on Growth Performance and Feed Efficiency of Arsi-Bale Sheep","Aman Gudeto","Accepted",""],
[471,"ATARC","Livestock","Dairy","Substitution of whole milk with milk replacer for growing crossbred calves at ATARC","Alemayehu Arega","Accepted",""],
[472,"ATARC","Livestock","Dairy","Effect of Feeding Different Levels of Soybean Seed Cake on Feed Intake, Milk Yield, Milk Composition and Economic Performance of Lactating Crossbred Dairy Cows","Alemayehu Arega","Accepted",""],
[473,"ATARC","Livestock","Meat","Assessment of Neonatal Lamb and Kid Mortality and their major causes in sheep and goats managed under commercial and traditional smallholder systems in East Shewa and West Arsi Zone, Oromia, Ethiopia","Dr. Gebawo Tibesso","Accepted",""],
[474,"ATARC","Livestock","Meat","Evaluation of Artificial Insemination (AI) Efficiency Response on Reproductive Performance of Arsi-Bale Goats","Aman Gudeto","Accepted",""],
[475,"ATARC","Livestock","Meat","Evaluating Pigeon Pea Leaves as a Partial Substitute for Concentrate in Rhodes Grass-Based Diets of Weaned Kids of Arsi-Bale Goats at dry season","Aman Gudeto","Accepted",""],
[476,"ATARC","Livestock","Meat","Prevalence, Risk Factors, and Etiological Identification of Major Circling Diseases in Sheep and Goats of East Shewa and West Arsi Zones","Aman Gudeto and Dr. Gebawo Tibeso","Accepted",""],
[477,"ATARC","Livestock","poultry","Evaluating locally available residue combinations as suitable bedding materials for chicken production at Adami Tulu Research Center.","Nebi H","Accepted",""],
[478,"ATARC","Livestock","poultry","Effects of Dietary Inclusion of Papaya Seed, Garlic, and Ginger as Natural Feed Additives on Growth, Feed Utilization, and Production Performance of layer chickens at ATARC","Beshir Husein and Tesfa Geleta","Accepted",""],
[479,"ATARC","Livestock","poultry","Ration formulation for commercial Tetra H layer chicken using different locally available feed ingredients at Adami Tulu Agricultural Research Center","Usman Abdulkadir and Beshir Hussein","Accepted",""],
[480,"ATARC","Livestock","poultry","Effects of replacement of maize grain with potato peel meal on egg production and quality of Tetra H chicken at on station","Usman Abdulkadir","Accepted",""],
[481,"ATARC","Livestock","poultry","Ethnobotanical Survey of Medical Plants and Other Health Management Used By Local People For Treatment and Prevention of Poultry Disease","Dr. Gebawo Tibesso","Accepted",""],
[482,"ATARC","Livestock","Api","Evaluation of sesame (Sesame indicum) L.) varieties for bee forage development","Taye Beyene","Accepted",""],
[483,"ATARC","Livestock","Api","Effect of pollen supplementary feeds on honeybees (Apis mellifera L.) colony performance and honey production","Taye Beyene","Accepted",""],
[484,"ATARC","Livestock","Api","Evaluation of Different Hive Insulation Materials for Improving Honeybee Colony Performance Under Heat Stress","Mekonen Wolditsadik","Accepted",""],
[485,"ATARC","Livestock","Api","Seasonal Prevalence of Nosema Infection and Its Relationship with Colony Strength","Mekonen Wolditsadik","Accepted",""],
[486,"ATARC","Livestock","Api","Evaluation of Locally Available Materials for Protecting Hives Against Ants","Mekonen Wolditsadik","Accepted",""],
[487,"ATARC","Livestock","Api","Effect of Honeybee Pollination on Fruit Set, Yield and Fruit Quality of Avocado (Persea americana Mill.) Under Central Rift Valley Conditions of Ethiopia","Mekonen Wolditsadik","Accepted",""],
[488,"ATARC","Livestock","Api","Evaluation of Honey Production Performance and Economic Profitability of Seasonal Migratory Beekeeping in Selected Areas of East Shewa and West Arsi Zones, Oromia, Ethiopia","Desta Abi","Accepted",""],
[489,"ATARC","Livestock","Api","Comparative Honey Production Potential Evaluation of Sinapis or Mustard Varieties in East Shewa and West Arsi Zones of Oromia Regional State, Ethiopia","Desta Abi","Accepted",""],
[490,"ATARC","Livestock","Meat","Effects of dietary biochar supplementation on growth performance, feed utilization and health status of goats under controlled feeding conditions.","Dr. Gebawo Tibesso","Accepted",""],
[491,"ATARC","Livestock","Dairy","Antimicrobial and Antioxidant Efficacy of Native Spice Formulations (Aframomum corrorima and Nigella sativa) as Natural Surface Preservatives for Raw Beef Stored under Ambient Room Temperature","Dr Abdela Edao","Rejected",""],
[492,"ATARC","Livestock","Dairy","Effects of Fresh Cactus Pear (Opuntia ficus-indica) Supplementation on Feed Intake, Nutrient Digestibility and Body Weight Change of Local Cattle","Alemayehu Arega","Rejected",""],
[493,"ATARC","Livestock","Meat","Comparative Feed Utilization Efficiency and Growth Performance of Boer, Arsi-Bale and Boer x Arsi-Bale Goats under Smallholder Feeding Systems","Ashebir Worku","Rejected",""],
[494,"ATARC","Livestock","Dairy","Validation of the FAMACHA Ocular Mucosa Anemia Chart and Body Condition Scoring (BCS) as Targeted Selective Treatment (TST) Decision Tools for Controlling Gastrointestinal Nematode Infections in Grazing Local Sheep","Dr Abdela Edao","Rejected",""],
[495,"ATARC","Livestock","Dairy","Comparative Field Evaluation of Single-Shot vs. Double-Shot Prostaglandin (PGF2alpha) Estrus Synchronization Protocols in Cattle Across Controlled On-Station and Smallholder Field Environments","Dr Abdela Edao","Rejected",""],
[496,"ATARC","Livestock","Dairy","Clinical Outcome Profiling and Pathogen Shedding Dynamics of Prophylactic Oxytetracycline and Neomycin Supplementation in Subnormally Fed Pre-Weaned Calves","Dr Abdela Edao","Rejected",""],
[497,"ATARC","Livestock","Dairy","Effects of Fresh Cactus (Opuntia ficus-indica) Feeding on Milk Yield and Composition of Lactating Crossbred Cows","Alemayehu Arega","Rejected",""],
[498,"ATARC","Livestock","Dairy","Sex sorted semen produced crossbred heifers and cows Performance Evaluation in Ethiopia","Alemayehu Arega","Rejected",""],
[499,"ATARC","Livestock","Dairy","Evaluating the first-generation crossbreds (F1 calves) of Borana and Arsi cattle breeds Feeding Manual and Automated equipment with Recommended Feeds on Calf Growth, Health, and adaptability Behavior in Adami Tulu Research Center.","Sisay Eshetu","Rejected",""],
[500,"ATARC","Livestock","Meat","Field Evaluation of Low-Cost Mash Concentrate Regimens for Youth and Female-Led Smallholder Sheep Fattening Enterprises in Mixed Crop-Livestock Systems of Mid-Highland Oromia","Genet Dadi","Rejected",""],
[501,"ATARC","Livestock","Meat","Establishing Standardized Pre-Fattening Deworming, Vaccination, and Adaptation Feeding Protocols to Reduce Early Mortality in Sheep Fattening Programs","Genet Dadi and Dr Abdela","Rejected",""],
[502,"ATARC","Livestock","Meat","Evaluation of Chemical Treatment (Urea-Lime Activation) on Lignin Degradation, In Sacco Dry, and Intake Matter Digestibility of Wheat and Teff Straw","Genet Dadi","Rejected",""],
[503,"ATARC","Livestock","Meat","Effects of Dietary Energy and Protein Levels on Nutrient Intake, Digestibility, and Body Weight Change of Arsi-Bale Sheep","Genet Dadi","Rejected",""],
[504,"ATARC","Livestock","Meat","Evaluation of Carcass Characteristics and Meat Quality of Boer and Boer x Arsi-Bale Goats under on station Condition","Ashebir Worku","Rejected",""],
[505,"ATARC","Livestock","Meat","Identification and Validation of Functional SNPs and Candidate Genes Associated with Prolificacy for Enhanced Goat Production and Productivity","Ashebir Worku","Rejected",""],
[506,"ATARC","Livestock","Meat","Determination of the Optimum Level of Boer Genetic Contribution for Improving Productivity of Arsi-Bale Goats under Central Rift Valley Conditions of Ethiopia","Ashebir Worku","Rejected",""],
[507,"ATARC","Livestock","Meat","Estimation of heterosis for growth, reproductive and survival traits in Boer x Arsi-Bale and Arsi-Bale x Boer crossbred goats","Ashebir Worku","Rejected",""],
[508,"ATARC","Livestock","Meat","Development and Evaluation of a Community-Based Breeding Program for Boer x Arsi-Bale Goats Integrating with Artificial Insemination (AI)","Ashebir Worku","Rejected",""],
[509,"ATARC","Livestock","Meat","Assessment of livestock health service delivery and its contribution to improving livestock productivity and meat production in East Shewa and West Arsi zones, Oromia, Ethiopia.","Dr. Gebawo Tibesso","Rejected",""],
[510,"ATARC","Livestock","Meat","Assessment of major meat animal health constraints and pre-slaughter handling practices and their effects on the physicochemical and microbiological quality of beef in selected municipal abattoirs in East Shewa and West Arsi Zone, Oromia, Ethiopia","Dr. Gebawo Tibesso","Rejected",""],
[511,"ATARC","Livestock","Meat","Assessment of antimicrobial usage practices, residue levels and resistance profiles of zoonotic bacterial pathogens in sheep and goats managed under commercial and traditional smallholder systems in East Shewa and West Arsi Zone, Oromia, Ethiopia","Dr. Gebawo Tibesso","Rejected",""],
[512,"ATARC","Livestock","Meat","Evaluation of mobile-based syndromic surveillance for early detection of small ruminant epidemics in East Shewa and West Arsi Zone, Oromia, Ethiopia","Dr. Gebawo Tibesso","Rejected",""],
[513,"ATARC","Livestock","Meat","Evaluation of Fresh and Frozen-Thawed Boer Goat Semen for Artificial Insemination in Arsi-Bale Does","Aman Gudeto","Rejected",""],
[514,"ATARC","Livestock","Meat","Evaluation of Artificial Insemination (AI) Efficiency Response on Reproductive Performance of Arsi-Bale Sheep in the Community-Based Breeding Program (CBBP)","Aman Gudeto","Rejected",""],
[515,"ATARC","Livestock","Meat","Evaluation of Growth, Reproductive Performance, Survival and Adaptability of Crossed Boer x Arsi-Bale Goats","Aman Gudeto","Rejected",""],
[516,"ATARC","Livestock","poultry","Evaluation of egg production and Survival of commercial chicken under Scavenging and intensive management in BARC","Tesfa G & Usman A/Q","Rejected",""],
[517,"ATARC","Livestock","poultry","Evaluation of reproductive performance and egg productivity of dual-purpose chicken in selected districts of Horro Guduru Zone","Tesfa Geleta and Nebi Husein","Rejected",""],
[518,"ATARC","Livestock","poultry","Effect of management on Growth performance and egg yield of commercial Chicken in selected districts of West Shoa Zone","Nebi H","Rejected",""],
[519,"ATARC","Livestock","poultry","Evaluation of growth, survival, and productive performance of commercial tetra-H Pullets under semi-intensive and backyard management systems in the Mid Rift Valley area","Nebi H","Rejected",""],
[520,"ATARC","Livestock","poultry","Evaluation of Optimum Biochar Application Rates for Pathogen Reduction and Layer Chicken Production Performance at ATARC","Nebi H","Rejected",""],
[521,"ATARC","Livestock","poultry","Partial Replacement of Soybean Meal with Brewery Spent Grain in Layer Chicken Diets at ATARC","Beshir H","Rejected",""],
[522,"ATARC","Livestock","poultry","Effect of Substituting Soybean Meal with Cowpea (Vigna unguiculata) Supplemented on Growth Performances and Carcass Characteristics of Cockerel Tetra-H chicken","Usman Abdulkadir","Rejected",""],
[523,"ATARC","Livestock","poultry","Identification of Ectoparasites Infesting Domestic Chickens and Evaluation of Control Practices across Production Systems in East Shewa and West Arsi Zones, Ethiopia","Dr. Gebawo Tibesso","Rejected",""],
[524,"ATARC","Livestock","poultry","Evaluation of improved breeds chicks brooding system in urban and Peri-urban areas in East Shewa and West Arsi zones","Dr. Gebawo Tibesso","Rejected",""],
[525,"ATARC","Livestock","poultry","Evaluation of effect of earthworm (Eisenia foetida) meal on growth performance, feed utilization, hematology, intestinal microbiota, meat quality and survival of Tetra H Chicken.","Dr. Gebawo Tibesso","Rejected",""],
[526,"ATARC","Livestock","Api","Development of Climate-Smart Honeybee Production Technologies for the Semi-Arid Agro-Ecology of the Central Rift Valley of Ethiopia","Mekonen Wolditsadik","Rejected",""],
[527,"ATARC","Livestock","Api","Development of an Early-Warning System for Honeybee Colony Absconding Using Weather and Colony Data","Mekonen Wolditsadik","Rejected",""],
[528,"ATARC","Livestock","Api","Evaluation of Biological Control Methods Against Wax Moth (Galleria mellonella) in Honeybee Colonies","Mekonen Wolditsadik","Rejected",""],
[529,"ATARC","Livestock","Api","Selection of Honeybee Colonies for Low Absconding Behaviour, High Honey Yield and Disease Resistance in east shewa and West Arsi","Mekonen Wolditsadik","Rejected",""],
[530,"ATARC","Livestock","Api","Use of GIS and Remote Sensing Technologies for Monitoring Honeybee Floral Phenology under Recurrent Climate Variability in East Shewa and West Arsi Zones of Oromia, Ethiopia","Desta Abi","Rejected",""],
[531,"ATARC","Livestock","Api","Evaluation of Honey Production and Colony Population Dynamics of Apis mellifera bandasii in Response to Different Volumes of Modern Hives in East Shewa and West Arsi Zones of Oromia, Ethiopia","Desta Abi","Rejected",""],
[532,"ATARC","Livestock","Api","Development of Regression Models for Estimating Honey Yield and Predicting Optimum Honey Harvest Time in Eucalyptus-Dominated Areas of East Shewa and West Arsi Zones, Oromia, Ethiopia","Desta Abi","Rejected",""],
[533,"ATARC","Livestock","Api","Farm-Based Evaluation and Demonstration of Honeybee (Apis mellifera L.) Pollination on Red Onion (Allium cepa L.) Seed Yield, Seed Quality and Economic Parameters in Adami Tulu Jido Kombolcha District, East Shewa, Oromia, Ethiopia","Desta Abi","Rejected",""],
[534,"ATARC","Livestock","Meat","Evaluation of Locally Available Feed Resources for Improving Growth Performance, Feed Conversion Efficiency, Carcass Characteristics and Economic Returns in Fattening Pigs to Support Ethiopia's Pork Development Initiative","Ashebir Worku","Rejected",""],
[535,"ATARC","Livestock","Api","Climate-Smart Integration of Apiculture with Agroforestry for Sustainable Rural Livelihoods in west Arsi and east shewa","Mekonen Wolditsadik","Rejected",""],
[536,"ATARC","Livestock","Feeds","Collection, Characterization and adaptation of Spineless Cactus Ecotypes from the Rift Valley of Oromia, Ethiopia","Meseret Tilahun","Accepted",""],
[537,"ATARC","Livestock","Feeds","Evaluation of Herbage Yield Accumulation and Nutritive Value of Brachiaria (Brachiaria spp.) Integrated with Alfalfa (Medicago sativa L.) in West Arsi Zone","Meseret Tilahun","Accepted",""],
[538,"ATARC","Livestock","Feeds","Sesbania sesban Preliminary yield trial in the lowland agroecology of East Shewa Zone","Fikre Dereba","Accepted",""],
[539,"ATARC","Livestock","Feeds","Lablab Preliminary yield trial in the lowland agroecology of East Shewa Zone","Fikre Dereba","Accepted",""],
[540,"ATARC","Livestock","Feeds","Oat Variety verification trial in the Lowland agroecology of East Shewa Zone","Fikre Dereba","Accepted",""],
[541,"ATARC","Livestock","Feeds","Rhodes grass adaptation trial in the Lowland Agroecology of East Shewa Zone","Fikre Dereba","Accepted",""],
[542,"ATARC","Livestock","Feeds","Cowpea Nursery Observation Trial in the Lowland agroecology of East Shewa Zone","Fikre Dereba","Accepted",""],
[543,"ATARC","Livestock","Feeds","Annual Ryegrass Nursery Observation Trial in the Highland agroecology of West Arsi Zone","Fikre Dereba","Accepted",""],
[544,"ATARC","Livestock","Feeds","Setaria Sphacelata Nursery Observation Trial at Adami Tulu Agricultural Research Center","Daniel wana","Accepted",""],
[545,"ATARC","Livestock","Feeds","Panicum coloratum grass Nursery Observation trial","Dawit Abate","Accepted",""],
[546,"ATARC","Livestock","Feeds","Evaluation of vetch varieties potentials for Pasture land improvements at mid and high land of west Arsi zone","Sub-component focal person: Meseret T","Accepted",""],
[547,"ATARC","Livestock","Feeds","Evaluation of space, harvesting stage and frequency of Guatemala grass cultivar on biomass and nutritive value at ATARC","Meseret Tilahun","Rejected",""],
[548,"ATARC","Livestock","Feeds","Oat adaptation trial in the Midland Agroecology of East Shewa Zone","Fikre Dereba","Rejected",""],
[549,"ATARC","Livestock","Feeds","Adaptation Trial of Amaranthus caudatus Varieties for biomass production and nutritive value as animal feed at west Arsi Zone","Daniel wana","Rejected",""],
[550,"ATARC","Livestock","Feeds","Effect of Seeding Rate and row Spacing on dry Matter Yield, seed yield and Forage Quality of Sweet Lupin (Lupinus angustifolius L.)","Dawit Abate","Rejected",""],
[551,"ATARC","Livestock","Feeds","Evaluating the Silage Quality and Shelf Life of Cactus Pear (Opuntia ficus-indica) Ensilaged with Differing Additives","Dawit Abate","Rejected",""],
[552,"ATARC","Livestock","Feeds","Effects of white fungi rot on crop residues treatment for quality improvements at east shewa and west arsi zone","NA","Rejected",""],
[553,"ATARC","Livestock","Feeds","Evaluation of Finger Millet (Eleusine coracana) varieties for dual purpose production (grain and fodder) at lowland agro-ecology of selected districts of East Shewa and West Arsi Zones of Oromia","Dawit Abate","Pended",""],
[554,"BARC","Livestock","Meat","Performance Evaluation of Pure Boar Goat and their crosses at BARC","Birmaduma Gadisa","Accepted with modification",""],
[555,"BARC","Livestock","Meat","Population Dynamics, Typology, Phenotypic Characteristics, and Production Systems of Indigenous Goat (Capra hircus) in Western Oromia. Ethiopia","Tusa Gemechu","Accepted with modification",""],
[556,"BARC","Livestock","Meat","Evaluation of alternative beef cattle ration formulation from locally available feed resources in West Shao and East Wollega zones","Birmaduma Gadisa","Accepted",""],
[557,"BARC","Livestock","poultry","Assessment of Major Health Constraints, Disease Occurrence, and Associated Risk Factors in Village Poultry Production Systems of Selected Districts of East Shewa and West Arsi Zones, Oromia, Ethiopia","Milkessa Gelana","Accepted",""],
[558,"BARC","Livestock","poultry","Evaluation of Farm Biosecurity Practices and Compliance Levels and Their Correlation with Major Disease Outbreaks in Selected Intensive and Semi-Intensive Poultry Farms in East Shewa and West Arsi Zones, Ethiopia.","Feyera Bodena","Accepted",""],
[559,"BARC","Livestock","poultry","Assessment of Antimicrobial and Anthelminthic Resistance Profiles and Public Health Risks of important Bacterial and Gastrointestinal Parasites of Poultry in Selected Commercial and Smallholder Farms in East Shawa and West Arsi Zones, Oromia, Ethiopia","Feyera Bodena","Accepted",""],
[560,"BARC","Livestock","Meat","Effect of Initial Fattening Age and Different Concentrate Mixtures on Feed Intake and Growth Performance of Horro Bulls","Tusa Gemechu","Conditionally Accepted",""],
[561,"BARC","Livestock","Meat","Adaptation trial of different pig breeds in BARC","Birmaduma Gadisa","Rejected",""],
[562,"BARC","Livestock","Meat","Genetic selection of indigenous goats for improved growth and reproductive performance through an open nucleus breeding scheme","Tusa Gemechu","Rejected",""],
[563,"BARC","Livestock","Meat","Performance Evaluation of Boer x Indigenous Goat Crosses for Genetic Improvement of Indigenous Goats for Meat Production","Tusa Gemechu","Rejected",""],
[564,"BARC","Livestock","Meat","Comparative Evaluation of Progesterone Vaginal Sponge and PGF2alpha Injection Protocols for Estrus Synchronization, Artificial Insemination, and Reproductive Performance in Indigenous Goats","Tusa Gemechu","Rejected",""],
[565,"BARC","Livestock","poultry","Evaluation of Activated Charcoal-Supplementation in Drinking Water on Growth Performance, Physiological Responses and Health Parameters of Tetra H.","Feyera Bodena","Rejected",""],
[566,"BARC","Livestock","Api","Determining the Optimum Sugar Syrup Amount and Feeding Frequency to Enhance Colony Performance, Honey Production, and Profitability of Apis mellifera bandasii in Western Oromia, Ethiopia.","Amsalu Arega","Accepted",""],
[567,"BARC","Livestock","Api","Determining the Optimum Colony Inspection Frequency for Improving Colony Strength, Productivity, and Honey Yield of Apis mellifera bandasii in Western Oromia, Ethiopia","Amsalu Arega","Accepted",""],
[568,"BARC","Livestock","Api","Development and Validation of a Multi-Trait Honeybee Breeding and Selection System for Genetic Improvement, Climate Resilience and Sustainable Productivity of Apis mellifera in Western Oromia, Ethiopia","Amsalu Arega","Rejected",""],
[569,"BARC","Livestock","Api","Evaluation of Individual Grass Mat Hive Roof Shade for Mitigating Heat Stress and Improving the Performance of Apis mellifera bandasii Colonies in Western Oromia, Ethiopia","Amsalu Arega","Rejected",""],
[570,"BARC","Livestock","Api","On-Station Adaptation, Survival, and Colony Performance Evaluation of Stingless Bee (Meliponula Beccarii) Under Bako Altitude Western Oromia, Ethiopia","Amsalu Arega","Rejected",""],
[571,"BARC","Livestock","Feeds","Evaluation of Selected Vetch Varieties Intercropped with Panicum Coleratum for Herbage Dry Matter Yield and Quality at Bako, Western Oromia","Wakgari Keba","Accepted",""],
[572,"BARC","Livestock","Feeds","Evaluation of Harvesting Stages and Cutting Intervals of Sweet Potato as Food-Feed Production Strategy under Bako Conditions, West Oromia","Wakgari Keba","Accepted",""],
[573,"BARC","Livestock","Feeds","Leucaena (Leucaena leucocephala) Observation Nursery at Bako","Mekonnen Diribsa","Accepted",""],
[574,"BARC","Livestock","Feeds","Buffel grass (Cenchrus ciliaris) Observation Nursery at Bako","Mekonnen Diribsa","Accepted",""],
[575,"BARC","Livestock","Feeds","Panicum (Panicum antidotale) Observation Nursery at Bako","Mekonnen Diribsa","Accepted",""],
[576,"BARC","Livestock","Feeds","Dolichos Lablab (Lablab purpureus) Observation Nursery at Bako","Mekonnen Diribsa","Accepted",""],
[577,"BARC","Livestock","Feeds","Common Vetch (Vicia sativa L.) Adaptation Trial Humid Mid-Altitudes and highland areas of Western Oromia","Mekonnen Diribsa","Accepted",""],
[578,"BARC","Livestock","Feeds","Cowpea (Vigna unguiculata L.) Preliminary Variety Trial at Bako","Mekonnen Diribsa","Accepted",""],
[579,"BARC","Livestock","Feeds","Alfalfa (Medicago sativa L.) Genotypes Preliminary Yield Trial at Bako","Mekonnen Diribsa","Accepted",""],
[580,"BARC","Livestock","Feeds","Setaria Grass (Setaria sphacelata) Genotypes Preliminary Variety","Mekonnen Diribsa","Accepted",""],
[581,"BARC","Livestock","Feeds","Centrosema Genotypes Variety Verification Trial (VVT)","Mekonnen Diribsa","Accepted",""],
[582,"BARC","Livestock","Feeds","Rhodes grass adaptation Trail (Transferred from FSRP CNs)","Researcher","Accepted",""],
[583,"BARC","Livestock","Dairy","On-Farm Evaluation of Artificial Insemination Efficiency, Estrus Detection, and Conception Rate in Holstein Friesian-Crossbred Dairy Cattle under Urban and Peri-Urban Farming Systems in Western Oromia, Ethiopia","Teshome Werku and Tesafye Mersha","Accepted with modification",""],
[584,"BARC","Livestock","Dairy","Study of Calf Health and Management Problems in Selected Districts of Western Oromia, Ethiopia","Tesfaye Mersha","Accepted with modification",""],
[585,"BARC","Livestock","Dairy","Epidemiological Study of Non Infectious Metabolic Diseases of Dairy Cattle in Urban and Peri-Urban Dairy Farms of Western Oromia, Ethiopia","Tesfaye Mersha","Accepted with modification",""],
[586,"BARC","Livestock","Dairy","Study on Bovine Trypanosomiasis & Identification of Fly Density in Tsetse Belt Areas of Western Oromia","Tesfaye Mersha","Accepted",""],
[587,"BARC","Livestock","Dairy","Study on Sero-Prevalence and Associated Risk Factors of Foot and Mouth Disease (FMD) in Selected Districts of Western Oromia, Ethiopia","Tesfaye Mersha","Accepted",""],
[588,"BARC","Livestock","Dairy","Evaluation of Adaptability and Milk Production Performance of Ayrshire x Horro Crossbred Cattle under On-Station and On-Farm Conditions in Western Ethiopia","Teshome Werku and Tesafye Mersha","Rejected",""],
[589,"BARC","Livestock","Dairy","Evaluation of Complete Feed Formulations for Improving Growth Performance and Reducing Age at Puberty in Horro Heifers under On-Station Conditions in Western Ethiopia","Teshome Werku and Tesafye Mersha","Rejected",""],
[590,"BARC","Livestock","Dairy","Epidemiology Study of Bovine Babesiosis in Selected Districts of Western Oromia, Ethiopia","Tesfaye Mersha","Rejected",""],
[591,"BARC","Livestock","Dairy","Assessment of Factors Affecting Production & Productivity of Indigenous Horro Cattles Breed in Selected Districts of Rural Areas of Western Oromia, Ethiopia","Tesfaye Mersha","Rejected",""],
[592,"BARC","Livestock","Dairy","Evaluation of Horro Bull Age as a Selection Criterion Based on Fertility and Conception Rate under Natural Mating in an On-Station Herd in Western Ethiopia","Teshome Werku and Tesafye Mersha","Rejected",""],
[593,"BARC","Livestock","Dairy","Genetic Improvement of Dairy Cattle through Sexed Semen Artificial Insemination, Evaluation and Farmer Adoption in urban and per urban dairy farms of Western Oromia, Ethiopia","Tesfaye Mersha","Rejected",""],
[594,"Bedele","Livestock","Feeds","Cowpea Regional Variety Trial (RVT) in Buno Bedele and Ili Aba Bor Zones, South Western Oromia, Ethiopia","Muleta Debela","Accepted",""],
[595,"Bedele","Livestock","Feeds","Lablab (Lablab purpureus) Observation Nursery at Buno Bedele Zone, South Western Oromia, Ethiopia","Muleta Debela","Accepted",""],
[596,"Bedele","Livestock","Feeds","Mission grass (Pennisetum polystachion (L.) Schult) Variety Adaptation Trial in Buno Bedele Zone, South Western Oromia, Ethiopia","Muleta Debela","Accepted",""],
[597,"Bedele","Livestock","Feeds","Performance Evaluation of Sesbania (Sesbania sesban (L.) Varieties at Buno Bedele Zone, Southwestern Oromia, Ethiopia","Muleta Debela","Accepted",""],
[598,"Bedele","Livestock","Api","Performance Evaluation of Selected Perennial Shrubs bee forage In Buno Bedele Zone, south western Oromia","Aberu Bane","Accepted",""],
[599,"Bedele","Livestock","Api","Evaluation of Physico-chemical properties and Quality standardization of honey produced in Selected Districts of in Buno Bedele and Ilu Aba Bor Zones, South western Oromia","Aberu Bane","Rejected",""],
[600,"Bedele","Livestock","Api","Assessment of Perennial bee forage potential to Enhances Honey Production and Ecosystem Resilience in Buno Bedele and Ilu Aba Bor zones, south western Ethiopia","Aberu Bane","Rejected",""],
[601,"Bore","Livestock","Feeds","Brachiaria Brithanta Regional Variety Trial (RVT) in the Midland of Guji zone","Teshale Jabessa","Accepted",""],
[602,"Bore","Livestock","Feeds","Common Vetch (Vicia sativa) Regional Variety Trial (RVT) in the highlands of Guji zone","Teshale Jabessa","Accepted",""],
[603,"Bore","Livestock","Feeds","Buffel (Centchrus Cilaries) Regional Variety Trial (RVT) in the midland of Guji zone","Teshale Jabessa","Accepted",""],
[604,"Bore","Livestock","Feeds","PVT of Desmodium accession at midland area of Guji zone, southern Oromia","Ketema Bekele","Accepted",""],
[605,"Bore","Livestock","Feeds","Guinea grass (Megathyrsus maximus) Nursery Observation in Midland of Guji zone","Teshale Jabessa","Accepted",""],
[606,"Bore","Livestock","Feeds","Nursery Observation of Alfalfa in the Highland area of Guji Zone, Southern Oromia","Ketema Bekele","Accepted",""],
[607,"Bore","Livestock","Feeds","Nursery Observation of oat in the midland area of Guji Zone, Southern Oromia","Ketema Bekele","Accepted",""],
[608,"Bore","Livestock","Feeds","Nursery Observation of panicum grass genotypes at midland parts of Guji Zone, Southern Oromia","Ketema Bekele","Accepted",""],
[609,"Bore","Livestock","Feeds","Optimizing Spatial Arrangements for Biomass Yield and Forage Quality of Oat and Sweet Lupin Intercropping System in the highland area of Guji Zone","Ketema Bekele","Accepted",""],
[610,"Bore","Livestock","Feeds","Nursery Observation of hairy vetch in the Highland area of Guji Zone, Southern Oromia","Ketema Bekele","Accepted",""],
[611,"Bore","Livestock","Feeds","Rhodes grass varieties adaptation trial (Transferred from FSRP)","Teshale Jabessa","Accepted",""],
[612,"Bore","Livestock","Api","Assessment, Collection and Performance Evaluation of Potential Herbaceous bee plants at Midland of Guji Zone of Oromia, Ethiopia","Mekonen Bayisa","Accepted",""],
[613,"Bore","Livestock","Api","Determining honey production potential and Colony Carrying Capacity of Wocoo Solooloo Forest in Ardaa Jilaa Me'ee Bokkoo District of Gujii Zone, Oromia Region, Ethiopia","Mekonen Bayisa","Accepted",""],
[614,"Bore","Livestock","Feeds","Collection and Evaluation of Indigenous Perennial Grasses spp. for dry matter yield and nutritive value in midland agro-ecologies of Guji and West Guji Zone, Southern Oromia","Teshale Jabessa","Rejected",""],
[615,"Bore","Livestock","Feeds","Stylosanthes guianensis Nursery Observation at Midland of Southern Guji Zone","Teshale Jabessa","Rejected",""],
[616,"Bore","Livestock","Feeds","Centerosoma Nursery Observation in Midland of Guji zone Southern Oromia","Teshale Jabessa","Rejected",""],
[617,"Bore","Livestock","Feeds","Fodder oat (Avena Sativa) adaptation in highland and midland agro-ecologies of West Guji zone","Teshale Jabessa","Rejected",""],
[618,"Bore","Livestock","Feeds","Determination of Optimum Seed Rate and Inter Row Spacing on Dry matter yield and nutritional quality of newly released Dolichos Lablab in midland of Guji zone","Teshale Jabessa","Rejected",""],
[619,"Bore","Livestock","Feeds","Determination of optimum Seed Rate and Inter Row Spacing on dry matter yield and nutritional quality of newly released Oat at highland of Guji Zone","Teshale Jabessa","Rejected",""],
[620,"Bore","Livestock","Feeds","Performance Evaluation of Different Perennial Grass Species for Biomass Yield and Chemical Composition under Rain-Fed Conditions in the Highlands of Guji Zone,","Ketema Bekele","Rejected",""],
[621,"Bore","Livestock","Feeds","Effect of Inorganic Fertilizer Level and Harvesting Date on Yield, Nutritive Value, and In Vitro Gas Production of Desho Grass in Guji Zone","Ketema Bekele","Rejected",""],
[622,"Bore","Livestock","Feeds","Nursery Observation of Setaria grass genotypes at midland parts of Guji Zone, Southern Oromia","Ketema Bekele","Rejected",""],
[623,"Bore","Livestock","Api","Performance Evaluation of (Waakkaa) at Highland of Guji Zone of Oromia, Ethiopia","Mekonen Bayisa","Rejected",""],
[624,"Bore","Livestock","Api","Evaluation of Physico-chemical Properties of Stingless bees' Honey in Gujii and West Gujii Zones of Oromia, Ethiopia","Mekonen Bayisa","Rejected",""],
[625,"Fedis","Livestock","Feeds","Rhodes grass Adaptation in East Hararghe zone, Oromia","Worku Bekuma","Accepted",""],
[626,"Fedis","Livestock","Feeds","Nursery Observation of Tall fescue (Festuca arundinacea) in lowlands of East Hararghe Zone","Tolera Fikadu","Accepted",""],
[627,"Fedis","Livestock","Feeds","Nursery Observation of Guinea grass (Megathyrsus maximus) in lowlands of East Hararghe Zone","Melese Furgasa","Accepted",""],
[628,"Fedis","Livestock","Feeds","Effects of intercropping Lablab purpureus (Foyesa variety) with Selected Sorghum Varieties on their Agronomic Performance in the East Hararghe Zone of Oromia","Melese Furgasa","Accepted",""],
[629,"Fedis","Livestock","Feeds","Sesbania Macrantha Observation Nursery at Midlands of East Hararghe zone","Abdi Misgana","Accepted",""],
[630,"Fedis","Livestock","Feeds","Preliminary yield trial of Lablab","NA","Accepted",""],
[631,"Fedis","Livestock","Feeds","Greenleaf desmodium (Desmodium intortum) Variety Verification Trial","Tolera Fikadu","Accepted",""],
[632,"Fedis","Livestock","Feeds","Buffel grass Variety Verification Trial","Worku Bekuma","Accepted",""],
[633,"Fedis","Livestock","Feeds","Centrosema (Centrosema molle) Preliminary Yield trial","Worku Bekuma","Accepted",""],
[634,"Fedis","Livestock","Feeds","Nursery Observation of Leucaena leucocephala at Lowlands of Eastern Hararghe Zone","Tolera Fikadu","Accepted",""],
[635,"Fedis","Livestock","Feeds","Regional variety trial of Setaria sphacelata","NA","Accepted",""],
[636,"Fedis","Livestock","Feeds","Barrel Medic (Medicago truncatula) Observation Nursery","Worku Bekuma","Rejected",""],
[637,"Fedis","Livestock","Feeds","Evaluation of different Spacing and Irrigation Methods on Napier grass (Hararghe variety) Biomass Yield and Yield related Parameters","Worku Bekuma","Rejected",""],
[638,"Fedis","Livestock","Feeds","Nursery Observation Trial of Vigna vexillata for East Hararghe Zone, Oromia","Melese Furgasa","Rejected",""],
[639,"Fedis","Livestock","Feeds","Nursery Observation of Gliricidia sepium for East Hararghe Zone","Melese Furgasa","Rejected",""],
[640,"Fedis","Livestock","Feeds","Assessment of Camel Feed resource Characterization and feeding practices in East Hararghe zone, Oromia, Ethiopia","Abdi Misgana","Rejected",""],
[641,"Fedis","Livestock","Api","Performance evaluation and Honey production potential of Black Cumin (Nigella sativa) Varities for Bee forage development in East Hararghe zone","Ifa Tesfaye","Accepted with modification",""],
[642,"Fedis","Livestock","Api","Performance Evaluation of Stingless Bee (Meliponula Beccarii) Using Pot Hives in East Hararghe Zone, Oromia, Ethiopia","Belete Fikadu","Accepted",""],
[643,"Fedis","Livestock","Api","Bee Forage Composition, Diversity and Associated Beekeeping Practices in Green Legacy Initiative Sites of East Hararghe Zone, Oromia, Ethiopia","Belete Fikadu","Accepted",""],
[644,"Fedis","Livestock","Api","Performance evaluation of Sunflower varieties for beekeeping development in East Hararghe Zone","Ifa Tesfaye","Accepted",""],
[645,"Fedis","Livestock","Api","Performance Evaluation of Alfalfa (Medicago sativa) Varieties for Bee Forage in East Hararghe Zone, Oromia, Ethiopia","Belete Fikadu","Rejected",""],
[646,"Fedis","Livestock","Api","Assessment of Beekeepers' Knowledge and Practices Regarding Pesticide and Herbicide Use and Its Effects on Honeybees in East Hararghe Zone","Belete Fikadu and Ifa Tesfaye","Rejected",""],
[647,"Fedis","Livestock","Api","Assessing the Effectiveness of Beekeeping Development Initiatives on Honeybee Productivity in Apiaries of Farmer Participating Cooperatives in East Hararghe Zone","Belete Fikadu","Rejected",""],
[648,"Fedis","Livestock","Api","Performance evaluation of herbaceous bee forage species under irrigation system in East Hararghe Zone of Oromia","Ifa Tesfaye","Rejected",""],
[649,"Fedis","Livestock","Api","Performance Evaluation and Honey Production Potential of Improved Vetch Species for Bee Forage Development in East Hararghe Zone of Oromia, Ethiopia","Ifa Tesfaye","Rejected",""],
[650,"Fitche","Livestock","Feeds","Brachiaria brizantha preliminary variety trials","Zinash A. & Dagmawi Y","Accepted",""],
[651,"Fitche","Livestock","Feeds","Setaria grass (Setariasphacelata) Preliminary Variety Trials","Zinash A. & Dagmawi Y.","Accepted",""],
[652,"Fitche","Livestock","Feeds","Rhodes Grass (Chloris gayana) Preliminary Variety Trials","Dagmawi Y.& Zinash A.","Accepted",""],
[653,"Fitche","Livestock","Feeds","Fodder Oat Variety Verification Trials","Fira'ol L., Zinash A. and Dagmawi Y","Accepted",""],
[654,"Fitche","Livestock","Feeds","Common Vetch Variety Verification Trials","Fira'ol L., Zinash A. and Dagmawi Y","Accepted",""],
[655,"Fishery","Livestock","aqua","Design, Performance Evaluation and IoT Optimization of Solar-Powered Smart Aeration and Automated Water-Quality Diagnostics for Media-Based Aquaponics","Dr Mathewos Hailu","Accepted",""],
[656,"Fishery","Livestock","aqua","Optimization of Sperm Cryopreservation and Hormone Induced Off Season Spawning Protocols for Cyprinus carpio and Clarias gariepinus","Dr Mathewos Hailu","Accepted",""],
[657,"Fishery","Livestock","aqua","Evaluation of African catfish (Clarias gariepinus) spawning performance in grass covered ponds","Samuel Ameja and Habtamu Duressa","Accepted",""],
[658,"Fishery","Livestock","aqua","Comparative study on growth performance between Chamo, and Alwero Nile tilapia strains and their crosses for aquaculture production","Derribew Hailu, Habtamu Duressa","Accepted",""],
[659,"Fishery","Livestock","aqua","Assessment of Aquaculture suitability and potential of irrigation schemes associated with the Arjo-Didessa reservoir","Samuel Ameja","Accepted",""],
[660,"Fishery","Livestock","aqua","Evaluation of brewers spent grain as a feed ingredient for growth performance of Nile tilapia (O. niloticus) on station /BFOALRC","Samuel Ameja and Dr. Girma Chalchisa","Accepted",""],
[661,"Fishery","Livestock","aqua","Isolation, Identification and Thermal Tolerance Profiling of Wild Brachionus Strains for Climate-Resilient Larviculture","Dr Mathewos Hailu","Accepted",""],
[662,"Fishery","Livestock","aqua","Optimization of Population Growth and Nutritional Quality of Native Daphnia Strains Fed Mono and Mixed Microalgal Diets for Hatchery Fingerling Production","Dr Mathewos Hailu","Accepted",""],
[663,"Fishery","Livestock","aqua","Comparative Evaluation of Common Carp (Cyprinus carpio) growth under Monoculture and Polyculture Systems in Earthen Ponds at Welmera District, West Shewa, Oromia, Ethiopia(Transferred from FSRP)","Samuel Ameja","Accepted",""],
[664,"Fishery","Livestock","capture","Earth-Observation and Hydrological Niche Modeling of Climate-Induced Habitat Change in Endemic Labeobarbus Populations","Dr Mathewos Hailu","Accepted",""],
[665,"Fishery","Livestock","capture","Study on Limnology of Arjo Dhidhesa reservoir","Getachew Senbete","Accepted",""],
[666,"Fishery","Livestock","capture","Introduction and Adaptability study of Rainbow trout on lakes Wonchi and Dendi, West Shawa Zone, Oromia","Getachew Senbete","Accepted",""],
[667,"Fishery","Livestock","capture","Stocking Density Calibration, and Harvest Yield Prediction for Small Irrigation Reservoirs in Jimma zone, Oromia, Ethiopia","Samuel Ameja","Accepted",""],
[668,"Fishery","Livestock","capture","Stocking Density Calibration, and Harvest Yield Prediction for Small Irrigation Reservoirs in western Harergae","Habtamu Duressa","Accepted",""],
[669,"Fishery","Livestock","capture","Assessment of Introduced Fish and Production Potential of Berrak and Hadha Reservoirs, North Shewa Zone, Oromia, Ethiopia","Derribew Hailu","Accepted",""],
[670,"Fishery","Livestock","capture","Reproductive Biology, Population Dynamics and Gear Selectivity of Labeobarbus intermedius in Arjo-Dedessa Reservoir","Dr Mathewos Hailu","Accepted",""],
[671,"Fishery","Livestock","capture","Assessment of histamine level in commercially important fish species harvested from Central Rift Valley Lakes of Ethiopia","Dr. Alemu Lema","Accepted",""],
[672,"Fishery","Livestock","capture","Proximate composition and minerals content of Labeobarbus intermidus harvested from newly impounded Katta Dibbe and Arjo-Didessa reservoirs, Oromia","Dr. Alemu Lema","Accepted",""],
[673,"Fishery","Livestock","capture","Evaluation of proximate composition and mineral contents of fish roe","Nura Tuma","Accepted",""],
[674,"Fishery","Livestock","aqua","Assessment of Fish Culture Suitability in Irrigation Schemes of Western Hararghe","Habtamu Duressa","Rejected",""],
[675,"Fishery","Livestock","capture","Assessment of Limnological Parameters of Aegen Reservoirs, Jimma, Oromia, Ethiopia.","Samuel Ameja","Rejected",""],
[676,"Fishery","Livestock","capture","Assessment of Limnological Parameters of Reservoirs in West Hararghe Zone, Ethiopia","Samuel Ameja","Rejected",""],
[677,"Fishery","Livestock","capture","Limnological Assessment of Berrak and Hadha Reservoirs, Located in Aleltu and Kimbibit Districts of North Shewa Zone","Derribew Hailu","Rejected",""],
[678,"Fishery","Livestock","capture","Quantitative Assessment of Water-Level Drawdown and Water-Hyacinth Coverage on Reservoir Limnology and Fisheries Yield Capacity","Dr Mathewos Hailu","Rejected",""],
[679,"Harosabu","Livestock","Api","Comparative study of proximate composition and antioxidant activities of beehive products","Lammiinbon Abata","Accepted with modification",""],
[680,"Harosabu","Livestock","Api","Assessment of Beekeeping Practices (Absconding, Bee Forage and Bee Diseases and Pests) in West Wollega And Kellem Wollega Zones","Lammiinbon Abata","Rejected",""],
[681,"HBRC","Livestock","Api","Comparative evaluation of seasonal honey bee colony management for sustainable honey production","Tolera Kumsa and Zewdu Ararso","Accepted with modification",""],
[682,"HBRC","Livestock","Api","Assessing the impact of herbicides application on abundance and diversity of herbaceous bee forage weeds in central of Oromia","Admassu Addi","Accepted",""],
[683,"HBRC","Livestock","Api","Performance evaluation of honey Production potential of Black cumin (Nigella sativa) varieties for bee forage development in West Shoa zone","Admassu Addi","Accepted",""],
[684,"HBRC","Livestock","Api","Predatory behavior and nesting habitats of yellow wasp (Vaspidae), the common enemy of stingless bee (Meliponula beccarii)","Alemayehu Gela and Zewdu Araraso","Accepted",""],
[685,"HBRC","Livestock","Api","Control of Ants (Dorylus spp.) using indigenous and local beekeeper's practices","Etenesh Mekonnen","Accepted",""],
[686,"HBRC","Livestock","Api","Prevalence and infestation of Nosema and Amoeba, honeybee diseases in Central Highlands of West Shewa Zone","Etenesh Mekonnen and Dr. Alemayehu G","Accepted",""],
[687,"HBRC","Livestock","Api","Developing and Evaluation of Circular Mesh Excluder of Yellow Wasp for Protection of Native Stingless Bee (Meliponula Beccari) ( fromFSRP)","Alemayehu Gela and Zewdu Araraso","Accepted",""],
[688,"HBRC","Livestock","Api","Comparative study of honeybee queens reared with the queen right and queenless method","Shimu Debela","Accepted",""],
[689,"HBRC","Livestock","Api","Preparation and evaluation of natural beeswax queen cell cup for honeybee queen rearing","Shimu Debela","Accepted",""],
[690,"HBRC","Livestock","Api","Evaluating starter strip in producing centrifugable honey combs through different hive supering in beekeeping potential areas of Oromia","Tolera Kumsa, Kibebew Wakjira and Shimu Debela","Accepted",""],
[691,"HBRC","Livestock","Api","Investigating factors affecting honeybee (Apis mellifera) productivity and absconding in apiaries of Holeta Bee Research Center","Kibebew Wakjira and Shimu Debela","Accepted",""],
[692,"HBRC","Livestock","Api","Supplementary Feeding Trial for Stingless Bees (Meliponula beccarii) during the dearth period","Melaku B. Dheressa K. and Alemayehu G.","Accepted",""],
[693,"HBRC","Livestock","Api","Evaluating stingless bee (Meliponula beccarii) colony multiplication using splitting method","Zewdu Ararso and Shimu Debela","Accepted",""],
[694,"HBRC","Livestock","Api","Development and Evaluation of a queen excluder-based hopper type queen separator for dequeening of defensive local honeybee colonies","Zewdu Ararso and Galana Fufi","Accepted",""],
[695,"HBRC","Livestock","Api","Assessment of Bee Pollen Production Potential in West and south West Shoa zones of Oromia","Teferi Damto and Dheressa Kebeba","Accepted",""],
[696,"HBRC","Livestock","Api","Assessment of Propolis Production Potential in West Shoa Zone of Oromia","Teferi Damto and Dheressa Kebeba","Accepted",""],
[697,"HBRC","Livestock","Api","Adaption and performance of Melilotus albus for dry season bee forage in Walmera district","Admassu Addi","Rejected",""],
[698,"HBRC","Livestock","Api","Assessment of honey Production Potential and mapping of monofloral honey in major honey production areas of Oromia","Admassu Addi and Dherssa Kababa","Rejected",""],
[699,"HBRC","Livestock","Api","Control of wax moth (Galleria mellonela) using honeybee pollen extract","Alemayehu Gela and Dheressa Kebebe","Rejected",""],
[700,"HBRC","Livestock","Api","Evaluation of Different Brood Comb Replacement Intervals on Colony Productivity of Honey Bees (Apis mellifera)","Shimu Debela","Rejected",""],
[701,"HBRC","Livestock","Api","Comparative Evaluation of Bailey Comb Change and Shook Swarm Methods for Increasing Beeswax Production.","Shimu Debela","Rejected",""],
[702,"HBRC","Livestock","Api","Biochemical markers of honey from Oromia: Authentication and association with phytochemical properties and antibacterial activity","Taye Negera and Zewdu Ararso","Rejected",""],
[703,"Harosabu","Livestock","Feeds","Desmodium intortum (Greenleaf desmodium) Nursery Observation Trial","Yerosan Wekgari","Accepted",""],
[704,"Harosabu","Livestock","Feeds","Optimizing of vetch row configuration and sowing date to enhance forage biomass yield and quality in Elephant grass-vetch intercropping systems, western Oromia","Yerosan Wekgari","Accepted",""],
[705,"Harosabu","Livestock","Feeds","Siratro (Macroptillium atropurpurem) Preliminary yield trial in west and kellam wollega zones of Oromia","Shedad Sultan","Accepted",""],
[706,"Harosabu","Livestock","Feeds","Setaria grass (Setaria sphacelata) nursery observation trial at Haro Sabu","Shedad Sultan","Accepted",""],
[707,"Harosabu","Livestock","Feeds","Trifolium (Clover) Species Evaluation Performance in Different Agro-ecological of West and Kellam Wollega Zones, Oromia, Ethiopia","Shedad Sultan","Accepted",""],
[708,"Harosabu","Livestock","Feeds","Cowpea (Vigna unguiculata L.) nursery observation trial at Haro Sabu ARC","Yerosan Wekgari","Accepted",""],
[709,"Harosabu","Livestock","Feeds","Glycine (Neonotonia wightii) Nursery Observation Trial","Yerosan Wekgari","Accepted",""],
[710,"Harosabu","Livestock","Feeds","Evaluation of Straw Yield and Quality of Acid Tolerant Finger Millet (Eleusine coracana L.) Varieties in Midland of Kellam Wollega Zone of Oromia, Ethiopia","Yerosan Wekgari","Rejected",""]
]

with open("/tmp/part2_a.json", "w") as f:
    json.dump(data, f)
print("Part 2A written:", len(data))
